export const ErrorMessages = {
  noInternet: 'You are offline. Keep logging and we will sync when the connection is back.',
  aiUnavailable: 'Context AI is unavailable right now. Try again in a few minutes.',
  saveFailed: 'I could not save right now. Your data stays safe and I will retry.',
  barcodeNotFound: 'I could not find that barcode. You can search the food or enter it manually.',
  paypalError: 'There was a payment problem. Nothing was charged.',
  photoAIFailed: 'I could not read that meal clearly. Try another photo or enter it manually.',
  voiceLogFailed: 'I could not understand that voice entry. Try again or enter it manually.',
  loginFailed: 'I could not sign you in. Check your details and try again.',
  registerFailed: 'I could not create your account. Try again.',
  sessionExpired: 'Your session expired. Sign in again to continue.',
  premiumRequired: 'This feature is part of Premium.',
  generic: 'Something went wrong. Try again in a moment.',
  loadFailed: 'I could not load the data. Pull to try again.',
  syncFailed: 'I could not sync. Your data is still safe locally.',
  permissionDenied: 'I need your permission to continue. You can change it in Settings.',
} as const;

export const AuthStrings = {
  welcome: {
    title: 'Train today.',
    subtitle: 'No excuses. No dashboards.',
    cta: 'Start free',
    login: 'I already have an account',
  },
  login: {
    title: 'Welcome back',
    email: 'Email',
    password: 'Password',
    cta: 'Sign in',
    forgot: 'I forgot my password',
    noAccount: 'I do not have an account',
    register: 'Create account',
  },
  register: {
    title: 'Create account',
    name: 'Your name',
    email: 'Email',
    password: 'Password (minimum 8 characters)',
    cta: 'Create my account',
    haveAccount: 'I already have an account',
    login: 'Sign in',
    tosLabel: 'I accept the',
    tos: 'Terms of Service',
    and: 'and the',
    privacy: 'Privacy Policy',
    healthConsent: 'I consent to Vyra processing my health data to personalize my experience.',
    medicalDisclaimer:
      'I understand Vyra is not a medical device and does not replace professional evaluation.',
  },
  medicalModal: {
    title: 'Before you start',
    body:
      'Vyra is a wellness and fitness app. It is not a certified medical device and does not replace professional consultation, diagnosis, or treatment.',
    cta: 'Understood, continue',
  },
} as const;

export const OnboardingStrings = {
  step1: {
    title: 'What is your main goal?',
    subtitle: 'We use it to prepare a coherent starting experience.',
    goals: {
      lose_fat: 'Lose fat',
      gain_muscle: 'Gain muscle',
      general_health: 'General health',
      sport_performance: 'Sport performance',
      mental_wellbeing: 'General wellbeing',
    },
  },
  step2: {
    title: 'Where do you train?',
    subtitle: 'This lets us filter the right routine and exercise type.',
    gender: {
      label: 'Biological sex',
      male: 'Male',
      female: 'Female',
      non_binary: 'Non-binary',
      prefer_not_to_say: 'Prefer not to say',
    },
    age: 'Age',
    height: 'Height (cm)',
    weight: 'Current weight (kg)',
    goalWeight: 'Goal weight (kg, optional)',
  },
  step3: {
    title: 'What is your main focus?',
    subtitle: 'Choose the main module first and add support modules if you want.',
    levels: {
      0: 'Very low',
      1: 'Low',
      2: 'Moderate',
      3: 'Active',
      4: 'Very active',
      5: 'Athlete',
    },
    equipment: {
      label: 'Available equipment',
      gym: 'Full gym',
      home: 'Home with basic equipment',
      both: 'Both',
      outside: 'Outdoors',
      none: 'No equipment',
    },
  },
  step4: {
    title: 'All set',
    subtitle: 'We leave your first action ready for today.',
    wakeTime: 'Wake time',
    sleepTime: 'Sleep time',
    fasting: {
      label: 'Intermittent fasting',
      yes: 'Yes',
      no: 'No',
    },
    protocol: 'Protocol',
  },
  step5: {
    title: 'Premium',
    subtitle: 'Advanced functions, no virtual economy, and less noise.',
    features: {
      aiCoach: 'Context AI',
      photoLog: 'Photo logging',
      voiceLog: 'Voice logging',
      unlimitedHistory: 'Extended history',
      correlations: 'More context and correlations',
      noAds: 'Ad-free experience',
    },
    monthly: '$12.99/month',
    yearly: '$99.99/year',
    yearlyNote: 'Yearly savings',
    trialCta: 'Go to PayPal checkout',
    freeCta: 'Continue free',
    freeNote: 'Free version with core features.',
  },
  next: 'Next',
  back: 'Back',
  skip: 'Skip',
  finish: 'Start',
  step: 'Step',
  of: 'of',
} as const;

export const DashboardStrings = {
  greeting: {
    morning: 'Good morning',
    afternoon: 'Good afternoon',
    evening: 'Good evening',
  },
  dailyScore: 'Daily signal',
  streak: 'streak days',
  bestStreak: 'best streak',
  checkIn: 'Daily check-in',
  checkInDone: 'Check-in done',
  quickActions: 'Quick logs',
  todayMissions: 'This week',
  aiInsight: 'Today context:',
  noInsight: 'Complete your first entry to receive context.',
} as const;

export const ModuleNames = {
  water: 'Water',
  steps: 'Steps',
  fasting: 'Fasting',
  sleep: 'Sleep',
  nutrition: 'Nutrition',
  weight: 'Weight',
  workout: 'Workout',
  mental: 'Wellbeing',
  female: 'Female health',
  supplements: 'Supplements',
  recovery: 'Recovery',
} as const;

export const ModuleEmojis = {
  water: '💧',
  steps: '🚶',
  fasting: '⏳',
  sleep: '😴',
  nutrition: '🥗',
  weight: '⚖️',
  workout: '🏋️',
  mental: '🧠',
  female: '🌸',
  supplements: '💊',
  recovery: '🛌',
} as const;

export const Disclaimers = {
  context: 'Vyra context AI offers general guidance and does not replace professional care.',
  supplements:
    'Vyra does not recommend supplement doses or combinations. Consult a health professional.',
  bmi: 'BMI and body fat are estimates. They are not a medical diagnosis.',
  cycle: 'Cycle prediction is an estimate and must not be used as contraception.',
  fasting24h: 'Extended fasting is not right for everyone. Ask a professional if you have doubts.',
  deficitHigh:
    'An aggressive calorie deficit can be harmful long term. Consider professional nutrition advice.',
} as const;

export const NotificationStrings = {
  waterReminder: (ml: number, goal: number) => `You are at ${ml} ml of ${goal} ml. Add a glass?`,
  stepsReminder: (steps: number, goal: number) =>
    `You are at ${steps.toLocaleString()} of ${goal.toLocaleString()} steps.`,
  streakDanger: (days: number) =>
    `Your ${days}-day streak is at risk. One short action today keeps it alive.`,
  fastingPhase: (phase: string) => `You entered ${phase}. Your fast is still on track.`,
  goalReached: (goal: string) => `${goal} goal reached.`,
  prAchieved: (exercise: string, weight: number) => `New record: ${weight} kg on ${exercise}.`,
} as const;

export const General = {
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  delete: 'Delete',
  edit: 'Edit',
  close: 'Close',
  back: 'Back',
  continue: 'Continue',
  retry: 'Try again',
  loading: 'Loading...',
  syncing: 'Syncing...',
  today: 'Today',
  yesterday: 'Yesterday',
  week: 'Week',
  month: 'Month',
  all: 'All',
  free: 'Free',
  premium: 'Premium',
  upgrade: 'Upgrade to Premium',
  history: 'History',
  settings: 'Settings',
  profile: 'Profile',
  logout: 'Sign out',
  or: 'or',
  and: 'and',
  of: 'of',
  for: 'for',
  done: 'Done',
  add: 'Add',
  remove: 'Remove',
  search: 'Search',
  noResults: 'No results',
  empty: 'Nothing here yet.',
  offline: 'Offline',
  online: 'Online',
} as const;
