export { ShellStrings } from './strings.shell.zh';

export const ErrorMessages = {
  noInternet: '这里没有信号。继续记录,当连接恢复时我会同步。',
  aiUnavailable: 'AI 层现在不可用。请稍后几分钟后重试。',
  saveFailed: '现在无法保存。您的数据是安全的,我会重试。',
  barcodeNotFound: '找不到该代码。您可以搜索食物或手动输入。',
  paymentError: '无法完成此操作。未应用任何更改。',
  photoAIFailed: '无法很好地读取该餐食。请尝试另一张照片或手动输入。',
  voiceLogFailed: '无法理解该语音记录。请重试或手动输入。',
  loginFailed: '无法登录。检查您的详细信息并重试。',
  registerFailed: '无法创建您的帐户。请重试。',
  sessionExpired: '您的会话已过期。再次登录以继续。',
  premiumRequired: '此功能已在您的当前访问权限中可用。',
  generic: '出错了。请稍后重试。',
  loadFailed: '无法加载数据。向下滑动以重试。',
  syncFailed: '无法同步。您的数据仍然本地保存。',
  permissionDenied: '我需要您的许可才能继续。您可以在设置中更改。',
} as const;

export const AuthStrings = {
  welcome: {
    title: '您的健身,从今天开始清楚。',
    subtitle: '训练、膳食、水、睡眠和进度在一个应用中。',
    cta: '创建免费帐户',
    login: '登录我的帐户',
    legal: '继续即表示您接受我们的条款。',
  },
  login: {
    title: '欢迎回来',
    email: '电子邮件',
    password: '密码',
    cta: '登录',
    forgot: '我忘记了密码',
    noAccount: '我没有帐户',
    register: '创建帐户',
  },
  register: {
    title: '创建帐户',
    name: '您的名字',
    email: '电子邮件',
    password: '密码(至少 8 个字符)',
    cta: '创建我的帐户',
    haveAccount: '我已经有帐户',
    login: '登录',
    tosLabel: '我接受',
    tos: '服务条款',
    and: '和',
    privacy: '隐私政策',
    healthConsent: '我同意 Vyra 处理我的健康数据以个性化我的体验。',
    medicalDisclaimer:
      '我理解 Vyra 不是医疗设备,不能替代专业评估。',
  },
  medicalModal: {
    title: '开始前',
    body:
      'Vyra 是一个健康和健身应用。它不是认证医疗设备,不能替代专业咨询、诊断或治疗。',
    cta: '我理解了,继续',
  },
} as const;

export const OnboardingStrings = {
  step1: {
    title: '您的主要目标是什么?',
    subtitle: '我们使用它来准备一致的初始体验。',
    goals: {
      lose_fat: '减肥',
      gain_muscle: '增肌',
      general_health: '一般健康',
      sport_performance: '运动表现',
      mental_wellbeing: '总体福祉',
    },
  },
  step2: {
    title: '您在哪里训练?',
    subtitle: '这样我们可以过滤例程和练习类型。',
    gender: {
      label: '生物学性别',
      male: '男性',
      female: '女性',
      non_binary: '非二进制',
      prefer_not_to_say: '我更喜欢不说',
    },
    age: '年龄',
    height: '身高(厘米)',
    weight: '当前体重(公斤)',
    goalWeight: '目标体重(公斤,可选)',
  },
  step3: {
    title: '您的主要重点是什么?',
    subtitle: '选择主要模块,然后根据需要添加支持。',
    levels: {
      0: '非常低',
      1: '低',
      2: '中等',
      3: '活跃',
      4: '非常活跃',
      5: '运动员',
    },
    equipment: {
      label: '可用设备',
      gym: '完整的体育馆',
      home: '家中有基本设备',
      both: '两者',
      outside: '户外',
      none: '没有设备',
    },
  },
  step4: {
    title: '一切就绪',
    subtitle: '我们为今天准备了第一个行动。',
    wakeTime: '醒来时间',
    sleepTime: '睡眠时间',
    fasting: {
      label: '间歇性禁食',
      yes: '是',
      no: '否',
    },
    protocol: '协议',
  },
  step5: {
    title: '开放式访问',
    subtitle: '从第一天起高级功能就准备好了。',
    features: {
      aiCoach: '上下文 AI',
      photoLog: '照片记录',
      voiceLog: '语音记录',
      unlimitedHistory: '扩展历史',
      correlations: '更多上下文和关联',
      noAds: '从第一天开始开放访问',
    },
    monthly: '开放式访问',
    yearly: '一切就绪',
    yearlyNote: '没有解锁',
    trialCta: '进入 Vyra',
    freeCta: '继续',
    freeNote: '产品已打开并准备使用。',
  },
  next: '下一步',
  back: '返回',
  skip: '跳过',
  finish: '开始',
  step: '步骤',
  of: '的',
} as const;

export const DashboardStrings = {
  greeting: {
    morning: '早上好',
    afternoon: '下午好',
    evening: '晚上好',
  },
  dailyScore: '每日信号',
  streak: (days: number) => `${days} ${days === 1 ? '天' : '天'}连续`,
  bestStreak: '最佳连胜',
  checkIn: '每日登记',
  checkInDone: '登记完成',
  quickActions: '快速记录',
  todayMissions: '本周',
  aiInsight: '今天的上下文:',
  noInsight: '完成您的第一条记录以获得上下文。',
} as const;

export const ModuleNames = {
  water: '水',
  steps: '步数',
  fasting: '禁食',
  sleep: '睡眠',
  nutrition: '营养',
  weight: '体重',
  workout: '锻炼',
  mental: '福祉',
  female: '女性健康',
  supplements: '补充剂',
  recovery: '恢复',
} as const;

export const ModuleEmojis = {
  water: '💧',
  steps: '🚶',
  fasting: '⏳',
  sleep: '😴',
  nutrition: '🥗',
  weight: '⚖️',
  workout: '🏋️',
  mental: '🧠',
  female: '🌸',
  supplements: '💊',
  recovery: '🛌',
} as const;

export const Disclaimers = {
  context: 'Vyra 的上下文 AI 提供一般指导,不能替代专业护理。',
  supplements:
    'Vyra 不推荐补充剂的剂量或组合。请咨询健康专业人士。',
  bmi: 'BMI 和体脂百分比是估计值。不是医学诊断。',
  cycle: '周期预测是估计的。不应用作避孕方法。',
  fasting24h:
    '长期禁食不适合所有人。如有疑虑,请咨询专业人士。',
  deficitHigh:
    '过度热量赤字可能在长期内有害。请咨询营养师。',
} as const;

export const NotificationStrings = {
  waterReminder: (ml: number, goal: number) => `您有 ${ml} 毫升 ${goal} 毫升。我们加一杯吗?`,
  stepsReminder: (steps: number, goal: number) =>
    `您有 ${steps.toLocaleString()} ${goal.toLocaleString()} 步。`,
  streakDanger: (days: number) =>
    `您 ${days} 天的连胜处于危险中。今天做一个小动作就能保持活力。`,
  fastingPhase: (phase: string) => `您进入了 ${phase}。您的禁食进行顺利。`,
  goalReached: (goal: string) => `达到 ${goal} 目标。`,
  prAchieved: (exercise: string, weight: number) => `${exercise} 新纪录:${weight} 公斤。`,
} as const;

export const General = {
  save: '保存',
  cancel: '取消',
  confirm: '确认',
  delete: '删除',
  edit: '编辑',
  close: '关闭',
  back: '返回',
  continue: '继续',
  retry: '重试',
  loading: '加载中...',
  syncing: '同步中...',
  today: '今天',
  yesterday: '昨天',
  week: '周',
  month: '月',
  all: '全部',
  free: '免费',
  premium: '包含',
  upgrade: '查看访问',
  history: '历史',
  settings: '设置',
  profile: '个人资料',
  logout: '登出',
  or: '或者',
  and: '和',
  of: '的',
  for: '为了',
  done: '完成',
  add: '添加',
  remove: '移除',
  search: '搜索',
  noResults: '没有结果',
  empty: '这里还没有任何东西。',
  offline: '离线',
  online: '已连接',
} as const;

export const ValidationMessages = {
  emailInvalid: '电子邮件格式无效。',
  passwordRequired: '密码是必需的。',
  passwordTooShort: '密码必须至少 8 个字符。',
  ageTooYoung: '您必须至少 13 岁才能使用 Vyra。',
  ageInvalid: '输入的年龄无效。',
  weightTooLow: '最小体重为 20 公斤。',
  weightInvalid: '输入的体重无效。',
  heightTooLow: '最小身高为 50 厘米。',
  heightInvalid: '输入的身高无效。',
  waterAmountTooHigh: '每次记录的最大数量为 5000 毫升。',
  waterGoalTooLow: '最小目标为 500 毫升。',
  waterGoalTooHigh: '最大目标为 10000 毫升。',
  stepsGoalTooLow: '最小目标为 1000 步。',
  stepsGoalTooHigh: '最大目标为 100000 步。',
  foodAmountTooHigh: '最大数量为 5000 克。',
  barcodeScanEmpty: '扫描的条形码为空。',
  barcodeTypeUnrecognized: '我们无法识别条形码类型。',
  barcodeProcessError: '处理条形码时出错。',
  emailAlreadyExists: '该电子邮件已注册。您可以使用该帐户登录。',
  networkError: '我们现在无法连接到 Vyra。检查您的连接并重试。',
  tempSessionError: '现在无法打开临时会话。请重试。',
  emailSendError: '我们无法发送电子邮件。验证地址。',
  accountDeleteSuccess: '您的请求已处理,我们已关闭会话。最终删除遵循现行政策。',
} as const;

export const FastingLabels = {
  activePhase: '活跃禁食',
  autophagy: '自噬作用',
  deepFast: '深度禁食',
  extendedFast: '延长禁食',
  gentleEntry: '低恢复日的温和进入',
  omad: 'OMAD — 一天一餐',
  omadAlt: '一天一餐(OMAD)',
  fastDay: '限制日(5:2 协议)',
  hungryPhaseWarning: '在这个阶段,饥饿和疲劳通常会增加。本周最好选择较短的协议。',
  consistencyTip: '您的模式表明稍微更灵活的窗口可以改善每周的连贯性。',
  progressTip: '您反复遗漏。中间协议可以帮助巩固习惯。',
  readyProgress: '您已完成几个 16:8 并有余量。您已准备好升级到 18:6。',
  autophagyCountdown: '距自噬作用还有 45 分钟。您已经来这么远了,再坚持一下。',
  fastingCancelled: '禁食已取消。下次会更好!',
  fast52Started: '根据您的时间表开始 5:2 禁食。',
  stayConsistent: '在这个阶段,坚持稳定的协议比追求额外的小时更重要。16:8 今天是一个不错的基础。',
  focusConsistency: '今天坚持当前协议。专注于一致性和明智的禁食中断。',
  menstrualGuidance: '月经期:如果身体要求降低负担,使用 12:12 或 14:10。恢复第一。',
  lutealGuidance: '黄体期:通常 14:10 或 16:8 与更简单的禁食中断效果更好。',
  ovulatoryGuidance: '排卵期:如果睡眠良好,通常对标准协议有良好的耐受性。',
  cancelled: '禁食已取消',
  fedPhase: '进食后',
  fedPhaseDesc: '消化。胰岛素升高。',
  activePhaseDesc: '糖原开始被消耗。',
  ketosisPhase: '初始酮症',
  ketosisPhaseDesc: '身体开始燃烧脂肪。',
  autophagyDesc: '活跃的细胞回收。最大效益。',
  deepFastDesc: '生长激素上升。强烈的细胞再生。',
  extendedFastDesc: '生存模式。最大细胞生存。',
  protocol12_12Desc: '低恢复日的温和进入',
  protocol14_10Desc: '保持坚持的中间步骤',
  protocol16_8Desc: '16 小时禁食,8 小时进食 — 最受欢迎',
  protocol18_6Desc: '18 小时禁食,6 小时窗口',
  protocol20_4Desc: '战士饮食',
  protocol23_1Desc: 'OMAD — 一天一餐',
  protocolOMADDesc: '一天一餐(OMAD)',
  protocol24hDesc: '完整的 24 小时禁食。',
  protocol5_2Desc: '限制日(5:2 协议)',
  protocolCustomDesc: '自定义',
} as const;

export const FemaleHealthLabels = {
  menstrual: '月经的',
  follicular: '卵泡期',
  ovulation: '排卵期',
  luteal: '黄体期',
  weightVariations: '体重变化可能因月经周期阶段而异。',
  hydrationMenstrual: '月经期间额外补水。',
  fastingMenstrual: '温和协议(12:12 或 14:10)。',
  sleepMenstrual: '优先考虑恢复性睡眠。',
  trainingRecovery: '积极恢复、流动性或轻度力量。',
  fastingFollicular: '对标准协议有更好的耐受性(16:8)。',
  nutritionFollicular: '增加蛋白质和锌以改善表现和恢复。',
  trainingOvulation: '高能量窗口:力量/高强度。',
  fastingOvulation: '如果恢复良好,可以维持 16:8 或 18:6。',
  fastingLuteal: '在黄体期可能更难;如果出现强烈饥饿感,请缩短协议。',
  nutritionLuteal: '增加镁和复杂碳水化合物以获得稳定的能量。',
  nextOvulationNotice: '明天您进入排卵窗口:我们准备了高强度训练。',
  menstruationNotice: '您的月经即将开始。本周优先考虑额外补水和恢复。',
  cycleVariation: '您的周期在月经之间相差超过 7 天。值得咨询妇科医生。',
  needSupport: '您需要支持',
  menstrualTraining: '积极恢复、流动性或轻度力量。',
  menstrualFasting: '优先考虑短期协议(12-14 小时)或禁食休息。',
  menstrualNutrition: '加强铁、omega-3 和抗炎食物。',
  menstrualWeightContext: '在月经/黄体期,由于液体可能会有 1-3 公斤的变化。',
  follicularTraining: '增加负荷和体积的好阶段。',
  follicularFasting: '对标准协议有更好的耐受性(16:8)。',
  follicularNutrition: '增加蛋白质和锌以改善表现和恢复。',
  ovulationTraining: '高能量窗口:力量/高强度。',
  ovulationFasting: '如果恢复良好,可以维持 16:8 或 18:6。',
  ovulationNutrition: '优先考虑抗氧化剂和优质碳水化合物。',
  lutealTraining: '以中等强度保持一致性。',
  lutealFasting: '在黄体期可能更难;如果出现强烈饥饿感,请缩短协议。',
  lutealNutrition: '增加镁和复杂碳水化合物以获得稳定的能量。',
  lutealWeightContext: '在黄体期保留液体并看到临时增加是正常的。',
} as const;

export const WorkoutLabels = {
  freesession: '自由课程',
  base: '基础',
  building: '建筑',
  consolidation: '巩固',
  muscleGroupsFatigued: '有 ${tired} 个肌肉群最近负荷较大。',
  lowerIntensity: '降低强度或选择技术课程是有意义的,以继续进步而不打破街区。',
  controlledSession: '有空间训练,但受控课程会给您更好的结果。',
  recordSet: '${exercise} 新纪录:${weight} 公斤',
} as const;

export const TabBarCopy = {
  quickLogHint: '打开面板以记录水、体重、禁食或睡眠。',
} as const;

export const BmiCategories = {
  underweight: '体重不足',
  normal: '正常体重',
  overweight: '超重',
  obesity: '肥胖症',
} as const;

export const ComponentMessages = {
  balanceCardNoData: '今天 Vyra 余额,数据不足',
  balanceNoData: '数据还不足够。',
  lastWeight: '最后的体重',
  noSession: '没有课程',
  seriesCount: '今天的组',
  isotonic: '等渗的',
  tea: '茶',
  coffee: '咖啡',
  workoutLogged: '课程已记录',
  syncSlowWarning: '初始加载花费了太多时间。我们打开了一个可用的会话,您可以在不关闭应用的情况下重试同步。',
  syncSlowWarning2: '初始加载花费的时间超过预期。您可以安全地进入并从应用中重试同步。',
  autoSessionRecovery: '我们无法自动恢复您的会话。您可以重试而不关闭应用。',
  retrySyncPartial: '重试部分同步',
  retrySync: '重新尝试',
  maintenanceMessage: '如果您使用的是水、睡眠、体重、营养或锻炼,本地仍然存在。只是等待系统返回并完成对齐其余部分。',
  authCallbackError: '提供商没有返回有效的会话数据。',
  invalidSession: '没有活跃的会话。',
  dailyLimitReached: '达到每日限制',
  aiBrainResting: '我的 AI 大脑在休息。',
  systemPrompt: '用中文回答,简洁、实用、安全。',
} as const;

export const MentalLabels = {
  needSupport: '您需要支持',
  emotionalTrend: '我们检测到向下的情绪趋势。今天优先恢复和一个小行动。',
} as const;

export const ReadinessLabels = {
  noConnection: '现在没有连接。我们显示您最后可用的状态。',
  exceptional: '非凡的一天',
  veryGood: '很好的一天',
} as const;

export const ReferralMessages = {
  noValidSession: '您需要有效的会话才能打开您的邀请。',
  serviceUnavailable: '邀请服务现在不可用。请稍后重试。',
  notConfigured: '此构建中未配置邀请后端。',
  loadFailed: '无法加载您的邀请。',
  noData: '邀请回复没有有用的数据。几秒钟后重试。',
  networkFailed: '我们无法连接到邀请服务。',
  notAvailable: '此构建中的邀请不可用。',
  redeemFailed: '无法兑换。',
} as const;

export const NotificationMessages = {
  routineReady: '您今天的例程已准备好',
  movementBlockReady: '您的移动块已准备好',
  movementBlockCta: '打开 Vyra 并今天完成一个短块。保持节奏比完美更重要。',
  routineStillOpen: '您的例程仍然开放',
  routineStillOpenDesc: '您有 ${name} 剩余。您可以返回或快速从通知中标记。',
  recommendedRoutineReady: '您今天的例程已准备好',
  recommendedRoutineDesc: '${name} 今天适合。您打开或标记而不浪费时间。',
  hydrationReminder: '💧 是时候补水了',
  hydrationReminderDesc: '${name},今天你仍然可以接近你的目标。',
  streakAtRisk: '🔥 您的连胜处于危险中',
  streakAtRiskDesc: '${name},今天快速记录 1 个并保持连胜活力。',
  hydrationSmartReminder: '💧 智能提醒',
  streakSmartReminder: '🔥 连胜处于危险中',
} as const;

export const PrivacyTexts = {
  dataExample: '水、步数、睡眠、体重、膳食、禁食、锻炼和每日摘要。',
  healthDataReduction: '减少对体重、心理健康和女性健康的纯文本存储量。',
} as const;

export const ExplorePageStrings = {
  title: '计划',
  heroEyebrow: '活动目标',
  heroBody: '计划不再用作第二个主页:从这里您应该看到您的路径、您的块和下一个有用的步骤。',
  loseFat: '减肥',
  gainMuscle: '增肌',
  performance: '表现',
  organizeHabits: '组织习惯',
  recovery: '恢复',
  yourCurrentPath: '您目前的路径',
  fallbackCoaching: '这周坚持一个精心选择的决定比一次打开十条路径更能推动局面。',
  recommended: '为您推荐',
  coaching: '背景教练',
  weeklyPriority: '本周优先事项',
  momentum: '挑战和动力',
  streakLabel: '连胜',
  sessionThisWeek: '周内会议',
  usefulLibrary: '有用的库',
  programTitle: '活跃程序',
  noneSelected: '还没有选择程序',
  activeWeek: '第 {{week}} 周。街区已经在运行,下一个决定应该来自这里。',
  suggested: '没有活跃的程序,但已经有建议的例程可以开始方向。',
  chooseRoute: '现在最好选择一条指导路线,而不是浏览完整目录。',
  nextAction: '下一步行动',
  backToSession: '返回会话',
  chooseProgram: '选择程序',
  progress: '进步',
  thisWeek: '{{sessions}}/{{goal}} 本周',
  continueProgram: '继续程序',
  nextFocusEyebrow: '下一个调整',
  nextFocusBody: '今天的背景阅读已经发现了最值得先推的东西。',
  workoutEyebrow: '锻炼',
  openCurrent: '打开您的当前块',
  chooseGuided: '选择指导程序',
  workoutOpenBody: '查看周、日和负荷连续性,不会偏离主路径。',
  workoutChooseBody: '以清晰的路径开始,而不是浏览无优先级的松散例程。',
  nutritionEyebrow: '营养',
  nutritionTitle: '简单的营养重置',
  nutritionBody: '记录良好的一天胜过您无法使用的复杂电子表格。',
  recoveryEyebrow: '恢复',
  sleepTitle: '本周睡眠更好',
  sleepBody: '在要求更多力量和更多一致性之前调整休息。',
  waterTitle: '补水程序',
  waterBody: '简单的水基础和每日节奏使系统的其余部分表现更好。',
  libraryEyebrow: '有用的库',
  plannerTitle: '每周计划',
  plannerBody: '可视化周并准备下一个块而不打开额外的模块。',
  mealTitle: '记录一餐',
  mealBody: '回到基础并在两个步骤中清晰地完成一天。',
  sleepLibraryTitle: '查看睡眠',
  sleepLibraryBody: '阅读最后一晚,并以更大的判断力降低或提高负荷。',
  progressTitle: '阅读真实进度',
  progressBody: '如果您想要更深层的背景,这里您会看到趋势,而不仅仅是单独的记录。',
  milestoneDone: '周遭在进行中。现在是维持块的质量而不添加噪声的时候了。',
  milestonePending: '您缺少 {{count}} 个会话来关闭您的每周目标。',
} as const;

export const HomePageStrings = {
  locale: 'zh-CN',
  guestName: '用户',
  quickActionHint: '打开此快捷方式。',
  secondaryModuleHint: '打开此辅助模块。',
  notificationFallbackTitle: 'Vyra 通知',
  notificationFallbackBody: '最近活动可用。',
  greeting: '你好, {{name}}',
  streakPillLabel: (days: number) => `当前连胜: ${days} ${days === 1 ? '天' : '天'}`,
  streakPillHint: '打开进度以查看您的一致性。',
  openNotifications: '打开最近的通知',
  openNotificationsHint: '显示交付控制和最新的警告。',
  openQuickLog: '打开快速日志',
  openQuickLogHint: '打开一张纸来记录水、睡眠、体重或禁食而不离开主页。',
  openProfile: '打开个人资料',
  openProfileHint: '打开您的帐户、模块和设置。',
  activeWorkoutAccessibility: '活跃课程, {{name}}, {{count}} 正在进行的练习',
  activeWorkoutEyebrow: '活跃会话',
  activeWorkoutFallbackTitle: '正在进行的锻炼',
  activeWorkoutMeta: '此设备上进行 {{count}} 练习。',
  activeWorkoutCta: '回到锻炼',
  nextStepEyebrow: '下一步',
  nextStepHint: '选择最能推动您一天的前面,并从这里解决。',
  planEyebrow: '今天',
  planTitle: '日计划',
  planSummary: '{{done}} 的 {{total}} 前面已覆盖。',
  planExpand: '查看完整计划',
  planCollapse: '显示更少',
  momentumEyebrow: '一致性',
  streakEyebrow: '连胜',
  streakStartToday: '今天开始你的连胜',
  streakRunning: (days: number) => `${days} ${days === 1 ? '天' : '天'}连续`,
  streakDoneBody: '今天已经算了。一个小动作支持你的连续性。',
  streakPendingBody: '您只需要水、步数、营养或锻炼就可以拯救这一天。',
  streakView: '查看连胜和进度',
  streakSave: '立即保存我的连胜',
  sectionsQuickActions: '快速行动',
  sectionsThisWeek: '本周',
  weekDone: '{{day}}: 本周完成的一天',
  weekTodayPending: '{{day}}: 今天仍在待定',
  weekPending: '{{day}}: 不完整',
  weekSummary: '{{count}} 本周 7 天',
  pauseBody: '您 {{days}} 天没有记录。今天用一些小东西恢复。',
  pauseCta: '立即恢复',
  pauseHint: '打开建议的操作以返回记录活动。',
  aiEyebrow: 'Vyra 建议',
  notificationsTitle: '最近的通知',
  notificationsEmpty: '这里还没有最近的活动可显示。',
  notificationsViewAll: '查看全部',
  notificationsAccessibility: '查看所有通知',
  notificationsHint: '打开通知交付控制和静音小时。',
} as const;

export const ProgressPageStrings = {
  sectionEnergy: '能量和体重',
  sectionEnergyHint: '什么是重要的取决于您选择的目标。',
  workoutSessions: '会话',
  sleepRecovered: '坚实的基础,可以维持今天的正常负荷。',
  sleepRecovering: '您的睡眠不如理想。调节强度是有意义的。',
  muscleChest: '胸部',
  muscleBack: '背',
  muscleShoulders: '肩膀',
  muscleArms: '手臂',
  muscleCore: '核心',
  muscleLegs: '腿',
  caloriesEyebrow: '今天的卡路里',
  weightEyebrow: '体重和方向',
  viewPrograms: '查看程序',
  backHome: '返回首页',
} as const;

export const WaterHydrationMessages = {
  goalReached: '目标已关闭。维持这个简单的模式是支持模块的原因。',
  behindAndAfternoon: '今天已经过去了很多。现在两条连续的记录完全改变了收盘。',
  lowProgress: '仍有空间恢复步伐而不增加复杂性。',
  onTrack: '你做得很好。与其在最后堆积所有东西相比,保持间隔的小杯子更值得。',
} as const;

export const StepsProgressMessages = {
  goalMet: '您达到或超过了您的目标。 {{totalSteps}} 今天的步骤。',
  almostThere: '几乎。您需要 {{remaining}} 步来达到目标。',
  goodProgress: '你做得很好。您已经为更好地结束这一天定下了步调。',
  justStarted: '很好的开始。继续添加。',
} as const;

export const HomeDetailStrings = {
  hero: {
    readiness: {
      eyebrow: '准备就绪',
      pending: '今天的基础',
      awaiting: '阅读在进行中',
      support: '通过睡眠、水、食物和运动,这个分数变得更准确。',
      noData: '我们仍在建立您的每日阅读。每个有用的记录都会增加更多背景。',
      weeklyAverage: '平均',
      projected: '可能关闭',
      stability: '稳定性',
      focus: '现在关注',
      cta: '查看详情',
    },
    fasting: {
      eyebrow: '活跃禁食',
      protocol: '协议 {{protocol}}',
      eatingWindowOpen: '进食窗口打开',
      accumulated: '{{hours}}h {{minutes}}m 累积。',
      close: '关闭禁食',
      complete: '完成禁食',
    },
    female: {
      eyebrow: '循环',
      phaseDay: '阶段 {{phase}} · 日 {{day}}',
      prioritizeRecovery: '优先恢复和规律性',
      trainStrong: '强烈训练的好一天',
      registerToday: '今天登记',
    },
    nutrition: {
      eyebrow: '营养',
      percentCalories: '{{pct}}% 今天的卡路里',
      caloriesOf: '{{current}} 的 {{target}} 千卡',
      cta: '记录一餐',
    },
    steps: {
      eyebrow: '步数',
      title: '今天的目标',
      ofSteps: '的 {{goal}} 步',
      estimatedCalories: '{{kcal}} 千卡估计。',
      cta: '查看详情',
    },
    sleep: {
      eyebrow: '睡眠',
      recovered: '坚实的基础,可以维持今天的正常负荷。',
      recovering: '您的睡眠不如理想。调节强度是有意义的。',
      view: '查看睡眠',
      log: '记录睡眠',
    },
    workoutRest: {
      eyebrow: '今天 · 休息',
      fallbackTitle: '主动恢复',
      body: '今天有意义的是降低负荷。您可以查看块的下一个会话而不匆忙。',
      cta: '查看明天',
    },
    workout: {
      eyebrow: '今天',
      activeFallback: '正在进行的会话',
      idleFallback: '今天训练',
      prYesterday: '公关昨天',
      activeMeta: '{{count}} 练习 · 会话打开',
      routineMeta: '{{count}} 练习 · ~{{minutes}} 分钟',
      emptyMeta: '今天还没有准备好的例程。',
      resume: '回到锻炼',
      trainNow: '现在训练',
    },
  },
  workoutProgram: {
    week: '第 {{week}} 周 · {{day}}',
    progress: '{{pct}}% 块',
    todayRoutine: '{{day}} · 日常',
    nextSuggestion: '{{day}} · 下一个建议',
    active: '活跃会话',
    exercises: '{{count}} 练习',
  },
  metrics: {
    waterGoal: '{{pct}}% 目标',
    sleepBelowGoal: '低于目标',
    steps: '{{pct}}% · {{kcal}} 千卡',
    noTrend: '趋势仍然很短',
    weeklyTrend: '{{sign}}{{value}} 本周',
  },
  quickActions: {
    logMeal: '记录一餐',
    addWater: '添加水',
    resumeWorkout: '回到锻炼',
    trainNow: '现在训练',
    logSleep: '记录睡眠',
    openQuickLog: '打开快速日志',
  },
} as const;

export const ForgotPasswordStrings = {
  title: '恢复您的访问',
  subtitle: '输入您的电子邮件,我们会发送说明。',
  send: '发送说明',
  sendFailed: '我们无法发送电子邮件。验证地址并重试。',
  successTitle: '检查您的收件箱',
  successBody: '如果您看不到,也要检查垃圾邮件。',
  resend: '重新发送',
  resendIn: (seconds: number) => `重新发送 ${seconds} 秒`,
  resendA11y: (seconds: number) =>
    seconds > 0 ? `重新发送 ${seconds} 秒` : '重新发送电子邮件',
  resendHint: '再次发送恢复电子邮件。',
} as const;

export const FastingMetabolicZones = {
  fed: {
    label: '饱了',
    description: '消化和精力仍然靠近最后一餐。',
  },
  early: {
    label: '适应',
    description: '能量开始容易下降,身体改变来源。',
  },
  fat: {
    label: '燃烧脂肪',
    description: '使用脂肪作为主要燃料变得更容易。',
  },
  ketosis: {
    label: '酮症',
    description: '酮症信号已经相当清晰地出现。',
  },
  autophagy: {
    label: '自噬作用',
    description: '高级窗口。这里背景和恢复更重要。',
  },
} as const;

export const BiometricLabels = {
  promptMessage: '解锁 Vyra',
  cancelLabel: '取消',
  fallbackLabel: '使用设备锁定',
  unlockButton: '解锁',
  verifyingButton: '验证中...',
  logoutHint: '关闭当前会话而不解锁应用。',
  accessibilityLabel: '解锁 Vyra',
} as const;

export const FemaleSymptoms = {
  colicos: '痉挛',
  hinchazon: '肿胀',
  fatiga: '疲劳',
  migrana: '偏头痛',
  cambios_humor: '情绪变化',
  energia_alta: '高能量',
} as const;

export const NutritionModule = {
  headerEditPrefix: '编辑',
  headerAddPrefix: '添加到',
  editingMode: {
    title: '编辑记录',
    description: '调整名称、克数或宏,并保存更改而不删除原始记录。',
  },
  logModes: {
    search: '搜索',
    photo: '照片',
    barcode: '条形码',
    manual: '手动',
  },
  library: {
    title: '快速库',
    description: '打开常用的东西或在搜索前恢复最近的记录。',
    tabs: {
      frequent: '频繁',
      recent: '最近',
    },
    itemA11y: (food: string) => `使用 ${food}`,
    itemHint: '加载此食物以确认数量和宏。',
    emptyFrequent: '您最喜欢的食物将出现在这里。',
    emptyRecent: '您最近的饭菜将出现在这里。',
  },
  search: {
    label: '搜索食物',
    placeholder: '示例:米饭、酸奶、鸡...',
    searching: '搜索食物...',
    libraryMatches: '已在您的库中',
    libraryDescription: '在打开一个长列表之前,我首先显示您已经使用过的匹配。',
    recentLabel: (timestamp: string) => `${timestamp}`,
    generalResults: '常规结果',
    resultsCount: (count: number) => {
      if (count >= 30) return `显示前 ${count} 个结果。如果找不到您要查找的内容,请打开更多结果或使用手动加载。`;
      return `我们为此搜索找到 ${count} 匹配。`;
    },
    noResults: (query: string) => `找不到"${query}"的食物。您可以重试或手动加载。`,
    noResultsLibrary: (query: string) => `找不到"${query}"的一般结果。如果之前使用过,则上方有匹配或手动加载。`,
    loadManual: '手动加载',
    moreResults: '查看更多结果',
  },
  preview: {
    title: '确认',
    hint: '在添加前确认宏和数量。',
    macros: {
      kcal: '千卡',
      protein: '蛋白质',
      carbs: '碳水化合物',
      fat: '脂肪',
      fiber: '纤维',
    },
    quantityLabel: '数量',
    portionHint: '1 份估计为 100 克,用于此确认。',
    addButton: (meal: string) => `添加到 ${meal}`,
  },
  photo: {
    title: '照片 AI',
    description: '拍照,检查 Vyra 检测到的内容,并在确认前调整部分。',
    takePhoto: '拍照',
    chooseGallery: '从画廊中选择',
    detection: '这是 AI 检测到的',
    confidence: (percent: number) => `信心 ${Math.round(percent * 100)}%`,
    lowConfidence: '检测的置信度很低。值得检查或转向手动搜索。',
    itemsSelected: (count: number) => `${count} 项 已标记。`,
    selectAtLeast: '至少标记一个项目以确认。',
    confirmDetection: '确认检测',
    manualSearch: '手动搜索',
    togglePortions: {
      show: '调整部分',
      hide: '隐藏部分调整',
    },
    estimated: (grams: number) => `${Math.round(grams)} 克估计`,
    noQuantity: '没有估计的数量',
    componentIncludeA11y: (name: string) => `包括 ${name}`,
    cameraMissingPermission: '需要相机许可。',
    galleryMissingPermission: '需要图库许可。',
  },
  manual: {
    title: '手动加载',
    nameLabel: '名称',
    namePlaceholder: '示例:米饭和鸡',
    quantityLabel: '数量',
    quantityUnit: 'g',
    proteinLabel: '蛋白质',
    proteinUnit: 'g',
    carbsLabel: '碳水化合物',
    carbsUnit: 'g',
    fatLabel: '脂肪',
    fatUnit: 'g',
    fiberLabel: '纤维',
    fiberUnit: 'g',
    submitEdit: '保存更改',
    submitAdd: (meal: string) => `添加到 ${meal}`,
  },
  errors: {
    loadingFood: '加载食物...',
  },
  modeA11y: (mode: string) => `模式 ${mode === 'search' ? '搜索' : mode === 'photo' ? '照片' : mode === 'barcode' ? '条形码' : '手动'}`,
  unitA11y: (unit: string) => `单位 ${unit}`,
  quickAmountA11y: (value: number) => `快速数量 ${value} 克`,
  portionAdjustmentNote: '我们根据您在确认前标记的项目调整了部分。',
} as const;

export const FemaleModule = {
  header: {
    title: '周期调整',
    subtitle: '模块、隐私和跟踪连续性。',
  },
  disclaimer: {
    title: '待处理医学免责声明',
    body: '值得在将模块用作日常参考前确认。',
    confirm: '确认免责声明',
  },
  errorCard: {
    title: '我们无法保存此更改',
  },
  moduleSection: {
    eyebrow: '模块',
    title: '敏感和可选的跟踪',
    subtitle: '如果激活,Vyra 可以根据您的阶段调整训练、营养和恢复的背景。',
    toggleLabel: '模块活跃',
    toggleDescription: '激活或暂停周期读数而不离开设置。',
  },
  cycleData: {
    eyebrow: '基础数据',
    title: '周期摘要',
    subtitle: '主要读数住在这里清晰的行中,编辑在专用屏幕上。',
    lastPeriod: '最后一个时期',
    unconfigured: '未配置',
    cycleDuration: '周期持续时间',
    daysLabel: '天数',
    periodDuration: '月经持续时间',
    nextPeriod: '下一个时期',
    editLink: '编辑周期数据',
    editDescription: '打开模块的基本配置以记录日期、持续时间和背景。',
  },
  errors: {
    saveFailed: '现在无法保存此调整。请在几秒钟后重试。',
    configSaveFailed: '无法保存周期配置。',
  },
} as const;

export const FastingModule = {
  header: {
    title: '间歇性禁食',
  },
  controls: {
    adjustTime: '⏱  调整开始时间',
    cancelAdjust: '✕  取消调整',
    adjustHint: '取消时将使用当前时间',
    adjustSubHint: '如果您已经开始或之后开始',
    adjustTitle: '您开始(或将开始)什么时间?',
    reduceOffset: '减少 15 分钟',
    increaseOffset: '增加 15 分钟',
    offsetHint: '每个触摸移动 15 分钟 · 最多 12 小时或 4 小时前进',
    now: '现在',
  },
  timer: {
    remaining: '剩余',
    elapsedPct: (elapsed: string, pct: number) => `${elapsed} 完成 · ${Math.round(pct)}%`,
    backgroundActive: '计时器继续在后台活跃。',
    endPredictionSameDay: (time: string) => `在 ${time} 结束`,
    endPredictionDiffDay: (time: string, date: string) => `在 ${time} 结束 · ${date}`,
    zones: '代谢区',
  },
  states: {
    activeBadge: '活跃禁食',
    completeBadge: '禁食完成',
    completeEmoji: '🎉',
    completeTitle: '你做到了!',
    completeMeta: (protocol: string, elapsed: string) => `${protocol} · ${elapsed} 完成`,
  },
  suggestion: {
    title: '今天适合这个',
  },
  buttons: {
    startFast: (protocol: string, timeLabel?: string) => 
      timeLabel ? `开始 ${protocol} · ${timeLabel}` : `开始 ${protocol}`,
    completeFast: '完成禁食',
    finishAndClose: '记录并关闭',
    earlyFinish: '提前完成',
    continueEarlyFinish: '继续禁食',
    partialFinish: '部分完成',
  },
  stats: {
    completedLabel: '已完成',
    avgLabel: '平均',
    longestLabel: '最长的',
    completedMeta: (avg: number, longest: number) => `平均 ${avg.toFixed(1)}h · 最好 ${longest.toFixed(1)}h`,
    noFasts: '还没有完成的禁食。',
  },
  history: {
    title: '最近的禁食',
    missed: '错过了',
    pending: '待定',
    completed: '✓',
    deleteBtn: '删除',
    deleteA11y: (protocol: string) => `删除禁食 ${protocol}`,
    emptyEmoji: '🌙',
    emptyTitle: '还没有记录的禁食。',
    emptyHint: '完成您的第一次禁食以在这里查看历史。',
  },
  fiveTwo: {
    header: '📅 今天是您的 5:2 天',
    status: '待定',
    desc: (protocol: string, hours: number, time?: string) => 
      time ? `协议: ${protocol} · 目标: ${hours}h · 计划时间: ${time}` : `协议: ${protocol} · 目标: ${hours}h`,
    button: '今天开始 5:2 禁食',
    week: '本周 · 5:2',
    weekMeta: (completed: number, target: number) => `${completed}/${target} 天完成`,
  },
  modals: {
    zoneDetail: {
      startHint: (hours: number) => `此区域从 ${hours}h 禁食开始。`,
      close: '关闭',
    },
    deleteConfirm: {
      title: '删除禁食',
      body: '删除此禁食?此操作无法撤消。',
      confirm: '删除',
    },
    earlyFinish: {
      title: '提前完成?',
      percentComplete: (pct: number) => `${Math.round(pct)}%`,
      label: '完成',
      context: (elapsed: string) => `您 ${elapsed} 目标。将记录为部分。`,
    },
  },
  contextCard: {
    female: '女性背景',
  },
  offsetLabel: {
    now: (time: string) => `现在 · ${time}`,
    past: (duration: string, time: string, dayLabel?: string) => `${duration} 前${dayLabel ? ` · ${dayLabel}` : ''} · ${time}`,
    future: (duration: string, time: string) => `在 ${duration} · ${time}`,
  },
} as const;

export const WaterModule = {
  header: {
    eyebrow: '设置',
    title: '水',
  },
  dailyGoal: {
    title: '每日目标',
    description: '选择现实的基础,让应用根据背景调整。',
    presets: {
      low: '低活动',
      moderate: '适度',
      recommended: '推荐',
      athlete: '运动员',
      hotClimate: '炎热气候',
    },
    customLabel: '自定义目标',
    customHint: '500 毫升至 10000 毫升之间。',
    unit: '毫升',
  },
  infoCard: {
    eyebrow: '调整',
    body: '如果很热、您在禁食中或该日充满活动,Vyra 可能会提高您的目标。',
  },
  containers: {
    title: '快速对象',
    description: '调整一次您实际容器中的数量。',
    resetLabel: '重置',
    resetA11y: '恢复默认大小',
    glass: '一杯',
    largeGlass: '大杯',
    bottle: '瓶子',
  },
  warningCard: {
    eyebrow: '警告',
    body: '提醒位于常规通知中。从这里您只需调整操作部分。',
  },
  buttons: {
    openNotifications: '打开通知',
    changeUnits: '更改单位',
  },
} as const;
