export const ShellStrings = {
  loadingMessage: '로드 중...',
  errorOccurred: '오류가 발생했습니다.',
  tryAgain: '다시 시도',
  ok: '확인',
  cancel: '취소',
  delete: '삭제',
  confirm: '확인',
  close: '닫기',
  back: '뒤로',
  next: '다음',
  save: '저장',
  search: '검색',
  settings: '설정',
  help: '도움말',
  about: '정보',
  logout: '로그아웃',
  login: '로그인',
  register: '가입',
  profile: '프로필',
  menu: '메뉴',
  notification: '알림',
  edit: '편집',
  add: '추가',
  remove: '제거',
  select: '선택',
  copy: '복사',
  share: '공유',
  download: '다운로드',
  upload: '업로드',
  submit: '제출',
  reset: '재설정',
  apply: '적용',
  filter: '필터',
  sort: '정렬',
  view: '보기',
  hide: '숨기기',
  show: '표시',
  expand: '확장',
  collapse: '축소',
} as const;
