export const ShellStrings = {
  loadingMessage: 'Laden...',
  errorOccurred: 'Er is een fout opgetreden.',
  tryAgain: 'Opnieuw proberen',
  ok: 'OK',
  cancel: 'Annuleren',
  delete: 'Verwijderen',
  confirm: 'Bevestigen',
  close: 'Sluiten',
  back: 'Terug',
  next: 'Volgende',
  save: 'Opslaan',
  search: 'Zoeken',
  settings: 'Instellingen',
  help: 'Help',
  about: 'Over',
  logout: 'Afmelden',
  login: 'Aanmelden',
  register: 'Registreren',
  profile: 'Profiel',
  menu: 'Menu',
  notification: 'Melding',
  edit: 'Bewerken',
  add: 'Toevoegen',
  remove: 'Verwijderen',
  select: 'Selecteren',
  copy: 'Kopiëren',
  share: 'Delen',
  download: 'Downloaden',
  upload: 'Uploaden',
  submit: 'Verzenden',
  reset: 'Opnieuw instellen',
  apply: 'Toepassen',
  filter: 'Filteren',
  sort: 'Sorteren',
  view: 'Weergeven',
  hide: 'Verbergen',
  show: 'Weergeven',
  expand: 'Uitvouwen',
  collapse: 'Samenvouwen',
} as const;
