export { ShellStrings } from './strings.shell.ru';

export const ErrorMessages = {
  noInternet: 'Нет сигнала здесь. Продолжайте регистрировать, и я синхронизирую, когда вернётся соединение.',
  aiUnavailable: 'Слой ИИ сейчас недоступен. Попробуйте ещё раз через пару минут.',
  saveFailed: 'Не удалось сохранить сейчас. Ваши данные в безопасности, я попробую снова.',
  barcodeNotFound: 'Не нашёл этот код. Вы можете найти продукт или ввести вручную.',
  paymentError: 'Не удалось завершить это действие. Изменения не применены.',
  photoAIFailed: 'Не смог правильно распознать это блюдо. Попробуйте другое фото или введите вручную.',
  voiceLogFailed: 'Не смог разобрать голосовую запись. Попробуйте ещё раз или введите вручную.',
  loginFailed: 'Не удалось войти. Проверьте данные и попробуйте снова.',
  registerFailed: 'Не удалось создать учётную запись. Попробуйте ещё раз.',
  sessionExpired: 'Ваша сессия истекла. Войдите снова, чтобы продолжить.',
  premiumRequired: 'Эта функция недоступна в вашем текущем доступе.',
  generic: 'Что-то пошло не так. Попробуйте ещё раз через мгновение.',
  loadFailed: 'Не удалось загрузить данные. Протяните для повторной попытки.',
  syncFailed: 'Не удалось синхронизировать. Ваши данные остаются сохранены локально.',
  permissionDenied: 'Мне нужно ваше разрешение, чтобы продолжить. Вы можете изменить это в Параметрах.',
} as const;

export const AuthStrings = {
  welcome: {
    title: 'Ваш фитнес ясен с сегодня.',
    subtitle: 'Тренировки, еда, вода, сон и прогресс в одном приложении.',
    cta: 'Создать бесплатный аккаунт',
    login: 'Войти в мой аккаунт',
    legal: 'Продолжая, вы принимаете наши условия.',
  },
  login: {
    title: 'С возвращением',
    email: 'Email',
    password: 'Пароль',
    cta: 'Войти',
    forgot: 'Забыл пароль',
    noAccount: 'Нет аккаунта',
    register: 'Создать аккаунт',
  },
  register: {
    title: 'Создать аккаунт',
    name: 'Ваше имя',
    email: 'Email',
    password: 'Пароль (минимум 8 символов)',
    cta: 'Создать мой аккаунт',
    haveAccount: 'У меня уже есть аккаунт',
    login: 'Войти',
    tosLabel: 'Я принимаю',
    tos: 'Условия обслуживания',
    and: 'и',
    privacy: 'Политику конфиденциальности',
    healthConsent: 'Я даю согласие Vyra обрабатывать мои данные здоровья для персонализации моего опыта.',
    medicalDisclaimer:
      'Я понимаю, что Vyra не является медицинским устройством и не заменяет профессиональную оценку.',
  },
  medicalModal: {
    title: 'Перед началом',
    body:
      'Vyra - это приложение для здоровья и фитнеса. Это не сертифицированное медицинское устройство и не заменяет консультацию, диагностику или профессиональное лечение.',
    cta: 'Понял, продолжить',
  },
} as const;

export const OnboardingStrings = {
  step1: {
    title: 'Какова ваша главная цель?',
    subtitle: 'Мы используем это для подготовки согласованного первоначального опыта.',
    goals: {
      lose_fat: 'Потеря жира',
      gain_muscle: 'Набор мышечной массы',
      general_health: 'Общее здоровье',
      sport_performance: 'Спортивное мастерство',
      mental_wellbeing: 'Общее благополучие',
    },
  },
  step2: {
    title: 'Где вы тренируетесь?',
    subtitle: 'Так мы фильтруем тип программы и упражнений.',
    gender: {
      label: 'Биологический пол',
      male: 'Мужской',
      female: 'Женский',
      non_binary: 'Небинарный',
      prefer_not_to_say: 'Предпочитаю не говорить',
    },
    age: 'Возраст',
    height: 'Рост (см)',
    weight: 'Текущий вес (кг)',
    goalWeight: 'Целевой вес (кг, опционально)',
  },
  step3: {
    title: 'В чём ваш основной фокус?',
    subtitle: 'Выберите основной модуль и затем добавьте дополнительно, если хотите.',
    levels: {
      0: 'Очень низкий',
      1: 'Низкий',
      2: 'Средний',
      3: 'Активный',
      4: 'Очень активный',
      5: 'Атлет',
    },
    equipment: {
      label: 'Доступное оборудование',
      gym: 'Полная тренажёрная зала',
      home: 'Дом с базовым оборудованием',
      both: 'Оба',
      outside: 'На открытом воздухе',
      none: 'Без оборудования',
    },
  },
  step4: {
    title: 'Всё готово',
    subtitle: 'Мы подготовили первое действие на сегодня.',
    wakeTime: 'Время пробуждения',
    sleepTime: 'Время сна',
    fasting: {
      label: 'Прерывистое голодание',
      yes: 'Да',
      no: 'Нет',
    },
    protocol: 'Протокол',
  },
  step5: {
    title: 'Полный доступ',
    subtitle: 'Продвинутые функции готовы с первого дня.',
    features: {
      aiCoach: 'Контекстный ИИ',
      photoLog: 'Регистрация по фото',
      voiceLog: 'Голосовая регистрация',
      unlimitedHistory: 'Расширенная история',
      correlations: 'Больше контекста и корреляций',
      noAds: 'Полный доступ с первого дня',
    },
    monthly: 'Полный доступ',
    yearly: 'Всё готово',
    yearlyNote: 'Без разблокировок',
    trialCta: 'Войти в Vyra',
    freeCta: 'Продолжить',
    freeNote: 'Продукт уже открыт и готов к использованию.',
  },
  next: 'Далее',
  back: 'Назад',
  skip: 'Пропустить',
  finish: 'Начать',
  step: 'Шаг',
  of: 'из',
} as const;

export const DashboardStrings = {
  greeting: {
    morning: 'Доброе утро',
    afternoon: 'Добрый день',
    evening: 'Добрый вечер',
  },
  dailyScore: 'Сигнал дня',
  streak: (days: number) => `${days} ${days === 1 ? 'день' : 'дней'} подряд`,
  bestStreak: 'лучшая серия',
  checkIn: 'Регистрация дня',
  checkInDone: 'Регистрация завершена',
  quickActions: 'Быстрые регистрации',
  todayMissions: 'На этой неделе',
  aiInsight: 'Контекст сегодня:',
  noInsight: 'Завершите первую регистрацию, чтобы получить контекст.',
} as const;

export const ModuleNames = {
  water: 'Вода',
  steps: 'Шаги',
  fasting: 'Голодание',
  sleep: 'Сон',
  nutrition: 'Питание',
  weight: 'Вес',
  workout: 'Тренировка',
  mental: 'Благополучие',
  female: 'Женское здоровье',
  supplements: 'Добавки',
  recovery: 'Восстановление',
} as const;

export const ModuleEmojis = {
  water: '💧',
  steps: '🚶',
  fasting: '⏳',
  sleep: '😴',
  nutrition: '🥗',
  weight: '⚖️',
  workout: '🏋️',
  mental: '🧠',
  female: '🌸',
  supplements: '💊',
  recovery: '🛌',
} as const;

export const Disclaimers = {
  context: 'Контекстный ИИ Vyra предоставляет общее руководство и не заменяет профессиональную помощь.',
  supplements:
    'Vyra не рекомендует дозировки или комбинации добавок. Проконсультируйтесь со специалистом здравоохранения.',
  bmi: 'ИМТ и процент жира - это оценки. Они не являются медицинским диагнозом.',
  cycle: 'Прогноз цикла является приблизительным. Не должен использоваться как противозачаточное средство.',
  fasting24h:
    'Длительное голодание подходит не всем. Если у вас есть вопросы, проконсультируйтесь со специалистом.',
  deficitHigh:
    'Агрессивный дефицит калорий может быть вредным в долгосрочной перспективе. Проконсультируйтесь с диетологом.',
} as const;

export const NotificationStrings = {
  waterReminder: (ml: number, goal: number) => `Вы выпили ${ml} мл из ${goal} мл. Добавим стакан воды?`,
  stepsReminder: (steps: number, goal: number) =>
    `Вы прошли ${steps.toLocaleString()} из ${goal.toLocaleString()} шагов.`,
  streakDanger: (days: number) =>
    `Ваша серия из ${days} дней под угрозой. Одно небольшое действие сегодня её спасёт.`,
  fastingPhase: (phase: string) => `Вы вошли в ${phase}. Ваше голодание идёт хорошо.`,
  goalReached: (goal: string) => `Цель ${goal} достигнута.`,
  prAchieved: (exercise: string, weight: number) => `Новый рекорд: ${weight} кг в ${exercise}.`,
} as const;

export const General = {
  save: 'Сохранить',
  cancel: 'Отмена',
  confirm: 'Подтвердить',
  delete: 'Удалить',
  edit: 'Редактировать',
  close: 'Закрыть',
  back: 'Назад',
  continue: 'Продолжить',
  retry: 'Повторить',
  loading: 'Загрузка...',
  syncing: 'Синхронизация...',
  today: 'Сегодня',
  yesterday: 'Вчера',
  week: 'Неделя',
  month: 'Месяц',
  all: 'Всё',
  free: 'Бесплатно',
  premium: 'Включено',
  upgrade: 'Посмотреть доступ',
  history: 'История',
  settings: 'Параметры',
  profile: 'Профиль',
  logout: 'Выход',
  or: 'или',
  and: 'и',
  of: 'из',
  for: 'для',
  done: 'Готово',
  add: 'Добавить',
  remove: 'Удалить',
  search: 'Поиск',
  noResults: 'Нет результатов',
  empty: 'Здесь ещё ничего нет.',
  offline: 'Отключено',
  online: 'Онлайн',
} as const;

export const ValidationMessages = {
  emailInvalid: 'Email имеет неверный формат.',
  passwordRequired: 'Пароль обязателен.',
  passwordTooShort: 'Пароль должен содержать не менее 8 символов.',
  ageTooYoung: 'Вам должно быть не менее 13 лет для использования Vyra.',
  ageInvalid: 'Введённый возраст неверный.',
  weightTooLow: 'Минимальный вес 20 кг.',
  weightInvalid: 'Введённый вес неверный.',
  heightTooLow: 'Минимальный рост 50 см.',
  heightInvalid: 'Введённый рост неверный.',
  waterAmountTooHigh: 'Максимальное количество 5000 мл за одну регистрацию.',
  waterGoalTooLow: 'Минимальная цель 500 мл.',
  waterGoalTooHigh: 'Максимальная цель 10000 мл.',
  stepsGoalTooLow: 'Минимальная цель 1000 шагов.',
  stepsGoalTooHigh: 'Максимальная цель 100000 шагов.',
  foodAmountTooHigh: 'Максимальное количество 5000 г.',
  barcodeScanEmpty: 'Отсканированный код пуст.',
  barcodeTypeUnrecognized: 'Не удалось распознать тип кода.',
  barcodeProcessError: 'Ошибка при обработке кода.',
  emailAlreadyExists: 'Этот email уже зарегистрирован. Вы можете войти с этого аккаунта.',
  networkError: 'Не удалось подключиться к Vyra. Проверьте подключение и попробуйте ещё раз.',
  tempSessionError: 'Не удалось открыть временную сессию. Попробуйте ещё раз.',
  emailSendError: 'Не удалось отправить email. Проверьте адрес.',
  accountDeleteSuccess: 'Ваш запрос обработан и мы завершили сессию. Окончательное удаление следует действующей политике.',
} as const;

export const FastingLabels = {
  activePhase: 'Активное голодание',
  autophagy: 'Аутофагия',
  deepFast: 'Глубокое голодание',
  extendedFast: 'Продлённое голодание',
  gentleEntry: 'Мягкий вход для дней низкого восстановления',
  omad: 'OMAD — один приём пищи в день',
  omadAlt: 'Один приём пищи в день (OMAD)',
  fastDay: 'День ограничения (протокол 5:2)',
  hungryPhaseWarning: 'На этом этапе обычно повышается голод и усталость. Более короткий протокол будет лучше на этой неделе.',
  consistencyTip: 'Ваш паттерн предполагает, что чуть более гибкое окно может улучшить еженедельную последовательность.',
  progressTip: 'Вы повторно недостаёте. Средний протокол может закрепить привычку.',
  readyProgress: 'Вы выполнили несколько 16:8 с запасом. Вы готовы к переходу на 18:6.',
  autophagyCountdown: 'Осталось 45 мин до аутофагии. Вы уже зашли так далеко, потерпите немного дольше.',
  fastingCancelled: 'Голодание отменено. Следующее будет лучше!',
  fast52Started: 'Голодание 5:2 начато по вашему расписанию.',
  stayConsistent: 'На этом этапе стоит удержать стабильный протокол, чем гнаться за дополнительными часами. 16:8 - хорошая база на сегодня.',
  focusConsistency: 'Держите текущий протокол сегодня. Сосредоточьтесь на последовательности и умном разрыве голодания.',
  menstrualGuidance: 'Менструальная фаза: используйте 12:12 или 14:10, если тело просит снизить нагрузку. Восстановление в приоритете.',
  lutealGuidance: 'Лютеиновая фаза: обычно лучше работают 14:10 или 16:8 с более простым разрывом голодания.',
  ovulatoryGuidance: 'Овуляторная фаза: обычно хорошо переносит стандартные протоколы, если вы хорошо спите.',
  cancelled: 'Голодание отменено',
  // Phase descriptions
  fedPhase: 'После еды',
  fedPhaseDesc: 'Переваривание. Инсулин повышен.',
  activePhaseDesc: 'Гликоген начинает потребляться.',
  ketosisPhase: 'Начальный кетоз',
  ketosisPhaseDesc: 'Тело начинает сжигать жир.',
  autophagyDesc: 'Активная клеточная переработка. Максимальные выгоды.',
  deepFastDesc: 'Увеличение ГРЧ. Интенсивная клеточная регенерация.',
  extendedFastDesc: 'Режим выживания. Максимальное клеточное выживание.',
  // Protocol descriptions
  protocol12_12Desc: 'Мягкий вход для дней низкого восстановления',
  protocol14_10Desc: 'Средний этап для удержания приверженности',
  protocol16_8Desc: '16ч голодание, 8ч для еды — наиболее популярный',
  protocol18_6Desc: '18ч голодание, 6ч окно',
  protocol20_4Desc: 'Warrior Diet',
  protocol23_1Desc: 'OMAD — один приём пищи в день',
  protocolOMADDesc: 'Один приём пищи в день (OMAD)',
  protocol24hDesc: 'Полное 24-часовое голодание.',
  protocol5_2Desc: 'День ограничения (протокол 5:2)',
  protocolCustomDesc: 'Пользовательский',
} as const;

export const FemaleHealthLabels = {
  menstrual: 'Менструальная',
  follicular: 'Фолликулярная',
  ovulation: 'Овуляция',
  luteal: 'Лютеиновая',
  weightVariations: 'Колебания веса могут быть временными в зависимости от фазы.',
  hydrationMenstrual: 'Дополнительная гидратация во время менструации.',
  fastingMenstrual: 'Мягкий протокол (12:12 или 14:10).',
  sleepMenstrual: 'Приоритет восстанавливающему сну.',
  trainingRecovery: 'Активное восстановление, мобильность или лёгкая сила.',
  fastingFollicular: 'Большая переносимость стандартных протоколов (16:8).',
  nutritionFollicular: 'Увеличьте белок и цинк для производительности и восстановления.',
  trainingOvulation: 'Окно высокой энергии: высокая сила/интенсивность.',
  fastingOvulation: 'Можно поддерживать 16:8 или 18:6, если хорошее восстановление.',
  fastingLuteal: 'На лютеиновой фазе может быть сложнее; сократите протокол, если появляется высокий голод.',
  nutritionLuteal: 'Увеличьте магний и сложные углеводы для стабильной энергии.',
  nextOvulationNotice: 'Завтра вы входите в овуляторное окно: готовим тренировку высокой интенсивности.',
  menstruationNotice: 'Ваша менструация начинается вскоре. На этой неделе приоритет дополнительная гидратация и восстановление.',
  cycleVariation: 'Ваш цикл варьируется более чем на 7 дней между периодами. Стоит обсудить с гинекологом для оценки.',
  needSupport: 'Вам нужна поддержка',
  // Phase guidance (menstrual)
  menstrualTraining: 'Активное восстановление, мобильность или лёгкая сила.',
  menstrualFasting: 'Приоритет короткие протоколы (12-14ч) или перерыв от голодания.',
  menstrualNutrition: 'Усильте железо, омега-3 и противовоспалительные продукты.',
  menstrualWeightContext: 'На менструальной/лютеиновой фазе могут быть колебания 1-3 кг из-за жидкости.',
  // Phase guidance (follicular)
  follicularTraining: 'Хорошая фаза для увеличения нагрузки и объёма.',
  follicularFasting: 'Большая переносимость стандартных протоколов (16:8).',
  follicularNutrition: 'Увеличьте белок и цинк для производительности и восстановления.',
  // Phase guidance (ovulation)
  ovulationTraining: 'Окно высокой энергии: высокая сила/интенсивность.',
  ovulationFasting: 'Можно поддерживать 16:8 или 18:6, если хорошее восстановление.',
  ovulationNutrition: 'Приоритет антиоксидантам и качественным углеводам.',
  // Phase guidance (luteal)
  lutealTraining: 'Поддерживайте последовательность с умеренной интенсивностью.',
  lutealFasting: 'На лютеиновой фазе может быть сложнее; сократите протокол, если появляется высокий голод.',
  lutealNutrition: 'Увеличьте магний и сложные углеводы для стабильной энергии.',
  lutealWeightContext: 'На лютеиновой фазе нормально задерживать жидкость и видеть временные увеличения.',
} as const;

export const WorkoutLabels = {
  freesession: 'Свободная сессия',
  base: 'Основа',
  building: 'Строительство',
  consolidation: 'Консолидация',
  muscleGroupsFatigued: 'Есть ${tired} групп мышц с недавней высокой нагрузкой.',
  lowerIntensity: 'Стоит снизить интенсивность или выбрать техническую сессию, чтобы продолжить не ломая блок.',
  controlledSession: 'Есть запас для тренировки, но с контролируемой сессией вы будете работать эффективнее.',
  recordSet: 'Новый рекорд в ${exercise}: ${weight} кг',
} as const;

export const TabBarCopy = {
  quickLogHint: 'Откройте панель для регистрации воды, веса, голодания или сна.',
} as const;

export const BmiCategories = {
  underweight: 'Недостаточный вес',
  normal: 'Нормальный вес',
  overweight: 'Избыточный вес',
  obesity: 'Ожирение',
} as const;

export const ComponentMessages = {
  balanceCardNoData: 'VYRA Баланс сегодня, недостаточно данных',
  balanceNoData: 'Недостаточно данных.',
  lastWeight: 'последний вес',
  noSession: 'нет сессии',
  seriesCount: 'подходов сегодня',
  isotonic: 'Изотоническая',
  tea: 'Чай',
  coffee: 'Кофе',
  workoutLogged: 'Сессия записана',
  syncSlowWarning: 'Начальная загрузка заняла слишком много времени. Мы открыли используемую сессию и вы можете повторить синхронизацию без закрытия приложения.',
  syncSlowWarning2: 'Начальная загрузка заняла больше ожидаемого. Вы можете безопасно войти и повторить синхронизацию из приложения.',
  autoSessionRecovery: 'Не удалось автоматически восстановить вашу сессию. Вы можете повторить без закрытия приложения.',
  retrySyncPartial: 'Повторить частичную синхронизацию',
  retrySync: 'Повторить',
  maintenanceMessage: 'Если вы использовали воду, сон, вес, питание или тренировку, локальные данные остаются. Осталось только системе вернуться и завершить остальное выравнивание.',
  authCallbackError: 'Провайдер не вернул действительные данные сессии.',
  invalidSession: 'Нет активной сессии.',
  dailyLimitReached: 'Достигнут суточный лимит',
  aiBrainResting: 'Мой ИИ мозг отдыхает.',
  systemPrompt: 'Ответьте на русском, кратко, практично и безопасно.',
} as const;

export const MentalLabels = {
  needSupport: 'Вам нужна поддержка',
  emotionalTrend: 'Мы обнаружили нисходящий эмоциональный тренд. Сегодня приоритизируйте восстановление и одно небольшое действие.',
} as const;

export const ReadinessLabels = {
  noConnection: 'Без соединения сейчас. Показываем ваше последнее доступное состояние.',
  exceptional: 'Исключительный день',
  veryGood: 'Очень хороший день',
} as const;

export const ReferralMessages = {
  noValidSession: 'Вам нужна действительная сессия для открытия ваших приглашений.',
  serviceUnavailable: 'Сервис приглашений сейчас недоступен. Повторите попытку позже.',
  notConfigured: 'Бэкенд приглашений не настроен в этой сборке.',
  loadFailed: 'Не удалось загрузить ваши приглашения.',
  noData: 'Приглашения ответили без полезных данных. Повторите попытку через несколько секунд.',
  networkFailed: 'Не удалось подключиться к сервису приглашений.',
  notAvailable: 'Приглашения недоступны в этой сборке.',
  redeemFailed: 'Не удалось обменять.',
} as const;

export const NotificationMessages = {
  routineReady: 'Ваша рутина сегодня готова',
  movementBlockReady: 'Ваш блок движения готов',
  movementBlockCta: 'Откройте Vyra и завершите короткий блок сегодня. Удержать ритм важнее, чем сделать идеально.',
  routineStillOpen: 'Ваша рутина ещё открыта',
  routineStillOpenDesc: 'Вам осталось ${name}. Вы можете вернуться или отметить быстро из уведомления.',
  recommendedRoutineReady: 'Ваша рутина сегодня готова',
  recommendedRoutineDesc: '${name} подходит хорошо сегодня. Вы открываете или отмечаете без потери времени.',
  hydrationReminder: '💧 Время гидратироваться',
  hydrationReminderDesc: '${name}, сегодня вы ещё можете приблизиться к своей цели.',
  streakAtRisk: '🔥 Ваша серия под угрозой',
  streakAtRiskDesc: '${name}, сделайте 1 быструю регистрацию сегодня и сохраните её.',
  hydrationSmartReminder: '💧 Умное напоминание',
  streakSmartReminder: '🔥 Серия под угрозой',
} as const;

export const PrivacyTexts = {
  dataExample: 'Вода, шаги, сон, вес, еда, голодание, тренировки и ежедневные резюме.',
  healthDataReduction: 'Сократите, сколько открыто хранится о весе, психическом здоровье и женском здоровье.',
} as const;

export const ExplorePageStrings = {
  title: 'План',
  heroEyebrow: 'Активная цель',
  heroBody: 'План больше не работает как вторая home: отсюда вы должны видеть свой путь, свой блок и следующий полезный шаг.',
  loseFat: 'Потеря жира',
  gainMuscle: 'Набор мышц',
  performance: 'Производительность',
  organizeHabits: 'Организация привычек',
  recovery: 'Восстановление',
  yourCurrentPath: 'Ваш текущий путь',
  fallbackCoaching: 'Удержать один хорошо выбранный решение на этой неделе сдвигает стрелку больше, чем открыть десять путей одновременно.',
  recommended: 'Рекомендовано для вас',
  coaching: 'Контекстный коучинг',
  weeklyPriority: 'Приоритет этой недели',
  momentum: 'Вызовы и импульс',
  streakLabel: 'серия',
  sessionThisWeek: 'сессий неделя',
  usefulLibrary: 'Полезная библиотека',
  // Program section
  programTitle: 'Активная программа',
  noneSelected: 'Ещё не выбрана программа',
  activeWeek: 'Неделя {{week}}. Блок уже работает и следующее решение должно выйти отсюда.',
  suggested: 'Нет активной программы, но уже есть предложенная рутина для начала с направлением.',
  chooseRoute: 'Лучше сейчас выбрать направленный маршрут вместо навигации по полному каталогу.',
  nextAction: 'Следующее действие',
  backToSession: 'Вернуться к сессии',
  chooseProgram: 'Выбрать программу',
  progress: 'Прогресс',
  thisWeek: '{{sessions}}/{{goal}} на этой неделе',
  continueProgram: 'Продолжить программу',
  // Cards
  nextFocusEyebrow: 'Следующая корректировка',
  nextFocusBody: 'Контекстное чтение сегодня уже нашло, что больше всего стоит толкать в первую очередь.',
  workoutEyebrow: 'Тренировка',
  openCurrent: 'Открыть ваш текущий блок',
  chooseGuided: 'Выбрать направленную программу',
  workoutOpenBody: 'Проверьте недели, дни и преемственность нагрузки, не выходя из главного пути.',
  workoutChooseBody: 'Начните с ясного маршрута вместо навигации отдельных рутин без приоритета.',
  nutritionEyebrow: 'Питание',
  nutritionTitle: 'Простой питательный сброс',
  nutritionBody: 'Один хорошо записанный день стоит больше, чем сложная таблица, которую вы не используете.',
  recoveryEyebrow: 'Восстановление',
  sleepTitle: 'Лучше спать на этой неделе',
  sleepBody: 'Отрегулируйте отдых перед тем, как попросить больше силы и последовательности в день.',
  waterTitle: 'Рутина гидратации',
  waterBody: 'Простая база воды и ежедневный ритм делают остальную систему работающей лучше.',
  libraryEyebrow: 'Полезная библиотека',
  plannerTitle: 'Еженедельный план',
  plannerBody: 'Визуализируйте неделю и подготовьте следующий блок без открытия дополнительных модулей.',
  mealTitle: 'Записать приём пищи',
  mealBody: 'Вернитесь к основам и сделайте день яснее за два шага.',
  sleepLibraryTitle: 'Посмотреть отдых',
  sleepLibraryBody: 'Прочитайте прошлую ночь и уменьшите или увеличьте нагрузку с большей уверенностью.',
  progressTitle: 'Прочитать реальный прогресс',
  progressBody: 'Если вы хотите более глубокий контекст, здесь вы видите тренд, а не только отдельные записи.',
  milestoneDone: 'Неделя направлена. Теперь пора удержать качество блока и не добавлять шум.',
  milestonePending: 'Вам нужно {{count}} сессий, чтобы закрыть вашу еженедельную цель.',
} as const;

export const HomePageStrings = {
  locale: 'ru-RU',
  guestName: 'Пользователь',
  quickActionHint: 'Откройте этот быстрый ярлык.',
  secondaryModuleHint: 'Откройте этот вторичный модуль.',
  notificationFallbackTitle: 'Уведомление Vyra',
  notificationFallbackBody: 'Доступна недавняя активность.',
  greeting: 'Привет, {{name}}',
  streakPillLabel: (days: number) => `Текущая серия: ${days} ${days === 1 ? 'день' : 'дней'}`,
  streakPillHint: 'Откройте прогресс, чтобы увидеть вашу последовательность.',
  openNotifications: 'Открыть недавние уведомления',
  openNotificationsHint: 'Показывает элементы управления доставкой и последние предупреждения.',
  openQuickLog: 'Открыть быструю регистрацию',
  openQuickLogHint: 'Откройте лист для регистрации воды, сна, веса или голодания без выхода с начала.',
  openProfile: 'Открыть профиль',
  openProfileHint: 'Откройте вашу учётную запись, модули и настройки.',
  activeWorkoutAccessibility: 'Активная сессия, {{name}}, {{count}} упражнений в процессе',
  activeWorkoutEyebrow: 'Активная сессия',
  activeWorkoutFallbackTitle: 'Тренировка в процессе',
  activeWorkoutMeta: '{{count}} упражнений в процессе на этом устройстве.',
  activeWorkoutCta: 'Вернуться к тренировке',
  nextStepEyebrow: 'Следующий шаг',
  nextStepHint: 'Выберите фронт, который больше всего движет ваш день, и решите его отсюда.',
  planEyebrow: 'Сегодня',
  planTitle: 'План дня',
  planSummary: '{{done}} из {{total}} фронтов уже покрыты.',
  planExpand: 'Посмотреть полный план',
  planCollapse: 'Показать меньше',
  momentumEyebrow: 'Последовательность',
  streakEyebrow: 'Серия',
  streakStartToday: 'Начните вашу серию сегодня',
  streakRunning: (days: number) => `${days} ${days === 1 ? 'день' : 'дней'} подряд`,
  streakDoneBody: 'Сегодня уже считается. Удержать небольшое действие поддерживает вашу непрерывность.',
  streakPendingBody: 'Вам достаточно воды, шагов, питания или тренировки, чтобы спасти день.',
  streakView: 'Посмотреть серию и прогресс',
  streakSave: 'Спасить мою серию сейчас',
  sectionsQuickActions: 'Быстрые действия',
  sectionsThisWeek: 'На этой неделе',
  weekDone: '{{day}}: день завершён на этой неделе',
  weekTodayPending: '{{day}}: сегодня ещё ожидается',
  weekPending: '{{day}}: не завершено',
  weekSummary: '{{count}} из 7 дней на этой неделе',
  pauseBody: 'Вы не регистрируетесь {{days}} дней. Возобновите сегодня с чего-нибудь маленького.',
  pauseCta: 'Возобновить сейчас',
  pauseHint: 'Откройте предложенное действие, чтобы вернуться к регистрации активности.',
  aiEyebrow: 'VYRA предполагает',
  notificationsTitle: 'Последние уведомления',
  notificationsEmpty: 'Здесь ещё нет недавней активности для показа.',
  notificationsViewAll: 'Показать всё',
  notificationsAccessibility: 'Посмотреть все уведомления',
  notificationsHint: 'Откройте элементы управления доставкой уведомлений и часы безмолвия.',
} as const;

export const ProgressPageStrings = {
  sectionEnergy: 'Энергия и вес',
  sectionEnergyHint: 'Что важно, меняется в зависимости от выбранной вами цели.',
  workoutSessions: 'сессии',
  sleepRecovered: 'Solid база для поддержания нормальной нагрузки сегодня.',
  sleepRecovering: 'Вы спали меньше, чем идеально. Стоит модулировать интенсивность.',
  muscleChest: 'Грудь',
  muscleBack: 'Спина',
  muscleShoulders: 'Плечи',
  muscleArms: 'Руки',
  muscleCore: 'Ядро',
  muscleLegs: 'Ноги',
  caloriesEyebrow: 'Калории сегодня',
  weightEyebrow: 'Вес и направление',
  viewPrograms: 'Посмотреть программы',
  backHome: 'Вернуться домой',
} as const;

export const WaterHydrationMessages = {
  goalReached: 'Цель закрыта. Удержать этот простой паттерн - это то, что поддерживает модуль.',
  behindAndAfternoon: 'Большая часть дня уже прошла. Два последовательных регистрации прямо сейчас полностью меняют закрытие.',
  lowProgress: 'Ещё есть запас для восстановления ритма без добавления сложности.',
  onTrack: 'Вы идёте хорошо. Удержать маленькие стаканы с расстояниями стоит больше, чем складывать всё в конце.',
} as const;

export const StepsProgressMessages = {
  goalMet: 'Вы превзошли или достигли вашей цели. {{totalSteps}} шагов сегодня.',
  almostThere: 'Почти. Вам нужно {{remaining}} шагов до цели.',
  goodProgress: 'Вы идёте хорошо. Вы уже набрали ритм, чтобы закончить день лучше.',
  justStarted: 'Хорошее начало. Продолжайте складывать.',
} as const;

export const HomeDetailStrings = {
  hero: {
    readiness: {
      eyebrow: 'Готовность',
      pending: 'База сегодня',
      awaiting: 'Чтение в процессе',
      support: 'Со сном, водой, едой и движением этот score становится более точным.',
      noData: 'Мы ещё строим ваше ежедневное чтение. Каждая полезная регистрация даёт ему больше контекста.',
      weeklyAverage: 'Среднее',
      projected: 'Возможное закрытие',
      stability: 'Стабильность',
      focus: 'Фокус сейчас',
      cta: 'Посмотреть подробности',
    },
    fasting: {
      eyebrow: 'Активное голодание',
      protocol: 'Протокол {{protocol}}',
      eatingWindowOpen: 'Окно еды открыто',
      accumulated: '{{hours}}ч {{minutes}}м накоплено.',
      close: 'Закрыть голодание',
      complete: 'Завершить голодание',
    },
    female: {
      eyebrow: 'Цикл',
      phaseDay: 'Фаза {{phase}} · День {{day}}',
      prioritizeRecovery: 'Приоритезируйте восстановление и регулярность',
      trainStrong: 'Хороший день для интенсивной тренировки',
      registerToday: 'Зарегистрировать сегодня',
    },
    nutrition: {
      eyebrow: 'Питание',
      percentCalories: '{{pct}}% калорий сегодня',
      caloriesOf: '{{current}} из {{target}} ккал',
      cta: 'Зарегистрировать приём пищи',
    },
    steps: {
      eyebrow: 'Шаги',
      title: 'Цель сегодня',
      ofSteps: 'из {{goal}} шагов',
      estimatedCalories: '{{kcal}} ккал предполагаемых.',
      cta: 'Посмотреть подробности',
    },
    sleep: {
      eyebrow: 'Сон',
      recovered: 'Solid база для поддержания нормальной нагрузки сегодня.',
      recovering: 'Вы спали меньше, чем идеально. Стоит модулировать интенсивность.',
      view: 'Посмотреть сон',
      log: 'Зарегистрировать сон',
    },
    workoutRest: {
      eyebrow: 'Сегодня · отдых',
      fallbackTitle: 'Активное восстановление',
      body: 'Сегодня стоит снизить нагрузку. Вы можете проверить следующую сессию блока без спешки.',
      cta: 'Посмотреть завтра',
    },
    workout: {
      eyebrow: 'Сегодня',
      activeFallback: 'Сессия в процессе',
      idleFallback: 'Тренируйтесь сегодня',
      prYesterday: 'ПР вчера',
      activeMeta: '{{count}} упражнений · сессия открыта',
      routineMeta: '{{count}} упражнений · ~{{minutes}} мин',
      emptyMeta: 'Ещё нет готовой рутины на сегодня.',
      resume: 'Вернуться к тренировке',
      trainNow: 'Тренируйтесь сейчас',
    },
  },
  workoutProgram: {
    week: 'Неделя {{week}} · {{day}}',
    progress: '{{pct}}% блока',
    todayRoutine: '{{day}} · рутина дня',
    nextSuggestion: '{{day}} · следующее предложение',
    active: 'Активная сессия',
    exercises: '{{count}} упражнений',
  },
  metrics: {
    waterGoal: '{{pct}}% цели',
    sleepBelowGoal: 'Ниже цели',
    steps: '{{pct}}% · {{kcal}} ккал',
    noTrend: 'Тренд ещё короткий',
    weeklyTrend: '{{sign}}{{value}} на этой неделе',
  },
  quickActions: {
    logMeal: 'Зарегистрировать приём пищи',
    addWater: 'Добавить воду',
    resumeWorkout: 'Вернуться к тренировке',
    trainNow: 'Тренируйтесь сейчас',
    logSleep: 'Зарегистрировать сон',
    openQuickLog: 'Открыть быструю регистрацию',
  },
} as const;

export const ForgotPasswordStrings = {
  title: 'Восстановите доступ',
  subtitle: 'Введите свой email и мы отправим инструкции.',
  send: 'Отправить инструкции',
  sendFailed: 'Не удалось отправить email. Проверьте адрес и попробуйте ещё раз.',
  successTitle: 'Проверьте ваш входящий ящик',
  successBody: 'Также проверьте папку спама, если не видите.',
  resend: 'Переотправить',
  resendIn: (seconds: number) => `Переотправить через ${seconds}с`,
  resendA11y: (seconds: number) =>
    seconds > 0 ? `Переотправить через ${seconds} секунд` : 'Переотправить email',
  resendHint: 'Переотправьте письмо восстановления.',
} as const;

export const FastingMetabolicZones = {
  fed: {
    label: 'Сытый',
    description: 'Переваривание и энергия всё ещё рядом с последним приёмом пищи.',
  },
  early: {
    label: 'Адаптация',
    description: 'Энергия начинает снижаться и тело меняет источник.',
  },
  fat: {
    label: 'Сжигание жира',
    description: 'Становится легче использовать жир как основное топливо.',
  },
  ketosis: {
    label: 'Кетоз',
    description: 'Сигнал кетоза уже появляется довольно ясно.',
  },
  autophagy: {
    label: 'Аутофагия',
    description: 'Продвинутое окно. Здесь важнее контекст и восстановление.',
  },
} as const;

export const BiometricLabels = {
  promptMessage: 'Разблокировать Vyra',
  cancelLabel: 'Отмена',
  fallbackLabel: 'Использовать блокировку устройства',
  unlockButton: 'Разблокировать',
  verifyingButton: 'Проверка...',
  logoutHint: 'Закройте текущую сессию без разблокировки приложения.',
  accessibilityLabel: 'Разблокировать Vyra',
} as const;

export const FemaleSymptoms = {
  colicos: 'Колики',
  hinchazon: 'Вздутие',
  fatiga: 'Усталость',
  migrana: 'Мигрень',
  cambios_humor: 'Перепады настроения',
  energia_alta: 'Высокая энергия',
} as const;

export const NutritionModule = {
  headerEditPrefix: 'Редактировать',
  headerAddPrefix: 'Добавить в',
  editingMode: {
    title: 'Редактирование регистрации',
    description: 'Отрегулируйте название, граммы или макросы и сохраните изменение без удаления исходной регистрации.',
  },
  logModes: {
    search: 'Поиск',
    photo: 'Фото',
    barcode: 'Код',
    manual: 'Вручную',
  },
  library: {
    title: 'Быстрая библиотека',
    description: 'Откройте часто используемое или восстановите недавнюю регистрацию перед поиском.',
    tabs: {
      frequent: 'Частые',
      recent: 'Недавние',
    },
    itemA11y: (food: string) => `Использовать ${food}`,
    itemHint: 'Загрузите этот продукт, чтобы подтвердить количество и макросы.',
    emptyFrequent: 'Ваши любимые продукты появятся здесь.',
    emptyRecent: 'Ваши недавние приёмы пищи появятся здесь.',
  },
  search: {
    label: 'Поиск продукта',
    placeholder: 'Пр: рис, йогурт, курица...',
    searching: 'Поиск продуктов...',
    libraryMatches: 'Уже в вашей библиотеке',
    libraryDescription: 'Перед открытием длинного списка мы сначала показываем совпадения, которые вы уже использовали.',
    recentLabel: (timestamp: string) => `${timestamp}`,
    generalResults: 'Общие результаты',
    resultsCount: (count: number) => {
      if (count >= 30) return `Показано первые ${count} результатов. Если вы не нашли искомое, откройте больше результатов или используйте ручную загрузку.`;
      return `Мы нашли ${count} совпадение${count === 1 ? '' : 'й'} для этого поиска.`;
    },
    noResults: (query: string) => `Не нашёл продукты для "${query}". Вы можете попробовать снова или загрузить вручную.`,
    noResultsLibrary: (query: string) => `Не нашёл общие результаты для "${query}". Если вы это использовали раньше, у вас есть совпадения выше или вы можете загрузить вручную.`,
    loadManual: 'Загрузить вручную',
    moreResults: 'Посмотреть больше результатов',
  },
  preview: {
    title: 'Подтверждение',
    hint: 'Подтвердите макросы и количество перед добавлением.',
    macros: {
      kcal: 'Ккал',
      protein: 'Белок',
      carbs: 'Углеводы',
      fat: 'Жир',
      fiber: 'Клетчатка',
    },
    quantityLabel: 'Количество',
    portionHint: '1 порция оценивается как 100 г для этого подтверждения.',
    addButton: (meal: string) => `Добавить в ${meal}`,
  },
  photo: {
    title: 'ИИ фото',
    description: 'Сделайте фото, проверьте, что обнаружил VYRA, и отрегулируйте порции перед подтверждением.',
    takePhoto: 'Сделать фото',
    chooseGallery: 'Выбрать из галереи',
    detection: 'Это обнаружил ИИ',
    confidence: (percent: number) => `уверенность ${Math.round(percent * 100)}%`,
    lowConfidence: 'Обнаружение имеет низкую уверенность. Стоит проверить или перейти на ручной поиск.',
    itemsSelected: (count: number) => `${count} элемент${count > 1 ? 'ов' : ''} отмечено${count > 1 ? '' : 'о'}.`,
    selectAtLeast: 'Отметьте минимум один элемент для подтверждения.',
    confirmDetection: 'Подтвердить обнаружение',
    manualSearch: 'Поиск вручную',
    togglePortions: {
      show: 'Отрегулировать порции',
      hide: 'Скрыть регулировку порций',
    },
    estimated: (grams: number) => `${Math.round(grams)} г предполагаемых`,
    noQuantity: 'Без предполагаемого количества',
    componentIncludeA11y: (name: string) => `Включить ${name}`,
    cameraMissingPermission: 'Требуется разрешение камеры.',
    galleryMissingPermission: 'Требуется разрешение галереи.',
  },
  manual: {
    title: 'Ручная загрузка',
    nameLabel: 'Название',
    namePlaceholder: 'Пр: рис с курицей',
    quantityLabel: 'Количество',
    quantityUnit: 'г',
    proteinLabel: 'Белок',
    proteinUnit: 'г',
    carbsLabel: 'Углеводы',
    carbsUnit: 'г',
    fatLabel: 'Жиры',
    fatUnit: 'г',
    fiberLabel: 'Клетчатка',
    fiberUnit: 'г',
    submitEdit: 'Сохранить изменения',
    submitAdd: (meal: string) => `Добавить в ${meal}`,
  },
  errors: {
    loadingFood: 'Загрузка продукта...',
  },
  modeA11y: (mode: string) => `Режим ${mode === 'search' ? 'поиск' : mode === 'photo' ? 'фото' : mode === 'barcode' ? 'код' : 'ручной'}`,
  unitA11y: (unit: string) => `Единица ${unit}`,
  quickAmountA11y: (value: number) => `Быстрое количество ${value} грамм`,
  portionAdjustmentNote: 'Мы отрегулировали порции в соответствии с элементами, которые вы отметили перед подтверждением.',
} as const;

export const FemaleModule = {
  header: {
    title: 'Регулировки цикла',
    subtitle: 'Модуль, приватность и преемственность отслеживания.',
  },
  disclaimer: {
    title: 'Медицинское предупреждение в ожидании',
    body: 'Стоит подтвердить перед использованием модуля как ежедневную справку.',
    confirm: 'Подтвердить предупреждение',
  },
  errorCard: {
    title: 'Не удалось сохранить это изменение',
  },
  moduleSection: {
    eyebrow: 'Модуль',
    title: 'Чувствительное и опциональное отслеживание',
    subtitle: 'Если вы активируете, VYRA может отрегулировать контекст тренировки, питания и восстановления в соответствии с вашей фазой.',
    toggleLabel: 'Модуль активен',
    toggleDescription: 'Активируйте или приостановите чтение цикла без выхода из ваших настроек.',
  },
  cycleData: {
    eyebrow: 'Базовые данные',
    title: 'Резюме цикла',
    subtitle: 'Основное чтение живёт здесь в ясных строках и редактирование живёт на выделенном экране.',
    lastPeriod: 'Последний период',
    unconfigured: 'Не настроено',
    cycleDuration: 'Продолжительность цикла',
    daysLabel: 'дней',
    periodDuration: 'Продолжительность менструации',
    nextPeriod: 'Следующий период',
    editLink: 'Редактировать данные цикла',
    editDescription: 'Откройте базовую конфигурацию модуля для регистрации дат, продолжительности и контекста.',
  },
  errors: {
    saveFailed: 'Не удалось сохранить эту настройку сейчас. Попробуйте снова через несколько секунд.',
    configSaveFailed: 'Не удалось сохранить конфигурацию цикла.',
  },
} as const;

export const FastingModule = {
  header: {
    title: 'Прерывистое голодание',
  },
  controls: {
    adjustTime: '⏱  Отрегулировать время начала',
    cancelAdjust: '✕  Отменить регулировку',
    adjustHint: 'При отмене будет использовано текущее время',
    adjustSubHint: 'Если вы уже начали раньше или начнёте позже',
    adjustTitle: 'В какое время вы начали (или начнёте)?',
    reduceOffset: 'Уменьшить на 15 минут',
    increaseOffset: 'Увеличить на 15 минут',
    offsetHint: 'Каждое касание сдвигается на 15 минут · до 12ч назад или 4ч вперёд',
    now: 'Сейчас',
  },
  timer: {
    remaining: 'остаток',
    elapsedPct: (elapsed: string, pct: number) => `${elapsed} завершено · ${Math.round(pct)}%`,
    backgroundActive: 'Таймер продолжает работать в фоне.',
    endPredictionSameDay: (time: string) => `Заканчивается в ${time}`,
    endPredictionDiffDay: (time: string, date: string) => `Заканчивается в ${time} · ${date}`,
    zones: 'Метаболические зоны',
  },
  states: {
    activeBadge: 'Активное голодание',
    completeBadge: 'Голодание завершено',
    completeEmoji: '🎉',
    completeTitle: 'Вы сделали это!',
    completeMeta: (protocol: string, elapsed: string) => `${protocol} · ${elapsed} завершено`,
  },
  suggestion: {
    title: 'Сегодня это стоит',
  },
  buttons: {
    startFast: (protocol: string, timeLabel?: string) => 
      timeLabel ? `Начать ${protocol} · ${timeLabel}` : `Начать ${protocol}`,
    completeFast: 'Завершить голодание',
    finishAndClose: 'Зарегистрировать и закрыть',
    earlyFinish: 'Завершить раньше',
    continueEarlyFinish: 'Продолжить голодание',
    partialFinish: 'Завершить частично',
  },
  stats: {
    completedLabel: 'Завершено',
    avgLabel: 'Среднее',
    longestLabel: 'Самое длинное',
    completedMeta: (avg: number, longest: number) => `Среднее ${avg.toFixed(1)}ч · лучшее ${longest.toFixed(1)}ч`,
    noFasts: 'Ещё нет завершённых голоданий.',
  },
  history: {
    title: 'Последние голодания',
    missed: 'Пропущено',
    pending: 'В ожидании',
    completed: '✓',
    deleteBtn: 'Удалить',
    deleteA11y: (protocol: string) => `Удалить голодание ${protocol}`,
    emptyEmoji: '🌙',
    emptyTitle: 'Голодания ещё не зарегистрированы.',
    emptyHint: 'Завершите первое голодание, чтобы увидеть историю здесь.',
  },
  fiveTwo: {
    header: '📅 Сегодня ваш день 5:2',
    status: 'В ожидании',
    desc: (protocol: string, hours: number, time?: string) => 
      time ? `Протокол: ${protocol} · Цель: ${hours}ч · Запланированное время: ${time}` : `Протокол: ${protocol} · Цель: ${hours}ч`,
    button: 'Начать голодание 5:2 на сегодня',
    week: 'На этой неделе · 5:2',
    weekMeta: (completed: number, target: number) => `${completed}/${target} дней завершено`,
  },
  modals: {
    zoneDetail: {
      startHint: (hours: number) => `Эта зона начинается в ${hours}ч голодания.`,
      close: 'Закрыть',
    },
    deleteConfirm: {
      title: 'Удалить голодание',
      body: 'Удалить это голодание? Это действие не может быть отменено.',
      confirm: 'Удалить',
    },
    earlyFinish: {
      title: 'Завершить раньше?',
      percentComplete: (pct: number) => `${Math.round(pct)}%`,
      label: 'завершено',
      context: (elapsed: string) => `У вас ${elapsed} цели. Будет зарегистрировано как частичное.`,
    },
  },
  contextCard: {
    female: 'Женский контекст',
  },
  offsetLabel: {
    now: (time: string) => `Сейчас · ${time}`,
    past: (duration: string, time: string, dayLabel?: string) => `${duration} назад${dayLabel ? ` · ${dayLabel}` : ''} · ${time}`,
    future: (duration: string, time: string) => `Через ${duration} · ${time}`,
  },
} as const;

export const WaterModule = {
  header: {
    eyebrow: 'Настройки',
    title: 'Вода',
  },
  dailyGoal: {
    title: 'Ежедневная цель',
    description: 'Выберите реалистичную базу и позвольте приложению отрегулировать её в зависимости от контекста.',
    presets: {
      low: 'Низкая активность',
      moderate: 'Умеренная',
      recommended: 'Рекомендуемая',
      athlete: 'Атлеты',
      hotClimate: 'Жаркий климат',
    },
    customLabel: 'Пользовательская цель',
    customHint: 'От 500 мл до 10000 мл.',
    unit: 'мл',
  },
  infoCard: {
    eyebrow: 'Регулировка',
    body: 'VYRA может увеличить вашу цель, если жарко, если вы голодаете или если день содержит много активности.',
  },
  containers: {
    title: 'Быстрые объекты',
    description: 'Один раз отрегулируйте, сколько в ваших реальных контейнерах.',
    resetLabel: 'Сброс',
    resetA11y: 'Восстановить размеры по умолчанию',
    glass: 'Один стакан',
    largeGlass: 'Большой стакан',
    bottle: 'Бутылка',
  },
  warningCard: {
    eyebrow: 'Предупреждение',
    body: 'Напоминания живут в общих уведомлениях. Отсюда вы только настраиваете операционную часть.',
  },
  buttons: {
    openNotifications: 'Открыть уведомления',
    changeUnits: 'Изменить единицы',
  },
} as const;
