export const ShellStrings = {
  loadingMessage: 'جاري التحميل...',
  errorOccurred: 'حدث خطأ.',
  tryAgain: 'حاول مرة أخرى',
  ok: 'حسنا',
  cancel: 'إلغاء',
  delete: 'حذف',
  confirm: 'تأكيد',
  close: 'إغلاق',
  back: 'عودة',
  next: 'التالي',
  save: 'حفظ',
  search: 'بحث',
  settings: 'الإعدادات',
  help: 'مساعدة',
  about: 'حول',
  logout: 'خروج',
  login: 'دخول',
  register: 'تسجيل',
  profile: 'الملف الشخصي',
  menu: 'القائمة',
  notification: 'الإخطار',
  edit: 'تحرير',
  add: 'إضافة',
  remove: 'إزالة',
  select: 'اختيار',
  copy: 'نسخ',
  share: 'مشاركة',
  download: 'تحميل',
  upload: 'رفع',
  submit: 'إرسال',
  reset: 'إعادة تعيين',
  apply: 'تطبيق',
  filter: 'تصفية',
  sort: 'الترتيب',
  view: 'عرض',
  hide: 'إخفاء',
  show: 'عرض',
  expand: 'توسيع',
  collapse: 'طي',
} as const;
