export const ShellStrings = {
  loadingMessage: 'טוען...',
  errorOccurred: 'אירעה שגיאה.',
  tryAgain: 'נסה שוב',
  ok: 'אישור',
  cancel: 'ביטול',
  delete: 'מחק',
  confirm: 'אשר',
  close: 'סגור',
  back: 'חזור',
  next: 'הבא',
  save: 'שמור',
  search: 'חיפוש',
  settings: 'הגדרות',
  help: 'עזרה',
  about: 'אודות',
  logout: 'התנתק',
  login: 'היכנס',
  register: 'הירשם',
  profile: 'פרופיל',
  menu: 'תפריט',
  notification: 'התראה',
  edit: 'ערוך',
  add: 'הוסף',
  remove: 'הסר',
  select: 'בחר',
  copy: 'העתק',
  share: 'שתף',
  download: 'הורד',
  upload: 'העלה',
  submit: 'שלח',
  reset: 'אפס',
  apply: 'החל',
  filter: 'סנן',
  sort: 'מיין',
  view: 'צפה',
  hide: 'הסתר',
  show: 'הצג',
  expand: 'הרחב',
  collapse: 'כווץ',
} as const;
