export const ShellStrings = {
  loadingMessage: 'Sedang memuat...',
  errorOccurred: 'Terjadi kesalahan.',
  tryAgain: 'Coba Lagi',
  ok: 'OK',
  cancel: 'Batal',
  delete: 'Hapus',
  confirm: 'Konfirmasi',
  close: 'Tutup',
  back: 'Kembali',
  next: 'Berikutnya',
  save: 'Simpan',
  search: 'Cari',
  settings: 'Pengaturan',
  help: 'Bantuan',
  about: 'Tentang',
  logout: 'Keluar',
  login: 'Masuk',
  register: 'Daftar',
  profile: 'Profil',
  menu: 'Menu',
  notification: 'Notifikasi',
  edit: 'Edit',
  add: 'Tambah',
  remove: 'Hapus',
  select: 'Pilih',
  copy: 'Salin',
  share: 'Bagikan',
  download: 'Unduh',
  upload: 'Unggah',
  submit: 'Kirim',
  reset: 'Atur Ulang',
  apply: 'Terapkan',
  filter: 'Filter',
  sort: 'Sortir',
  view: 'Lihat',
  hide: 'Sembunyikan',
  show: 'Tampilkan',
  expand: 'Perluas',
  collapse: 'Perkecil',
} as const;
