export const ShellStrings = {
  loadingMessage: 'Φόρτωση...',
  errorOccurred: 'Προέκυψε σφάλμα.',
  tryAgain: 'Δοκιμάστε ξανά',
  ok: 'ΟΚ',
  cancel: 'Ακύρωση',
  delete: 'Διαγραφή',
  confirm: 'Επιβεβαίωση',
  close: 'Κλείσιμο',
  back: 'Επιστροφή',
  next: 'Επόμενο',
  save: 'Αποθήκευση',
  search: 'Αναζήτηση',
  settings: 'Ρυθμίσεις',
  help: 'Βοήθεια',
  about: 'Σχετικά',
  logout: 'Αποσύνδεση',
  login: 'Σύνδεση',
  register: 'Εγγραφή',
  profile: 'Προφίλ',
  menu: 'Μενού',
  notification: 'Ειδοποίηση',
  edit: 'Επεξεργασία',
  add: 'Προσθήκη',
  remove: 'Αφαίρεση',
  select: 'Επιλογή',
  copy: 'Αντιγραφή',
  share: 'Κοινοποίηση',
  download: 'Λήψη',
  upload: 'Αποστολή',
  submit: 'Υποβολή',
  reset: 'Επαναφορά',
  apply: 'Εφαρμογή',
  filter: 'Φίλτρο',
  sort: 'Ταξινόμηση',
  view: 'Προβολή',
  hide: 'Απόκρυψη',
  show: 'Εμφάνιση',
  expand: 'Διαστολή',
  collapse: 'Σύμπτυξη',
} as const;
