export const ShellStrings = {
  loadingMessage: 'Yükleniyor...',
  errorOccurred: 'Bir hata oluştu.',
  tryAgain: 'Tekrar Dene',
  ok: 'Tamam',
  cancel: 'İptal',
  delete: 'Sil',
  confirm: 'Onayla',
  close: 'Kapat',
  back: 'Geri',
  next: 'Sonraki',
  save: 'Kaydet',
  search: 'Ara',
  settings: 'Ayarlar',
  help: 'Yardım',
  about: 'Hakkında',
  logout: 'Çıkış Yap',
  login: 'Giriş Yap',
  register: 'Kayıt Ol',
  profile: 'Profil',
  menu: 'Menü',
  notification: 'Bildirim',
  edit: 'Düzenle',
  add: 'Ekle',
  remove: 'Kaldır',
  select: 'Seç',
  copy: 'Kopyala',
  share: 'Paylaş',
  download: 'İndir',
  upload: 'Yükle',
  submit: 'Gönder',
  reset: 'Sıfırla',
  apply: 'Uygula',
  filter: 'Filtre',
  sort: 'Sırala',
  view: 'Görüntüle',
  hide: 'Gizle',
  show: 'Göster',
  expand: 'Genişlet',
  collapse: 'Daralt',
} as const;
