export const ShellStrings = {
  loadingMessage: 'Đang tải...',
  errorOccurred: 'Đã xảy ra lỗi.',
  tryAgain: 'Thử lại',
  ok: 'OK',
  cancel: 'Hủy',
  delete: 'Xóa',
  confirm: 'Xác nhận',
  close: 'Đóng',
  back: 'Quay lại',
  next: 'Tiếp theo',
  save: 'Lưu',
  search: 'Tìm kiếm',
  settings: 'Cài đặt',
  help: 'Trợ giúp',
  about: 'Về',
  logout: 'Đăng xuất',
  login: 'Đăng nhập',
  register: 'Đăng ký',
  profile: 'Hồ sơ',
  menu: 'Menu',
  notification: 'Thông báo',
  edit: 'Chỉnh sửa',
  add: 'Thêm',
  remove: 'Xóa',
  select: 'Chọn',
  copy: 'Sao chép',
  share: 'Chia sẻ',
  download: 'Tải về',
  upload: 'Tải lên',
  submit: 'Gửi',
  reset: 'Đặt lại',
  apply: 'Áp dụng',
  filter: 'Lọc',
  sort: 'Sắp xếp',
  view: 'Xem',
  hide: 'Ẩn',
  show: 'Hiển thị',
  expand: 'Mở rộng',
  collapse: 'Thu gọn',
} as const;
