export const ShellStrings = {
  loadingMessage: 'Chargement...',
  errorOccurred: 'Une erreur s\'est produite.',
  tryAgain: 'Réessayer',
  ok: 'OK',
  cancel: 'Annuler',
  delete: 'Supprimer',
  confirm: 'Confirmer',
  close: 'Fermer',
  back: 'Retour',
  next: 'Suivant',
  save: 'Enregistrer',
  search: 'Rechercher',
  settings: 'Paramètres',
  help: 'Aide',
  about: 'À propos',
  logout: 'Déconnexion',
  login: 'Connexion',
  register: 'S\'inscrire',
  profile: 'Profil',
  menu: 'Menu',
  notification: 'Notification',
  edit: 'Modifier',
  add: 'Ajouter',
  remove: 'Supprimer',
  select: 'Sélectionner',
  copy: 'Copier',
  share: 'Partager',
  download: 'Télécharger',
  upload: 'Téléverser',
  submit: 'Soumettre',
  reset: 'Réinitialiser',
  apply: 'Appliquer',
  filter: 'Filtrer',
  sort: 'Trier',
  view: 'Afficher',
  hide: 'Masquer',
  show: 'Afficher',
  expand: 'Développer',
  collapse: 'Réduire',
} as const;
