// ============================================================
// VYRA FITNESS — Strings (EN)
// ============================================================

export const ErrorMessages = {
  noInternet:      'No signal right now — keep logging, we will sync when you are back online.',
  aiUnavailable:   'My AI brain is taking a short break — try again in a few minutes.',
  saveFailed:      'Something failed while saving. It is stored locally and will sync automatically.',
  barcodeNotFound: 'Barcode not found. Want to enter it manually? I can search by product name.',
  paypalError:     'There was a payment issue. You were not charged — you can try again.',
  photoAIFailed:   'I could not read this meal clearly. Want to enter it manually?',
  voiceLogFailed:  'I did not catch that. Want to try again or enter it manually?',
  loginFailed:     'I could not sign you in. Check your details and try again.',
  registerFailed:  'Something went wrong creating your account. Try again.',
  sessionExpired:  'Your session expired. Please sign in again.',
  premiumRequired: 'This feature is Premium. Activate it with PayPal whenever you want.',
  generic:         'Something went wrong. Try again in a moment.',
  loadFailed:      'I could not load the data. Pull to try again.',
  syncFailed:      'I could not sync. Your data is safe locally.',
  permissionDenied:'I need your permission to continue. You can change it in Settings.',
} as const;

export const AuthStrings = {
  welcome: {
    title:    'Your best self,\nevery day.',
    subtitle: 'Water, steps, food, sleep, and mind — all in one place that gets you.',
    cta:      'Start now',
    login:    'I already have an account',
  },
  login: {
    title:    'Welcome\nback',
    email:    'Email',
    password: 'Password',
    cta:      'Sign in',
    forgot:   'Forgot your password?',
    noAccount:'No account yet?',
    register: 'Create one for free',
  },
  register: {
    title:      'Create account',
    name:       'Your name',
    email:      'Email',
    password:   'Password (min 8 characters)',
    cta:        'Create my account',
    haveAccount:'Already have an account?',
    login:      'Sign in',
    tosLabel:   'I accept the',
    tos:        'Terms of Service',
    and:        'and the',
    privacy:    'Privacy Policy',
    healthConsent: 'I consent to Vyra processing my health data to personalize my experience',
    medicalDisclaimer: 'I understand Vyra is not a medical device and does not replace professional medical advice',
  },
  medicalModal: {
    title:   'Before you start',
    body:    'Vyra is a wellness and fitness app. It is not a certified medical device and does not replace medical consultation, diagnosis, or treatment.\n\nAlways consult your doctor if you have health concerns.',
    cta:     'Got it, continue',
  },
} as const;

export const OnboardingStrings = {
  step1: {
    title:    'What is your main goal?',
    subtitle: 'We use it to personalize everything in Vyra.',
    goals: {
      lose_fat:          'Lose fat',
      gain_muscle:       'Gain muscle',
      general_health:    'General health',
      sport_performance: 'Sport performance',
      mental_wellbeing:  'Mental wellbeing',
    },
  },
  step2: {
    title:    'Tell us about you',
    subtitle: 'We calculate your TDEE and personalized targets.',
    gender: {
      label:            'Biological sex',
      male:             'Male',
      female:           'Female',
      non_binary:       'Non binary',
      prefer_not_to_say:'Prefer not to say',
    },
    age:       'Age',
    height:    'Height (cm)',
    weight:    'Current weight (kg)',
    goalWeight:'Goal weight (kg, optional)',
  },
  step3: {
    title:    'How active are you?',
    subtitle: 'This calibrates your step and calorie goals.',
    levels: {
      0: 'Sedentary — almost no activity',
      1: 'Very low — 1-2 days/week',
      2: 'Somewhat active — 3 days/week',
      3: 'Moderately active — 4-5 days/week',
      4: 'Very active — 6-7 days/week',
      5: 'Athlete — multiple sessions per day',
    },
    equipment: {
      label:    'Where do you train?',
      gym:      'Gym',
      home:     'Home',
      both:     'Both',
      outside:  'Outdoors',
      none:     'Not training for now',
    },
  },
  step4: {
    title:    'Your schedule',
    subtitle: 'We set notifications without bothering you.',
    wakeTime:  'What time do you wake up?',
    sleepTime: 'What time do you go to sleep?',
    fasting: {
      label:    'Do you do intermittent fasting?',
      yes:      'Yes, I want to try it',
      no:       'Not for now',
    },
    protocol: 'Which protocol do you prefer?',
  },
  step5: {
    title:    'Activate Premium\nwith no waiting',
    subtitle: 'PayPal charges on confirmation. There is no free trial. Cancel anytime.',
    features: {
      aiCoach:      'AI coach with real memory',
      photoLog:     'Unlimited barcode scanner',
      voiceLog:     'No ads in Premium',
      unlimitedHistory: 'Tracking and synced account',
      correlations: 'Sleep/weight/nutrition correlations',
      noAds:        'No ads',
    },
    monthly:     '$12.99/month',
    yearly:      '$99.99/year',
    yearlyNote:  'Save 36% (~$8.33/month)',
    trialCta:    'Go to PayPal checkout',
    freeCta:     'Continue free',
    freeNote:    'Free with ads and basic features. No Premium trial.',
  },
  next:   'Next',
  back:   'Back',
  skip:   'Skip',
  finish: 'Start',
  step:   'Step',
  of:     'of',
} as const;

export const DashboardStrings = {
  greeting: {
    morning:   'Good morning',
    afternoon: 'Good afternoon',
    evening:   'Good evening',
  },
  dailyScore:    'Daily score',
  streak:        'streak days',
  bestStreak:    'best streak',
  checkIn:       'Mental check-in',
  checkInDone:   'Check-in done',
  quickActions:  'Quick actions',
  todayMissions: 'Today missions',
  aiInsight:     'Coach says:',
  noInsight:     'Complete your first check-in to receive insights.',
} as const;

export const ModuleNames = {
  water:       'Hydration',
  steps:       'Steps',
  fasting:     'Fasting',
  sleep:       'Sleep',
  nutrition:   'Nutrition',
  weight:      'Weight',
  workout:     'Workouts',
  mental:      'Mood',
  female:      'Female Health',
  supplements: 'Supplements',
  recovery:    'Recovery',
} as const;

export const ModuleEmojis = {
  water:       '💧',
  steps:       '🚶',
  fasting:     '⏳',
  sleep:       '😴',
  nutrition:   '🍎',
  weight:      '⚖️',
  workout:     '💪',
  mental:      '🧠',
  female:      '🌸',
  supplements: '💊',
  recovery:    '🧘',
} as const;

export const GamificationStrings = {
  coins:        'VyraCoins',
  coinSymbol:   '🪙',
  xp:           'XP',
  level:        'Level',
  streak:       'Streak',
  days:         'days',
  badge:        'Badge',
  newRecord:    'New personal record!',
  levelUp:      'You reached level',
  streakSaved:  'Streak saved!',
  badgeUnlocked:'Badge unlocked!',
  watchAdFor:   'Watch ad for',
  earn:         'You earn',
  watchAd:      'Watch ad',
  skipAd:       'Skip',
} as const;

export const Disclaimers = {
  coach:        'Vyra Coach is a wellness assistant. It does not replace medical, nutrition, or psychological advice.',
  supplements:  'This app does not recommend supplement doses or combinations. Consult a health professional.',
  bmi:          'BMI and body fat are estimates. For medical diagnosis, consult your doctor.',
  cycle:        'Predictions are estimates. Do not use this app as contraception.',
  fasting24h:   'Long fasting is not suitable for people with diabetes, pregnancy, or eating disorders. Consult your doctor before starting.',
  deficitHigh:  'You are in a very aggressive calorie deficit. It can be harmful long-term. Consider a nutritionist.',
} as const;

export const NotificationStrings = {
  waterReminder:    (ml: number, goal: number) => `It is ${new Date().getHours()}h. You are at ${ml}ml of ${goal}ml. Want to add a glass?`,
  stepsReminder:    (steps: number, goal: number) => `You have ${steps.toLocaleString()}/${goal.toLocaleString()} steps. Almost there!`,
  streakDanger:     (days: number) => `Your ${days}-day streak is at risk. Tap to log in 30s.`,
  fastingPhase:     (phase: string) => `You entered ${phase}. Streak on.`,
  goalReached:      (goal: string) => `Goal ${goal} achieved!`,
  prAchieved:       (exercise: string, weight: number) => `New PR: ${weight}kg on ${exercise}.`,
} as const;

export const General = {
  save:      'Save',
  cancel:    'Cancel',
  confirm:   'Confirm',
  delete:    'Delete',
  edit:      'Edit',
  close:     'Close',
  back:      'Back',
  continue:  'Continue',
  retry:     'Try again',
  loading:   'Loading...',
  syncing:   'Syncing...',
  today:     'Today',
  yesterday: 'Yesterday',
  week:      'Week',
  month:     'Month',
  all:       'All',
  free:      'Free',
  premium:   'Premium',
  upgrade:   'Upgrade to Premium',
  history:   'History',
  settings:  'Settings',
  profile:   'Profile',
  logout:    'Sign out',
  or:        'or',
  and:       'and',
  of:        'of',
  for:       'for',
  done:      'Done',
  add:       'Add',
  remove:    'Remove',
  search:    'Search',
  noResults: 'No results',
  empty:     'Nothing here yet.',
  offline:   'Offline',
  online:    'Online',
} as const;
