export const ShellStrings = {
  loadingMessage: 'Wird geladen...',
  errorOccurred: 'Ein Fehler ist aufgetreten.',
  tryAgain: 'Erneut versuchen',
  ok: 'OK',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  confirm: 'Bestätigen',
  close: 'Schließen',
  back: 'Zurück',
  next: 'Nächste',
  save: 'Speichern',
  search: 'Suchen',
  settings: 'Einstellungen',
  help: 'Hilfe',
  about: 'Über',
  logout: 'Abmelden',
  login: 'Anmelden',
  register: 'Registrieren',
  profile: 'Profil',
  menu: 'Menü',
  notification: 'Benachrichtigung',
  edit: 'Bearbeiten',
  add: 'Hinzufügen',
  remove: 'Entfernen',
  select: 'Auswählen',
  copy: 'Kopieren',
  share: 'Teilen',
  download: 'Herunterladen',
  upload: 'Hochladen',
  submit: 'Absenden',
  reset: 'Zurücksetzen',
  apply: 'Anwenden',
  filter: 'Filtern',
  sort: 'Sortieren',
  view: 'Anzeigen',
  hide: 'Verbergen',
  show: 'Anzeigen',
  expand: 'Erweitern',
  collapse: 'Reduzieren',
} as const;
