export const ShellStrings = {
  loadingMessage: 'Ładowanie...',
  errorOccurred: 'Wystąpił błąd.',
  tryAgain: 'Spróbuj ponownie',
  ok: 'OK',
  cancel: 'Anuluj',
  delete: 'Usuń',
  confirm: 'Potwierdź',
  close: 'Zamknij',
  back: 'Wstecz',
  next: 'Dalej',
  save: 'Zapisz',
  search: 'Szukaj',
  settings: 'Ustawienia',
  help: 'Pomoc',
  about: 'O nas',
  logout: 'Wyloguj się',
  login: 'Zaloguj się',
  register: 'Zarejestruj się',
  profile: 'Profil',
  menu: 'Menu',
  notification: 'Powiadomienie',
  edit: 'Edytuj',
  add: 'Dodaj',
  remove: 'Usuń',
  select: 'Wybierz',
  copy: 'Skopiuj',
  share: 'Udostępnij',
  download: 'Pobierz',
  upload: 'Prześlij',
  submit: 'Prześlij',
  reset: 'Zresetuj',
  apply: 'Zastosuj',
  filter: 'Filtruj',
  sort: 'Sortuj',
  view: 'Widok',
  hide: 'Ukryj',
  show: 'Pokaż',
  expand: 'Rozwiń',
  collapse: 'Zwiń',
} as const;
