export { ShellStrings } from './strings.shell.hi';

export const ErrorMessages = {
  noInternet: 'यहाँ कोई सिग्नल नहीं है। पंजीकरण करते रहें और जब कनेक्शन वापस आए तो मैं सिंक करूँ।',
  aiUnavailable: 'AI परत अभी उपलब्ध नहीं है। कुछ मिनट में फिर से कोशिश करें।',
  saveFailed: 'अभी सहेज नहीं सका। आपका डेटा सुरक्षित है और मैं फिर कोशिश करूँगा।',
  barcodeNotFound: 'वह कोड नहीं मिला। आप भोजन खोज सकते हैं या मैन्युअल रूप से प्रविष्ट कर सकते हैं।',
  paymentError: 'यह क्रिया पूरी नहीं कर सका। कोई परिवर्तन लागू नहीं हुआ।',
  photoAIFailed: 'वह भोजन अच्छी तरह नहीं पढ़ सका। दूसरी फ़ोटो आजमाएँ या मैन्युअल रूप से प्रविष्ट करें।',
  voiceLogFailed: 'वह वॉयस रिकॉर्डिंग समझ नहीं सका। फिर से कोशिश करें या मैन्युअल रूप से प्रविष्ट करें।',
  loginFailed: 'लॉगिन नहीं कर सका। अपना डेटा जाँचें और फिर से कोशिश करें।',
  registerFailed: 'खाता नहीं बना सका। फिर से कोशिश करें।',
  sessionExpired: 'आपका सत्र समाप्त हो गया। जारी रखने के लिए फिर से लॉगिन करें।',
  premiumRequired: 'यह सुविधा आपकी वर्तमान पहुँच में उपलब्ध नहीं है।',
  generic: 'कुछ गलत हुआ। एक पल में फिर से कोशिश करें।',
  loadFailed: 'डेटा लोड नहीं कर सका। फिर से कोशिश के लिए स्वाइप करें।',
  syncFailed: 'सिंक नहीं कर सका। आपका डेटा स्थानीय रूप से सहेजा गया है।',
  permissionDenied: 'जारी रखने के लिए मुझे आपकी अनुमति चाहिए। आप इसे सेटिंग्स में बदल सकते हैं।',
} as const;

export const AuthStrings = {
  welcome: {
    title: 'आपकी फिटनेस आज से स्पष्ट है।',
    subtitle: 'एक ऐप में व्यायाम, भोजन, पानी, नींद और प्रगति।',
    cta: 'मुफ़्त खाता बनाएँ',
    login: 'मेरे खाते में लॉगिन करें',
    legal: 'जारी रखकर आप हमारी शर्तें स्वीकार करते हैं।',
  },
  login: {
    title: 'स्वागत है वापसी पर',
    email: 'ईमेल',
    password: 'पासवर्ड',
    cta: 'लॉगिन करें',
    forgot: 'अपना पासवर्ड भूल गए',
    noAccount: 'खाता नहीं है',
    register: 'खाता बनाएँ',
  },
  register: {
    title: 'खाता बनाएँ',
    name: 'आपका नाम',
    email: 'ईमेल',
    password: 'पासवर्ड (न्यूनतम 8 वर्ण)',
    cta: 'मेरा खाता बनाएँ',
    haveAccount: 'मेरे पास पहले से खाता है',
    login: 'लॉगिन करें',
    tosLabel: 'मैं स्वीकार करता हूँ',
    tos: 'सेवा की शर्तें',
    and: 'और',
    privacy: 'गोपनीयता नीति',
    healthConsent: 'मैं Vyra को मेरे स्वास्थ्य डेटा को मेरा अनुभव व्यक्तिगत करने के लिए प्रसंस्करण करने की सहमति देता हूँ।',
    medicalDisclaimer:
      'मैं समझता हूँ कि Vyra एक चिकित्सा उपकरण नहीं है और पेशेवर मूल्यांकन का स्थान नहीं ले सकता।',
  },
  medicalModal: {
    title: 'शुरू करने से पहले',
    body:
      'Vyra एक कल्याण और फिटनेस ऐप है। यह एक प्रमाणित चिकित्सा उपकरण नहीं है और परामर्श, निदान या व्यावसायिक उपचार का स्थान नहीं ले सकता।',
    cta: 'समझा, जारी रखें',
  },
} as const;

export const OnboardingStrings = {
  step1: {
    title: 'आपका मुख्य लक्ष्य क्या है?',
    subtitle: 'हम एक सुसंगत प्रारंभिक अनुभव तैयार करने के लिए इसका उपयोग करते हैं।',
    goals: {
      lose_fat: 'वसा खोना',
      gain_muscle: 'मांसपेशी प्राप्त करें',
      general_health: 'सामान्य स्वास्थ्य',
      sport_performance: 'खेल प्रदर्शन',
      mental_wellbeing: 'सामान्य कल्याण',
    },
  },
  step2: {
    title: 'आप कहाँ व्यायाम करते हैं?',
    subtitle: 'तो हम दिनचर्या और व्यायाम के प्रकार को फ़िल्टर करते हैं।',
    gender: {
      label: 'जैविक लिंग',
      male: 'पुरुष',
      female: 'महिला',
      non_binary: 'गैर-बाइनरी',
      prefer_not_to_say: 'कहना पसंद नहीं',
    },
    age: 'आयु',
    height: 'ऊँचाई (सेमी)',
    weight: 'वर्तमान वजन (किग्रा)',
    goalWeight: 'लक्ष्य वजन (किग्रा, वैकल्पिक)',
  },
  step3: {
    title: 'आपका मुख्य ध्यान क्या है?',
    subtitle: 'मुख्य मॉड्यूल चुनें और फिर यदि चाहें तो समर्थन जोड़ें।',
    levels: {
      0: 'बहुत कम',
      1: 'कम',
      2: 'मध्यम',
      3: 'सक्रिय',
      4: 'बहुत सक्रिय',
      5: 'एथलीट',
    },
    equipment: {
      label: 'उपलब्ध उपकरण',
      gym: 'पूर्ण जिम',
      home: 'बुनियादी सामग्री के साथ घर',
      both: 'दोनों',
      outside: 'बाहर',
      none: 'कोई सामग्री नहीं',
    },
  },
  step4: {
    title: 'सब कुछ तैयार है',
    subtitle: 'हमने आज के लिए पहली कार्रवाई तैयार की है।',
    wakeTime: 'जागने का समय',
    sleepTime: 'सोने का समय',
    fasting: {
      label: 'अंतराल उपवास',
      yes: 'हाँ',
      no: 'नहीं',
    },
    protocol: 'प्रोटोकॉल',
  },
  step5: {
    title: 'पूर्ण पहुँच',
    subtitle: 'पहले दिन से उन्नत विशेषताएँ तैयार हैं।',
    features: {
      aiCoach: 'संदर्भ AI',
      photoLog: 'फ़ोटो रजिस्ट्रेशन',
      voiceLog: 'वॉयस रजिस्ट्रेशन',
      unlimitedHistory: 'विस्तारित इतिहास',
      correlations: 'अधिक संदर्भ और सहसंबंध',
      noAds: 'पहले दिन से पूर्ण पहुँच',
    },
    monthly: 'पूर्ण पहुँच',
    yearly: 'सब कुछ तैयार है',
    yearlyNote: 'बिना अनलॉक के',
    trialCta: 'Vyra में प्रवेश करें',
    freeCta: 'जारी रखें',
    freeNote: 'उत्पाद पहले से ही खुला और उपयोग के लिए तैयार है।',
  },
  next: 'अगला',
  back: 'वापस',
  skip: 'छोड़ें',
  finish: 'शुरू करें',
  step: 'चरण',
  of: 'का',
} as const;

export const DashboardStrings = {
  greeting: {
    morning: 'सुप्रभात',
    afternoon: 'शुभ दोपहर',
    evening: 'शुभ संध्या',
  },
  dailyScore: 'दिन का संकेत',
  streak: (days: number) => `${days} ${days === 1 ? 'दिन' : 'दिन'} की श्रृंखला`,
  bestStreak: 'सर्वश्रेष्ठ श्रृंखला',
  checkIn: 'दिन की जाँच',
  checkInDone: 'जाँच पूरी हुई',
  quickActions: 'तेज़ रजिस्ट्रेशन',
  todayMissions: 'इस सप्ताह',
  aiInsight: 'आज की संदर्भ:',
  noInsight: 'संदर्भ प्राप्त करने के लिए अपनी पहली रजिस्ट्रेशन पूरी करें।',
} as const;

export const ModuleNames = {
  water: 'पानी',
  steps: 'कदम',
  fasting: 'उपवास',
  sleep: 'नींद',
  nutrition: 'पोषण',
  weight: 'वजन',
  workout: 'कसरत',
  mental: 'कल्याण',
  female: 'महिला स्वास्थ्य',
  supplements: 'पूरक',
  recovery: 'पुनर्प्राप्ति',
} as const;

export const ModuleEmojis = {
  water: '💧',
  steps: '🚶',
  fasting: '⏳',
  sleep: '😴',
  nutrition: '🥗',
  weight: '⚖️',
  workout: '🏋️',
  mental: '🧠',
  female: '🌸',
  supplements: '💊',
  recovery: '🛌',
} as const;

export const Disclaimers = {
  context: 'Vyra की संदर्भ AI सामान्य मार्गदर्शन प्रदान करती है और पेशेवर देखभाल का स्थान नहीं लेती।',
  supplements:
    'Vyra पूरक की खुराक या संयोजन की सिफारिश नहीं करता। स्वास्थ्य सेवा पेशेवर से परामर्श लें।',
  bmi: 'BMI और वसा प्रतिशत अनुमान हैं। ये चिकित्सा निदान नहीं हैं।',
  cycle: 'चक्र पूर्वानुमान अनुमानित है। इसे गर्भनिरोधक विधि के रूप में उपयोग नहीं करना चाहिए।',
  fasting24h:
    'लंबे समय तक उपवास सभी के लिए उपयुक्त नहीं है। यदि आपको संदेह है तो पेशेवर से परामर्श लें।',
  deficitHigh:
    'आक्रामक कैलोरी घाटा दीर्घकाल में हानिकारक हो सकता है। किसी पोषण विशेषज्ञ से परामर्श लें।',
} as const;

export const NotificationStrings = {
  waterReminder: (ml: number, goal: number) => `आपने ${ml} मिली से ${goal} मिली का सेवन किया। एक गिलास जोड़ें?`,
  stepsReminder: (steps: number, goal: number) =>
    `आपने ${steps.toLocaleString()} से ${goal.toLocaleString()} कदम चलाए।`,
  streakDanger: (days: number) =>
    `आपकी ${days} दिन की श्रृंखला जोखिम में है। आज एक छोटी कार्रवाई इसे बचाएगी।`,
  fastingPhase: (phase: string) => `आप ${phase} में प्रवेश किए। आपका उपवास अच्छी तरह चल रहा है।`,
  goalReached: (goal: string) => `${goal} का लक्ष्य पूरा हुआ।`,
  prAchieved: (exercise: string, weight: number) => `नया रिकॉर्ड: ${exercise} में ${weight} किग्रा।`,
} as const;

export const General = {
  save: 'सहेजें',
  cancel: 'रद्द करें',
  confirm: 'पुष्टि करें',
  delete: 'हटाएँ',
  edit: 'संपादित करें',
  close: 'बंद करें',
  back: 'वापस',
  continue: 'जारी रखें',
  retry: 'फिर से कोशिश करें',
  loading: 'लोड हो रहा है...',
  syncing: 'सिंक हो रहा है...',
  today: 'आज',
  yesterday: 'कल',
  week: 'सप्ताह',
  month: 'महीना',
  all: 'सभी',
  free: 'मुफ़्त',
  premium: 'शामिल',
  upgrade: 'पहुँच देखें',
  history: 'इतिहास',
  settings: 'सेटिंग्स',
  profile: 'प्रोफ़ाइल',
  logout: 'लॉग आउट',
  or: 'या',
  and: 'और',
  of: 'का',
  for: 'के लिए',
  done: 'पूरा',
  add: 'जोड़ें',
  remove: 'हटाएँ',
  search: 'खोजें',
  noResults: 'कोई परिणाम नहीं',
  empty: 'यहाँ अभी कुछ नहीं है।',
  offline: 'ऑफ़लाइन',
  online: 'ऑनलाइन',
} as const;

export const ValidationMessages = {
  emailInvalid: 'ईमेल सही प्रारूप में नहीं है।',
  passwordRequired: 'पासवर्ड आवश्यक है।',
  passwordTooShort: 'पासवर्ड कम से कम 8 वर्ण लंबा होना चाहिए।',
  ageTooYoung: 'Vyra का उपयोग करने के लिए आपकी आयु कम से कम 13 वर्ष होनी चाहिए।',
  ageInvalid: 'दर्ज की गई आयु सही नहीं है।',
  weightTooLow: 'न्यूनतम वजन 20 किग्रा है।',
  weightInvalid: 'दर्ज किया गया वजन सही नहीं है।',
  heightTooLow: 'न्यूनतम ऊँचाई 50 सेमी है।',
  heightInvalid: 'दर्ज की गई ऊँचाई सही नहीं है।',
  waterAmountTooHigh: 'अधिकतम मात्रा प्रति रजिस्ट्रेशन 5,000 मिली है।',
  waterGoalTooLow: 'न्यूनतम लक्ष्य 500 मिली है।',
  waterGoalTooHigh: 'अधिकतम लक्ष्य 10,000 मिली है।',
  stepsGoalTooLow: 'न्यूनतम लक्ष्य 1,000 कदम है।',
  stepsGoalTooHigh: 'अधिकतम लक्ष्य 100,000 कदम है।',
  foodAmountTooHigh: 'अधिकतम मात्रा 5,000 ग्राम है।',
  barcodeScanEmpty: 'स्कैन की गई कोड खाली है।',
  barcodeTypeUnrecognized: 'हम कोड के प्रकार को पहचान नहीं सके।',
  barcodeProcessError: 'कोड को संसाधित करने में त्रुटि।',
  emailAlreadyExists: 'यह ईमेल पहले से पंजीकृत है। आप इस खाते से लॉगिन कर सकते हैं।',
  networkError: 'Vyra से जुड़ नहीं सके। अपने कनेक्शन की जाँच करें और फिर से कोशिश करें।',
  tempSessionError: 'अस्थायी सत्र खोल नहीं सके। फिर से कोशिश करें।',
  emailSendError: 'ईमेल भेज नहीं सके। पता जाँचें।',
  accountDeleteSuccess: 'आपका अनुरोध संसाधित किया गया और हमने सत्र समाप्त कर दिया। अंतिम हटाना वर्तमान नीति के अनुसार है।',
} as const;

export const FastingLabels = {
  activePhase: 'सक्रिय उपवास',
  autophagy: 'आटोफेजी',
  deepFast: 'गहरा उपवास',
  extendedFast: 'विस्तारित उपवास',
  gentleEntry: 'कम वसूली के दिनों के लिए कोमल प्रवेश',
  omad: 'OMAD — दिन में एक भोजन',
  omadAlt: 'दिन में एक भोजन (OMAD)',
  fastDay: 'प्रतिबंध दिन (5:2 प्रोटोकॉल)',
  hungryPhaseWarning: 'इस चरण में भूख और थकान बढ़ जाती है। इस सप्ताह छोटा प्रोटोकॉल बेहतर होगा।',
  consistencyTip: 'आपका पैटर्न दर्शाता है कि थोड़ा अधिक लचीला खिड़की साप्ताहिक निरंतरता में सुधार कर सकता है।',
  progressTip: 'आप बार-बार कम हो रहे हैं। एक मध्य प्रोटोकॉल आदत को मजबूत कर सकता है।',
  readyProgress: 'आपने कई 16:8 पूरे किए हैं मार्जिन के साथ। आप 18:6 के लिए तैयार हैं।',
  autophagyCountdown: 'आटोफेजी में 45 मिनट बाकी। आप यहाँ तक पहुँच गए, थोड़ा और सहन करें।',
  fastingCancelled: 'उपवास रद्द। अगला बेहतर होगा!',
  fast52Started: 'आपके समय के अनुसार 5:2 उपवास शुरू हुआ।',
  stayConsistent: 'इस चरण में स्थिर प्रोटोकॉल रखना अतिरिक्त घंटों का पीछा करने से अधिक मायने रखता है। 16:8 आज एक अच्छा आधार है।',
  focusConsistency: 'आज वर्तमान प्रोटोकॉल पकड़ें। निरंतरता और स्मार्ट उपवास ब्रेक पर ध्यान दें।',
  menstrualGuidance: 'मासिक धर्म चरण: 12:12 या 14:10 का उपयोग करें यदि शरीर भार कम करने के लिए कहता है। वसूली पहले।',
  lutealGuidance: 'ल्यूटिअल चरण: 14:10 या 16:8 बेहतर काम करता है सरल उपवास ब्रेक के साथ।',
  ovulatoryGuidance: 'अंडोत्सर्ग चरण: यदि आप अच्छी नींद लेते हैं तो मानक प्रोटोकॉल अच्छी तरह सहन किया जाता है।',
  cancelled: 'उपवास रद्द',
  // Phase descriptions
  fedPhase: 'भोजन के बाद',
  fedPhaseDesc: 'पाचन कर रहा। इंसुलिन ऊँचा।',
  activePhaseDesc: 'ग्लाइकोजन का सेवन शुरू होना।',
  ketosisPhase: 'प्रारंभिक कीटोसिस',
  ketosisPhaseDesc: 'शरीर वसा जलाना शुरू करता है।',
  autophagyDesc: 'सक्रिय कोशिका पुनर्चक्रण। अधिकतम लाभ।',
  deepFastDesc: 'HGH बढ़ रहा है। तीव्र कोशिका पुनर्जन्म।',
  extendedFastDesc: 'अस्तित्व मोड। अधिकतम कोशिका अस्तित्व।',
  // Protocol descriptions
  protocol12_12Desc: 'कम वसूली के दिनों के लिए कोमल प्रवेश',
  protocol14_10Desc: 'निष्ठा बनाए रखने के लिए मध्य चरण',
  protocol16_8Desc: '16 घंटे उपवास, 8 घंटे खाना — सबसे लोकप्रिय',
  protocol18_6Desc: '18 घंटे उपवास, 6 घंटे खिड़की',
  protocol20_4Desc: 'वारियर डाइट',
  protocol23_1Desc: 'OMAD — दिन में एक भोजन',
  protocolOMADDesc: 'दिन में एक भोजन (OMAD)',
  protocol24hDesc: 'पूर्ण 24 घंटे का उपवास।',
  protocol5_2Desc: 'प्रतिबंध दिन (5:2 प्रोटोकॉल)',
  protocolCustomDesc: 'अनुकूलित',
} as const;

export const FemaleHealthLabels = {
  menstrual: 'मासिक धर्म',
  follicular: 'कूपिक',
  ovulation: 'अंडोत्सर्ग',
  luteal: 'ल्यूटिअल',
  weightVariations: 'वजन में उतार-चढ़ाव चरण के आधार पर अस्थायी हो सकते हैं।',
  hydrationMenstrual: 'मासिक धर्म के दौरान अतिरिक्त जलयोजन।',
  fastingMenstrual: 'कोमल प्रोटोकॉल (12:12 या 14:10)।',
  sleepMenstrual: 'पुनर्स्थापक नींद को प्राथमिकता दें।',
  trainingRecovery: 'सक्रिय वसूली, गतिशीलता या हल्का शक्ति।',
  fastingFollicular: 'मानक प्रोटोकॉल में अधिक सहनशीलता (16:8)।',
  nutritionFollicular: 'कार्यक्षमता और वसूली के लिए प्रोटीन और जस्ता बढ़ाएँ।',
  trainingOvulation: 'उच्च ऊर्जा खिड़की: उच्च शक्ति/तीव्रता।',
  fastingOvulation: 'यदि अच्छी वसूली है तो 16:8 या 18:6 बनाए रखा जा सकता है।',
  fastingLuteal: 'ल्यूटिअल चरण में यह कठिन हो सकता है; यदि उच्च भूख दिखाई दे तो प्रोटोकॉल संक्षिप्त करें।',
  nutritionLuteal: 'स्थिर ऊर्जा के लिए मैग्नीशियम और जटिल कार्बोहाइड्रेट बढ़ाएँ।',
  nextOvulationNotice: 'कल आप अंडोत्सर्ग खिड़की में प्रवेश करते हैं: उच्च तीव्रता प्रशिक्षण तैयार करते हैं।',
  menstruationNotice: 'आपका मासिक धर्म जल्द शुरू होगा। इस सप्ताह अतिरिक्त जलयोजन और वसूली को प्राथमिकता दें।',
  cycleVariation: 'आपका चक्र अवधि के बीच 7 दिन से अधिक भिन्न होता है। यह स्त्री रोग विशेषज्ञ के साथ चर्चा करने लायक है।',
  needSupport: 'आपको समर्थन की आवश्यकता है',
  // Phase guidance (menstrual)
  menstrualTraining: 'सक्रिय वसूली, गतिशीलता या हल्का शक्ति।',
  menstrualFasting: 'छोटे प्रोटोकॉल (12-14 घंटे) या उपवास से ब्रेक को प्राथमिकता दें।',
  menstrualNutrition: 'लौह, ओमेगा-3 और सूजन-रोधी खाद्य पदार्थों को मजबूत करें।',
  menstrualWeightContext: 'मासिक धर्म/ल्यूटिअल चरण में तरल के कारण 1-3 किग्रा के उतार-चढ़ाव हो सकते हैं।',
  // Phase guidance (follicular)
  follicularTraining: 'भार और मात्रा बढ़ाने के लिए अच्छा चरण।',
  follicularFasting: 'मानक प्रोटोकॉल में अधिक सहनशीलता (16:8)।',
  follicularNutrition: 'कार्यक्षमता और वसूली के लिए प्रोटीन और जस्ता बढ़ाएँ।',
  // Phase guidance (ovulation)
  ovulationTraining: 'उच्च ऊर्जा खिड़की: उच्च शक्ति/तीव्रता।',
  ovulationFasting: 'यदि अच्छी वसूली है तो 16:8 या 18:6 बनाए रखा जा सकता है।',
  ovulationNutrition: 'एंटीऑक्सिडेंट और गुणवत्ता कार्बोहाइड्रेट को प्राथमिकता दें।',
  // Phase guidance (luteal)
  lutealTraining: 'मध्यम तीव्रता के साथ निरंतरता बनाए रखें।',
  lutealFasting: 'ल्यूटिअल चरण में यह कठिन हो सकता है; यदि उच्च भूख दिखाई दे तो प्रोटोकॉल संक्षिप्त करें।',
  lutealNutrition: 'स्थिर ऊर्जा के लिए मैग्नीशियम और जटिल कार्बोहाइड्रेट बढ़ाएँ।',
  lutealWeightContext: 'ल्यूटिअल चरण में तरल बनाए रखना और अस्थायी वृद्धि देखना सामान्य है।',
} as const;

export const WorkoutLabels = {
  freesession: 'मुक्त सत्र',
  base: 'आधार',
  building: 'निर्माण',
  consolidation: 'समेकन',
  muscleGroupsFatigued: 'हाल के उच्च भार के साथ ${tired} मांसपेशी समूह हैं।',
  lowerIntensity: 'तीव्रता को कम करना या तकनीकी सत्र चुनना ब्लॉक को तोड़े बिना जारी रखने के लिए लायक है।',
  controlledSession: 'प्रशिक्षण के लिए मार्जिन है, लेकिन एक नियंत्रित सत्र के साथ आप बेहतर प्रदर्शन करेंगे।',
  recordSet: '${exercise} में नया रिकॉर्ड: ${weight} किग्रा',
} as const;

export const TabBarCopy = {
  quickLogHint: 'पानी, वजन, उपवास या नींद रजिस्ट्रेशन के लिए पैनल खोलें।',
} as const;

export const BmiCategories = {
  underweight: 'कम वजन',
  normal: 'सामान्य वजन',
  overweight: 'अधिक वजन',
  obesity: 'मोटापा',
} as const;

export const ComponentMessages = {
  balanceCardNoData: 'VYRA आज का संतुलन, अभी पर्याप्त डेटा नहीं',
  balanceNoData: 'अभी पर्याप्त डेटा नहीं।',
  lastWeight: 'अंतिम वजन',
  noSession: 'कोई सत्र नहीं',
  seriesCount: 'आज सेट',
  isotonic: 'आइसोटोनिक',
  tea: 'चाय',
  coffee: 'कॉफी',
  workoutLogged: 'सत्र दर्ज किया गया',
  syncSlowWarning: 'प्रारंभिक लोड बहुत लंबा था। हमने एक उपयोग योग्य सत्र खोला और आप ऐप को बंद किए बिना पुनः सिंक्रोनाइज़ेशन कर सकते हैं।',
  syncSlowWarning2: 'प्रारंभिक लोड अपेक्षा से अधिक लंबा था। आप सुरक्षित रूप से प्रवेश कर सकते हैं और ऐप से पुनः सिंक्रोनाइज़ेशन कर सकते हैं।',
  autoSessionRecovery: 'आपके सत्र को स्वचालित रूप से पुनः प्राप्त नहीं कर सके। आप ऐप को बंद किए बिना पुनः प्रयास कर सकते हैं।',
  retrySyncPartial: 'आंशिक सिंक्रोनाइज़ेशन दोहराएँ',
  retrySync: 'दोहराएँ',
  maintenanceMessage: 'यदि आप पानी, नींद, वजन, पोषण या कसरत का उपयोग कर रहे थे, तो स्थानीय यहाँ रहता है। केवल सिस्टम के लिए वापस आने और बाकी को संरेखित करना आवश्यक है।',
  authCallbackError: 'प्रदाता ने मान्य सत्र डेटा नहीं दिया।',
  invalidSession: 'कोई सक्रिय सत्र नहीं है।',
  dailyLimitReached: 'दैनिक सीमा पहुँची',
  aiBrainResting: 'मेरा AI मस्तिष्क आराम कर रहा है।',
  systemPrompt: 'हिंदी में संक्षिप्त, व्यावहारिक और सुरक्षित रूप से उत्तर दें।',
} as const;

export const MentalLabels = {
  needSupport: 'आपको समर्थन की आवश्यकता है',
  emotionalTrend: 'हमने भावनात्मक प्रवृत्ति में गिरावट का पता लगाया। आज वसूली और एक छोटी कार्रवाई को प्राथमिकता दें।',
} as const;

export const ReadinessLabels = {
  noConnection: 'अभी बिना कनेक्शन। हम आपकी अंतिम उपलब्ध स्थिति दिखाते हैं।',
  exceptional: 'असाधारण दिन',
  veryGood: 'बहुत अच्छा दिन',
} as const;

export const ReferralMessages = {
  noValidSession: 'अपने निमंत्रण खोलने के लिए आपको एक वैध सत्र की आवश्यकता है।',
  serviceUnavailable: 'रेफरल सेवा अभी उपलब्ध नहीं है। बाद में फिर से कोशिश करें।',
  notConfigured: 'इस निर्माण में रेफरल बैकएंड कॉन्फ़िगर नहीं है।',
  loadFailed: 'आपके निमंत्रण लोड नहीं कर सके।',
  noData: 'रेफरल ने उपयोगी डेटा के बिना उत्तर दिया। कुछ सेकंड में दोबारा कोशिश करें।',
  networkFailed: 'रेफरल सेवा से कनेक्ट नहीं कर सके।',
  notAvailable: 'रेफरल इस निर्माण में उपलब्ध नहीं है।',
  redeemFailed: 'रिडीम नहीं कर सके।',
} as const;

export const NotificationMessages = {
  routineReady: 'आपकी दिनचर्या आज तैयार है',
  movementBlockReady: 'आपकी गति ब्लॉक तैयार है',
  movementBlockCta: 'Vyra खोलें और आज एक छोटी ब्लॉक पूरी करें। लय बनाए रखना सही करने से अधिक मायने रखता है।',
  routineStillOpen: 'आपकी दिनचर्या अभी खुली है',
  routineStillOpenDesc: 'आपके पास ${name} बचा है। आप वापस जा सकते हैं या नोटिफिकेशन से तेज़ी से चिह्नित कर सकते हैं।',
  recommendedRoutineReady: 'आपकी दिनचर्या आज तैयार है',
  recommendedRoutineDesc: '${name} आज अच्छी तरह फिट बैठता है। आप समय बर्बाद किए बिना खोलते या चिह्नित करते हैं।',
  hydrationReminder: '💧 जलयोजन का समय',
  hydrationReminderDesc: '${name}, आप आज अभी भी अपने लक्ष्य के करीब आ सकते हैं।',
  streakAtRisk: '🔥 आपकी श्रृंखला जोखिम में है',
  streakAtRiskDesc: '${name}, आज 1 तेज़ लॉग करें और इसे जीवित रखें।',
  hydrationSmartReminder: '💧 स्मार्ट अनुस्मारक',
  streakSmartReminder: '🔥 श्रृंखला जोखिम में है',
} as const;

export const PrivacyTexts = {
  dataExample: 'पानी, कदम, नींद, वजन, भोजन, उपवास, कसरत और दैनिक सारांश।',
  healthDataReduction: 'कम करें कि वजन, मानसिक स्वास्थ्य और महिला स्वास्थ्य के बारे में कितना स्पष्ट संरक्षित है।',
} as const;

export const ExplorePageStrings = {
  title: 'योजना',
  heroEyebrow: 'सक्रिय लक्ष्य',
  heroBody: 'योजना अब दूसरे होम की तरह काम नहीं करती: यहाँ से आपको अपना रास्ता, अपनी ब्लॉक और अगला उपयोगी कदम दिखना चाहिए।',
  loseFat: 'वसा खोना',
  gainMuscle: 'मांसपेशी प्राप्त करें',
  performance: 'कार्यक्षमता',
  organizeHabits: 'आदतें संगठित करें',
  recovery: 'पुनर्प्राप्ति',
  yourCurrentPath: 'आपका वर्तमान पथ',
  fallbackCoaching: 'इस सप्ताह एक अच्छी तरह से चुनी गई एक निर्णय रखना एक ही समय में दस रास्तों को खोलने से अधिक सुई हिलाता है।',
  recommended: 'आपके लिए अनुशंसित',
  coaching: 'संदर्भ कोचिंग',
  weeklyPriority: 'इस सप्ताह की प्राथमिकता',
  momentum: 'चुनौतियाँ और गति',
  streakLabel: 'श्रृंखला',
  sessionThisWeek: 'सत्र सप्ताह',
  usefulLibrary: 'उपयोगी पुस्तकालय',
  // Program section
  programTitle: 'सक्रिय कार्यक्रम',
  noneSelected: 'अभी तक कोई कार्यक्रम चुना नहीं गया',
  activeWeek: 'सप्ताह {{week}}. ब्लॉक पहले से चल रहा है और अगला निर्णय यहाँ से निकलना चाहिए।',
  suggested: 'कोई सक्रिय कार्यक्रम नहीं है, लेकिन दिशा के साथ शुरू करने के लिए पहले से एक सुझाई गई दिनचर्या है।',
  chooseRoute: 'अभी सर्वश्रेष्ठ पूरी सूची के माध्यम से नेविगेट करने के बजाय निर्देशित मार्ग चुनना है।',
  nextAction: 'अगली कार्रवाई',
  backToSession: 'सत्र पर वापस जाएँ',
  chooseProgram: 'कार्यक्रम चुनें',
  progress: 'प्रगति',
  thisWeek: '{{sessions}}/{{goal}} इस सप्ताह',
  continueProgram: 'कार्यक्रम जारी रखें',
  // Cards
  nextFocusEyebrow: 'अगली समायोजन',
  nextFocusBody: 'आज की संदर्भ पढ़ना पहले अधिकतम धक्का देने के लिए क्या पाया है।',
  workoutEyebrow: 'कसरत',
  openCurrent: 'अपनी वर्तमान ब्लॉक खोलें',
  chooseGuided: 'निर्देशित कार्यक्रम चुनें',
  workoutOpenBody: 'मुख्य पथ से बाहर जाए बिना सप्ताह, दिन और लोड निरंतरता की समीक्षा करें।',
  workoutChooseBody: 'बिना प्राथमिकता के ढीले दिनचर्या के माध्यम से नेविगेट करने के बजाय स्पष्ट मार्ग से शुरू करें।',
  nutritionEyebrow: 'पोषण',
  nutritionTitle: 'सरल पोषण पुनः सेट',
  nutritionBody: 'एक अच्छी तरह से दर्ज किया गया दिन एक जटिल स्प्रेडशीट से अधिक लायक है जिसे आप उपयोग नहीं करते।',
  recoveryEyebrow: 'पुनर्प्राप्ति',
  sleepTitle: 'इस सप्ताह बेहतर सो',
  sleepBody: 'दिन के लिए अधिक शक्ति और अधिक निरंतरता माँगने से पहले आराम को समायोजित करें।',
  waterTitle: 'जलयोजन दिनचर्या',
  waterBody: 'पानी का सरल आधार और दैनिक लय बाकी सिस्टम को बेहतर प्रदर्शन करने में मदद करता है।',
  libraryEyebrow: 'उपयोगी पुस्तकालय',
  plannerTitle: 'साप्ताहिक योजना',
  plannerBody: 'सप्ताह की कल्पना करें और अतिरिक्त मॉड्यूल खोले बिना अगली ब्लॉक तैयार करें।',
  mealTitle: 'भोजन रजिस्ट्रेशन',
  mealBody: 'बुनियादी बातों पर वापस जाएँ और दो चरणों में दिन को स्पष्ट करें।',
  sleepLibraryTitle: 'आराम देखो',
  sleepLibraryBody: 'पिछली रात पढ़ें और अधिक मानदंड के साथ भार कम या बढ़ाएँ।',
  progressTitle: 'वास्तविक प्रगति पढ़ें',
  progressBody: 'यदि आप गहरी संदर्भ चाहते हैं, यहाँ आप प्रवृत्ति देखते हैं केवल ढीले रजिस्ट्रेशन नहीं।',
  milestoneDone: 'सप्ताह निर्देशित। अब ब्लॉक की गुणवत्ता रखने और शोर न जोड़ने का समय।',
  milestonePending: 'आपके साप्ताहिक लक्ष्य को बंद करने के लिए {{count}} सत्रों की आवश्यकता है।',
} as const;

export const HomePageStrings = {
  locale: 'hi-IN',
  guestName: 'उपयोगकर्ता',
  quickActionHint: 'इस त्वरित लिंक को खोलें।',
  secondaryModuleHint: 'इस माध्यमिक मॉड्यूल को खोलें।',
  notificationFallbackTitle: 'Vyra अधिसूचना',
  notificationFallbackBody: 'हाल की गतिविधि उपलब्ध है।',
  greeting: 'नमस्ते, {{name}}',
  streakPillLabel: (days: number) => `वर्तमान श्रृंखला: ${days} ${days === 1 ? 'दिन' : 'दिन'}`,
  streakPillHint: 'अपनी निरंतरता देखने के लिए प्रगति खोलें।',
  openNotifications: 'हाल की अधिसूचनाएँ खोलें',
  openNotificationsHint: 'वितरण नियंत्रण और हाल के चेतावनियाँ दिखाता है।',
  openQuickLog: 'त्वरित लॉग खोलें',
  openQuickLogHint: 'शुरुआत से बाहर जाए बिना पानी, नींद, वजन या उपवास रजिस्ट्रेशन के लिए शीट खोलें।',
  openProfile: 'प्रोफ़ाइल खोलें',
  openProfileHint: 'अपना खाता, मॉड्यूल और सेटिंग्स खोलें।',
  activeWorkoutAccessibility: 'सक्रिय सत्र, {{name}}, {{count}} व्यायाम चल रहे हैं',
  activeWorkoutEyebrow: 'सक्रिय सत्र',
  activeWorkoutFallbackTitle: 'कसरत चल रही है',
  activeWorkoutMeta: 'इस डिवाइस पर {{count}} व्यायाम चल रहे हैं।',
  activeWorkoutCta: 'कसरत पर वापस जाएँ',
  nextStepEyebrow: 'अगला कदम',
  nextStepHint: 'वह मोर्चा चुनें जो आपके दिन को सबसे ज़्यादा हिलाता है और इसे यहाँ से हल करें।',
  planEyebrow: 'आज',
  planTitle: 'दिन की योजना',
  planSummary: '{{done}} का {{total}} मोर्चे पहले से ही कवर हैं।',
  planExpand: 'पूरी योजना देखो',
  planCollapse: 'कम दिखाएँ',
  momentumEyebrow: 'निरंतरता',
  streakEyebrow: 'श्रृंखला',
  streakStartToday: 'आज अपनी श्रृंखला शुरू करें',
  streakRunning: (days: number) => `${days} ${days === 1 ? 'दिन' : 'दिन'} श्रृंखला में`,
  streakDoneBody: 'आज गिनती। एक छोटी कार्रवाई रखना आपकी निरंतरता को बनाए रखता है।',
  streakPendingBody: 'आपको दिन बचाने के लिए बस पानी, कदम, पोषण या कसरत की आवश्यकता है।',
  streakView: 'श्रृंखला और प्रगति देखो',
  streakSave: 'अभी मेरी श्रृंखला बचाएँ',
  sectionsQuickActions: 'तेज़ कार्रवाई',
  sectionsThisWeek: 'इस सप्ताह',
  weekDone: '{{day}}: इस सप्ताह पूरा दिन',
  weekTodayPending: '{{day}}: आज अभी बाकी है',
  weekPending: '{{day}}: अधूरा',
  weekSummary: 'इस सप्ताह {{count}} का 7 दिन',
  pauseBody: 'आप {{days}} दिन बिना रजिस्ट्रेशन के हैं। कुछ छोटे के साथ आज फिर से शुरू करें।',
  pauseCta: 'अभी फिर से शुरू करें',
  pauseHint: 'गतिविधि रजिस्ट्रेशन पर वापस जाने के लिए सुझाई गई कार्रवाई खोलें।',
  aiEyebrow: 'VYRA सुझाव देता है',
  notificationsTitle: 'हाल की अधिसूचनाएँ',
  notificationsEmpty: 'यहाँ अभी दिखाने के लिए हाल की गतिविधि नहीं है।',
  notificationsViewAll: 'सब देखो',
  notificationsAccessibility: 'सभी अधिसूचनाएँ देखो',
  notificationsHint: 'अधिसूचना वितरण नियंत्रण और मूक घंटे खोलें।',
} as const;

export const ProgressPageStrings = {
  sectionEnergy: 'ऊर्जा और वजन',
  sectionEnergyHint: 'महत्वपूर्ण बात आपके द्वारा चुने गए लक्ष्य के अनुसार बदलती है।',
  workoutSessions: 'सत्र',
  sleepRecovered: 'आज सामान्य भार को बनाए रखने के लिए ठोस आधार।',
  sleepRecovering: 'आप आदर्श से कम सोए। तीव्रता को मॉड्यूल करना लायक है।',
  muscleChest: 'छाती',
  muscleBack: 'पीठ',
  muscleShoulders: 'कंधे',
  muscleArms: 'बाहें',
  muscleCore: 'कोर',
  muscleLegs: 'पैर',
  caloriesEyebrow: 'आज कैलोरी',
  weightEyebrow: 'वजन और दिशा',
  viewPrograms: 'कार्यक्रम देखो',
  backHome: 'घर वापस जाएँ',
} as const;

export const WaterHydrationMessages = {
  goalReached: 'लक्ष्य बंद। इस सरल पैटर्न को रखना ही है जो मॉड्यूल को बनाए रखता है।',
  behindAndAfternoon: 'बहुत सारा दिन पहले से ही चला गया। दो लगातार रजिस्ट्रेशन अभी पूरी तरह बंद को बदल देते हैं।',
  lowProgress: 'जटिलता जोड़े बिना लय को पुनः प्राप्त करने के लिए अभी भी मार्जिन है।',
  onTrack: 'आप अच्छी तरह चल रहे हैं। छोटे कप को दूरी पर रखना सब कुछ अंत में ढेर करने से अधिक लायक है।',
} as const;

export const StepsProgressMessages = {
  goalMet: 'आपने अपना लक्ष्य पार किया या पूरा किया। आज {{totalSteps}} कदम।',
  almostThere: 'लगभग। आपको लक्ष्य के लिए {{remaining}} कदमों की आवश्यकता है।',
  goodProgress: 'आप अच्छी तरह चल रहे हैं। आपने पहले से ही दिन को बेहतर तरीके से समाप्त करने के लिए लय ली है।',
  justStarted: 'अच्छी शुरुआत। योग करते रहो।',
} as const;

export const HomeDetailStrings = {
  hero: {
    readiness: {
      eyebrow: 'तैयारी',
      pending: 'आज का आधार',
      awaiting: 'निर्माण में पढ़ना',
      support: 'नींद, पानी, भोजन और गति के साथ यह स्कोर अधिक सटीक हो जाता है।',
      noData: 'हम अभी भी आपकी दैनिक पढ़ना बना रहे हैं। प्रत्येक उपयोगी रजिस्ट्रेशन इसे अधिक संदर्भ देता है।',
      weeklyAverage: 'औसत',
      projected: 'संभावित बंद',
      stability: 'स्थिरता',
      focus: 'अभी फोकस',
      cta: 'विवरण देखो',
    },
    fasting: {
      eyebrow: 'सक्रिय उपवास',
      protocol: 'प्रोटोकॉल {{protocol}}',
      eatingWindowOpen: 'खाने की खिड़की खुली',
      accumulated: '{{hours}}ह {{minutes}}म जमा।',
      close: 'उपवास बंद करें',
      complete: 'उपवास पूरा करें',
    },
    female: {
      eyebrow: 'चक्र',
      phaseDay: 'चरण {{phase}} · दिन {{day}}',
      prioritizeRecovery: 'वसूली और नियमितता को प्राथमिकता दें',
      trainStrong: 'मजबूत प्रशिक्षण के लिए अच्छा दिन',
      registerToday: 'आज रजिस्ट्रेशन करें',
    },
    nutrition: {
      eyebrow: 'पोषण',
      percentCalories: 'आज {{pct}}% कैलोरी',
      caloriesOf: '{{current}} का {{target}} kcal',
      cta: 'भोजन रजिस्ट्रेशन करें',
    },
    steps: {
      eyebrow: 'कदम',
      title: 'आज का लक्ष्य',
      ofSteps: '{{goal}} कदमों के',
      estimatedCalories: '{{kcal}} kcal अनुमानित।',
      cta: 'विवरण देखो',
    },
    sleep: {
      eyebrow: 'नींद',
      recovered: 'आज सामान्य भार को बनाए रखने के लिए ठोस आधार।',
      recovering: 'आप आदर्श से कम सोए। तीव्रता को मॉड्यूल करना लायक है।',
      view: 'नींद देखो',
      log: 'नींद रजिस्ट्रेशन करें',
    },
    workoutRest: {
      eyebrow: 'आज · आराम',
      fallbackTitle: 'सक्रिय वसूली',
      body: 'आज भार कम करना लायक है। आप जल्दबाज़ी के बिना ब्लॉक के अगले सत्र की जाँच कर सकते हैं।',
      cta: 'कल देखो',
    },
    workout: {
      eyebrow: 'आज',
      activeFallback: 'सत्र चल रहा है',
      idleFallback: 'आज कसरत करें',
      prYesterday: 'PR कल',
      activeMeta: '{{count}} व्यायाम · सत्र खुला',
      routineMeta: '{{count}} व्यायाम · ~{{minutes}} मिनट',
      emptyMeta: 'आज के लिए अभी तक कोई दिनचर्या तैयार नहीं है।',
      resume: 'कसरत पर वापस जाएँ',
      trainNow: 'अभी कसरत करें',
    },
  },
  workoutProgram: {
    week: 'सप्ताह {{week}} · {{day}}',
    progress: 'ब्लॉक का {{pct}}%',
    todayRoutine: '{{day}} · दिन की दिनचर्या',
    nextSuggestion: '{{day}} · अगली सलाह',
    active: 'सक्रिय सत्र',
    exercises: '{{count}} व्यायाम',
  },
  metrics: {
    waterGoal: 'लक्ष्य का {{pct}}%',
    sleepBelowGoal: 'लक्ष्य के नीचे',
    steps: '{{pct}}% · {{kcal}} kcal',
    noTrend: 'अभी तक छोटा प्रवृत्ति',
    weeklyTrend: '{{sign}}{{value}} इस सप्ताह',
  },
  quickActions: {
    logMeal: 'भोजन रजिस्ट्रेशन करें',
    addWater: 'पानी जोड़ें',
    resumeWorkout: 'कसरत पर वापस जाएँ',
    trainNow: 'अभी कसरत करें',
    logSleep: 'नींद रजिस्ट्रेशन करें',
    openQuickLog: 'त्वरित लॉग खोलें',
  },
} as const;

export const ForgotPasswordStrings = {
  title: 'अपनी पहुँच पुनः प्राप्त करें',
  subtitle: 'अपनी ईमेल दर्ज करें और हम निर्देश भेजेंगे।',
  send: 'निर्देश भेजें',
  sendFailed: 'ईमेल भेज नहीं सके। पता जाँचें और फिर से कोशिश करें।',
  successTitle: 'अपने इनबॉक्स की जाँच करें',
  successBody: 'यदि आप नहीं देखते तो स्पैम की जाँच भी करें।',
  resend: 'फिर से भेजें',
  resendIn: (seconds: number) => `${seconds}सेकंड में फिर से भेजें`,
  resendA11y: (seconds: number) =>
    seconds > 0 ? `${seconds} सेकंड में फिर से भेजें` : 'ईमेल फिर से भेजें',
  resendHint: 'पुनः प्राप्ति ईमेल फिर से भेजें।',
} as const;

export const FastingMetabolicZones = {
  fed: {
    label: 'संतुष्ट',
    description: 'पाचन और अंतिम भोजन के पास अभी भी ऊर्जा।',
  },
  early: {
    label: 'अनुकूलन',
    description: 'ऊर्जा आसानी से गिरना शुरू करती है और शरीर स्रोत बदलता है।',
  },
  fat: {
    label: 'वसा जलना',
    description: 'मुख्य ईंधन के रूप में वसा का उपयोग करना आसान हो जाता है।',
  },
  ketosis: {
    label: 'कीटोसिस',
    description: 'कीटोसिस सिग्नल पहले से ही काफी स्पष्ट दिख रहा है।',
  },
  autophagy: {
    label: 'आटोफेजी',
    description: 'उन्नत खिड़की। यहाँ संदर्भ और वसूली अधिक मायने रखता है।',
  },
} as const;

export const BiometricLabels = {
  promptMessage: 'Vyra को अनलॉक करें',
  cancelLabel: 'रद्द करें',
  fallbackLabel: 'डिवाइस लॉक का उपयोग करें',
  unlockButton: 'अनलॉक करें',
  verifyingButton: 'सत्यापन...',
  logoutHint: 'ऐप को अनलॉक किए बिना वर्तमान सत्र बंद करें।',
  accessibilityLabel: 'Vyra को अनलॉक करें',
} as const;

export const FemaleSymptoms = {
  colicos: 'ऐंठन',
  hinchazon: 'सूजन',
  fatiga: 'थकान',
  migrana: 'माइग्रेन',
  cambios_humor: 'मूड में बदलाव',
  energia_alta: 'उच्च ऊर्जा',
} as const;

export const NutritionModule = {
  headerEditPrefix: 'संपादित',
  headerAddPrefix: 'को जोड़ें',
  editingMode: {
    title: 'रजिस्ट्रेशन संपादन',
    description: 'नाम, ग्राम या मैक्रो को समायोजित करें और मूल रजिस्ट्रेशन को हटाए बिना परिवर्तन को सहेजें।',
  },
  logModes: {
    search: 'खोजें',
    photo: 'फ़ोटो',
    barcode: 'कोड',
    manual: 'मैनुअल',
  },
  library: {
    title: 'त्वरित पुस्तकालय',
    description: 'अक्सर कुछ खोलें या खोज से पहले हाल की रजिस्ट्रेशन पुनः प्राप्त करें।',
    tabs: {
      frequent: 'बार-बार',
      recent: 'हाल ही का',
    },
    itemA11y: (food: string) => `${food} का उपयोग करें`,
    itemHint: 'मात्रा और मैक्रो की पुष्टि करने के लिए इस भोजन को लोड करें।',
    emptyFrequent: 'आपके पसंदीदा खाद्य पदार्थ यहाँ दिखाई देंगे।',
    emptyRecent: 'आपके हाल के भोजन यहाँ दिखाई देंगे।',
  },
  search: {
    label: 'भोजन खोजें',
    placeholder: 'पूर्व: चावल, दही, चिकन...',
    searching: 'खाद्य पदार्थ खोज रहा है...',
    libraryMatches: 'पहले से ही आपके पुस्तकालय में',
    libraryDescription: 'लंबी सूची खोलने से पहले, मैं पहले मेल दिखाता हूँ जो आपने पहले से ही उपयोग किए हैं।',
    recentLabel: (timestamp: string) => `${timestamp}`,
    generalResults: 'सामान्य परिणाम',
    resultsCount: (count: number) => {
      if (count >= 30) return `पहले ${count} परिणाम दिखाए गए। यदि आप जो खोज रहे हैं वह नहीं दिख रहा है, तो अधिक परिणाम खोलें या मैनुअल लोड का उपयोग करें।`;
      return `हमने इस खोज के लिए ${count} मिलान${count === 1 ? '' : 'ें'} पाए।`;
    },
    noResults: (query: string) => `"${query}" के लिए खाद्य पदार्थ नहीं मिले। आप फिर से कोशिश कर सकते हैं या मैनुअल रूप से लोड कर सकते हैं।`,
    noResultsLibrary: (query: string) => `"${query}" के लिए सामान्य परिणाम नहीं मिले। यदि आपने पहले इसका उपयोग किया है, तो आपके पास ऊपर मेल हैं या आप मैनुअल रूप से लोड कर सकते हैं।`,
    loadManual: 'मैनुअल लोड करें',
    moreResults: 'अधिक परिणाम देखो',
  },
  preview: {
    title: 'पुष्टिकरण',
    hint: 'जोड़ने से पहले मैक्रो और मात्रा की पुष्टि करें।',
    macros: {
      kcal: 'Kcal',
      protein: 'प्रोटीन',
      carbs: 'कार्ब्स',
      fat: 'वसा',
      fiber: 'फाइबर',
    },
    quantityLabel: 'मात्रा',
    portionHint: '1 हिस्सा इस पुष्टिकरण के लिए 100 ग्राम के रूप में अनुमानित है।',
    addButton: (meal: string) => `${meal} को जोड़ें`,
  },
  photo: {
    title: 'AI फ़ोटो',
    description: 'फ़ोटो लें, VYRA को पुष्टि करने से पहले क्या पता चला है यह देखें और हिस्से को समायोजित करें।',
    takePhoto: 'फ़ोटो लें',
    chooseGallery: 'गैलरी से चुनें',
    detection: 'यह AI ने पता लगाया',
    confidence: (percent: number) => `आत्मविश्वास ${Math.round(percent * 100)}%`,
    lowConfidence: 'पता लगाने में कम आत्मविश्वास है। यह जाँच करने या मैनुअल खोज पर जाने के लिए लायक है।',
    itemsSelected: (count: number) => `${count} आइटम${count > 1 ? 's' : ''} चिह्नित।`,
    selectAtLeast: 'पुष्टि करने के लिए कम से कम एक आइटम चिह्नित करें।',
    confirmDetection: 'पता लगाव की पुष्टि करें',
    manualSearch: 'मैनुअल खोजें',
    togglePortions: {
      show: 'हिस्से समायोजित करें',
      hide: 'हिस्से समायोजन छिपाएँ',
    },
    estimated: (grams: number) => `${Math.round(grams)} ग्राम अनुमानित`,
    noQuantity: 'कोई अनुमानित मात्रा नहीं',
    componentIncludeA11y: (name: string) => `${name} शामिल करें`,
    cameraMissingPermission: 'कैमरा अनुमति आवश्यक है।',
    galleryMissingPermission: 'गैलरी अनुमति आवश्यक है।',
  },
  manual: {
    title: 'मैनुअल लोड',
    nameLabel: 'नाम',
    namePlaceholder: 'पूर्व: चावल और चिकन',
    quantityLabel: 'मात्रा',
    quantityUnit: 'ग्राम',
    proteinLabel: 'प्रोटीन',
    proteinUnit: 'ग्राम',
    carbsLabel: 'कार्बोहाइड्रेट',
    carbsUnit: 'ग्राम',
    fatLabel: 'वसा',
    fatUnit: 'ग्राम',
    fiberLabel: 'फाइबर',
    fiberUnit: 'ग्राम',
    submitEdit: 'परिवर्तन सहेजें',
    submitAdd: (meal: string) => `${meal} को जोड़ें`,
  },
  errors: {
    loadingFood: 'भोजन लोड हो रहा है...',
  },
  modeA11y: (mode: string) => `मोड ${mode === 'search' ? 'खोजें' : mode === 'photo' ? 'फ़ोटो' : mode === 'barcode' ? 'कोड' : 'मैनुअल'}`,
  unitA11y: (unit: string) => `इकाई ${unit}`,
  quickAmountA11y: (value: number) => `त्वरित मात्रा ${value} ग्राम`,
  portionAdjustmentNote: 'हमने पुष्टि से पहले आपके द्वारा चिह्नित आइटमों के अनुसार हिस्से को समायोजित किया।',
} as const;

export const FemaleModule = {
  header: {
    title: 'चक्र समायोजन',
    subtitle: 'मॉड्यूल, गोपनीयता और ट्रैकिंग निरंतरता।',
  },
  disclaimer: {
    title: 'चिकित्सा अस्वीकरण लंबित',
    body: 'इसे दैनिक संदर्भ के रूप में मॉड्यूल का उपयोग करने से पहले पुष्टि करना लायक है।',
    confirm: 'अस्वीकरण की पुष्टि करें',
  },
  errorCard: {
    title: 'हम इस परिवर्तन को सहेज नहीं सके',
  },
  moduleSection: {
    eyebrow: 'मॉड्यूल',
    title: 'संवेदनशील और वैकल्पिक ट्रैकिंग',
    subtitle: 'यदि आप सक्रिय करते हैं, तो VYRA आपके चरण के अनुसार कसरत, पोषण और वसूली संदर्भ को समायोजित कर सकता है।',
    toggleLabel: 'मॉड्यूल सक्रिय',
    toggleDescription: 'अपनी सेटिंग्स से बाहर जाए बिना चक्र पढ़ने को सक्रिय या रोकें।',
  },
  cycleData: {
    eyebrow: 'आधार डेटा',
    title: 'चक्र सारांश',
    subtitle: 'मुख्य पढ़ना स्पष्ट पंक्तियों में यहाँ रहता है और संपादन एक समर्पित स्क्रीन पर रहता है।',
    lastPeriod: 'अंतिम अवधि',
    unconfigured: 'असंरचित',
    cycleDuration: 'चक्र की अवधि',
    daysLabel: 'दिन',
    periodDuration: 'मासिक धर्म की अवधि',
    nextPeriod: 'अगली अवधि',
    editLink: 'चक्र डेटा संपादित करें',
    editDescription: 'तारीखें, अवधि और संदर्भ रजिस्ट्रेशन के लिए मॉड्यूल का आधार कॉन्फ़िगरेशन खोलें।',
  },
  errors: {
    saveFailed: 'यह सेटिंग अभी सहेज नहीं सकते। कुछ सेकंड में फिर से कोशिश करें।',
    configSaveFailed: 'चक्र कॉन्फ़िगरेशन सहेज नहीं सकते।',
  },
} as const;

export const FastingModule = {
  header: {
    title: 'अंतराल उपवास',
  },
  controls: {
    adjustTime: '⏱  शुरुआत का समय समायोजित करें',
    cancelAdjust: '✕  समायोजन रद्द करें',
    adjustHint: 'रद्द करने पर वर्तमान समय का उपयोग किया जाएगा',
    adjustSubHint: 'यदि आपने पहले से शुरू किया है या बाद में शुरू करेंगे',
    adjustTitle: 'आपने किस समय शुरू किया (या शुरू करेंगे)?',
    reduceOffset: '15 मिनट कम करें',
    increaseOffset: '15 मिनट जोड़ें',
    offsetHint: 'प्रत्येक टच 15 मिनट चलता है · 12 घंटे तक या 4 घंटे आगे',
    now: 'अभी',
  },
  timer: {
    remaining: 'बाकी',
    elapsedPct: (elapsed: string, pct: number) => `${elapsed} पूरा · ${Math.round(pct)}%`,
    backgroundActive: 'टाइमर पृष्ठभूमि में सक्रिय रहता है।',
    endPredictionSameDay: (time: string) => `${time} पर समाप्त`,
    endPredictionDiffDay: (time: string, date: string) => `${time} पर समाप्त · ${date}`,
    zones: 'मेटाबोलिक ज़ोन',
  },
  states: {
    activeBadge: 'सक्रिय उपवास',
    completeBadge: 'उपवास पूरा',
    completeEmoji: '🎉',
    completeTitle: 'आपने यह किया!',
    completeMeta: (protocol: string, elapsed: string) => `${protocol} · ${elapsed} पूरा`,
  },
  suggestion: {
    title: 'आज लायक है',
  },
  buttons: {
    startFast: (protocol: string, timeLabel?: string) => 
      timeLabel ? `${protocol} शुरू करें · ${timeLabel}` : `${protocol} शुरू करें`,
    completeFast: 'उपवास पूरा करें',
    finishAndClose: 'रजिस्ट्रेशन और बंद करो',
    earlyFinish: 'जल्दी समाप्त करें',
    continueEarlyFinish: 'उपवास जारी रखें',
    partialFinish: 'आंशिक समाप्त करें',
  },
  stats: {
    completedLabel: 'पूरा',
    avgLabel: 'औसत',
    longestLabel: 'सबसे लंबा',
    completedMeta: (avg: number, longest: number) => `औसत ${avg.toFixed(1)}घ · सर्वश्रेष्ठ ${longest.toFixed(1)}घ`,
    noFasts: 'अभी तक कोई उपवास पूरा नहीं हुआ।',
  },
  history: {
    title: 'हाल के उपवास',
    missed: 'मिस',
    pending: 'लंबित',
    completed: '✓',
    deleteBtn: 'हटाएँ',
    deleteA11y: (protocol: string) => `${protocol} उपवास हटाएँ`,
    emptyEmoji: '🌙',
    emptyTitle: 'अभी तक कोई उपवास रजिस्ट्रेशन नहीं।',
    emptyHint: 'अपना पहला उपवास पूरा करें यहाँ इतिहास देखने के लिए।',
  },
  fiveTwo: {
    header: '📅 आज आपका 5:2 दिन है',
    status: 'लंबित',
    desc: (protocol: string, hours: number, time?: string) => 
      time ? `प्रोटोकॉल: ${protocol} · लक्ष्य: ${hours}घ · अनुसूचित समय: ${time}` : `प्रोटोकॉल: ${protocol} · लक्ष्य: ${hours}घ`,
    button: 'आज का 5:2 उपवास शुरू करें',
    week: 'इस सप्ताह · 5:2',
    weekMeta: (completed: number, target: number) => `${completed}/${target} दिन पूरा`,
  },
  modals: {
    zoneDetail: {
      startHint: (hours: number) => `यह ज़ोन ${hours}घ उपवास पर शुरू होता है।`,
      close: 'बंद करें',
    },
    deleteConfirm: {
      title: 'उपवास हटाएँ',
      body: 'यह उपवास हटाएँ? यह कार्रवाई अनुमत नहीं है।',
      confirm: 'हटाएँ',
    },
    earlyFinish: {
      title: 'जल्दी समाप्त करें?',
      percentComplete: (pct: number) => `${Math.round(pct)}%`,
      label: 'पूरा',
      context: (elapsed: string) => `आपके पास ${elapsed} लक्ष्य है। आंशिक के रूप में रजिस्ट्रेशन किया जाएगा।`,
    },
  },
  contextCard: {
    female: 'महिला संदर्भ',
  },
  offsetLabel: {
    now: (time: string) => `अभी · ${time}`,
    past: (duration: string, time: string, dayLabel?: string) => `${duration} पहले${dayLabel ? ` · ${dayLabel}` : ''} · ${time}`,
    future: (duration: string, time: string) => `में ${duration} · ${time}`,
  },
} as const;

export const WaterModule = {
  header: {
    eyebrow: 'सेटिंग्स',
    title: 'पानी',
  },
  dailyGoal: {
    title: 'दैनिक लक्ष्य',
    description: 'एक यथार्थवादी आधार चुनें और संदर्भ के अनुसार इसे समायोजित करने के लिए ऐप दें।',
    presets: {
      low: 'कम गतिविधि',
      moderate: 'मध्यम',
      recommended: 'अनुशंसित',
      athlete: 'एथलीट',
      hotClimate: 'गर्म जलवायु',
    },
    customLabel: 'अनुकूलित लक्ष्य',
    customHint: '500 मिली और 10,000 मिली के बीच।',
    unit: 'मिली',
  },
  infoCard: {
    eyebrow: 'समायोजन',
    body: 'यदि गर्म है, यदि आप उपवास कर रहे हैं, या यदि दिन में बहुत सारी गतिविधि है तो VYRA आपके लक्ष्य को बढ़ा सकता है।',
  },
  containers: {
    title: 'तेज़ ऑब्जेक्ट',
    description: 'एक बार समायोजित करें कि आपके वास्तविक कंटेनर में कितना है।',
    resetLabel: 'रीसेट करें',
    resetA11y: 'डिफ़ॉल्ट आकार पुनः स्थापित करें',
    glass: 'एक ग्लास',
    largeGlass: 'बड़ा ग्लास',
    bottle: 'बोतल',
  },
  warningCard: {
    eyebrow: 'चेतावनी',
    body: 'अनुस्मारक सामान्य सूचनाओं में रहते हैं। यहाँ आप केवल परिचालन भाग को ठीक करते हैं।',
  },
  buttons: {
    openNotifications: 'सूचनाएँ खोलें',
    changeUnits: 'इकाइयाँ बदलें',
  },
} as const;
