export const ShellStrings = {
  loadingMessage: 'Laddar...',
  errorOccurred: 'Ett fel inträffade.',
  tryAgain: 'Försök igen',
  ok: 'OK',
  cancel: 'Avbryt',
  delete: 'Radera',
  confirm: 'Bekräfta',
  close: 'Stäng',
  back: 'Tillbaka',
  next: 'Nästa',
  save: 'Spara',
  search: 'Sök',
  settings: 'Inställningar',
  help: 'Hjälp',
  about: 'Om',
  logout: 'Logga ut',
  login: 'Logga in',
  register: 'Registrera',
  profile: 'Profil',
  menu: 'Meny',
  notification: 'Avisering',
  edit: 'Redigera',
  add: 'Lägg till',
  remove: 'Ta bort',
  select: 'Välj',
  copy: 'Kopiera',
  share: 'Dela',
  download: 'Ladda ner',
  upload: 'Ladda upp',
  submit: 'Skicka',
  reset: 'Återställ',
  apply: 'Tillämpa',
  filter: 'Filtrera',
  sort: 'Sortera',
  view: 'Visa',
  hide: 'Dölj',
  show: 'Visa',
  expand: 'Expandera',
  collapse: 'Dölj',
} as const;
