import type { Exercise, Routine, WorkoutProgram } from '@/lib/workout-types';

export const WORKOUT_CATALOG_VERSION = 5;

function exercise(input: Exercise): Exercise {
  return input;
}

function routineExercise(
  exercise_id: string,
  exercise_name: string,
  sets_target: number,
  reps_target: number,
  weight_suggestion_kg: number,
  order: number,
  rest_seconds: number,
  notes?: string,
) {
  return {
    exercise_id,
    exercise_name,
    sets_target,
    reps_target,
    weight_suggestion_kg,
    order,
    rest_seconds,
    notes: notes ?? null,
  };
}

function seedRoutine(input: Routine): Routine {
  return {
    ...input,
    source: input.source ?? 'seed',
    user_id: input.user_id ?? null,
  };
}

function workoutProgram(input: WorkoutProgram): WorkoutProgram {
  return {
    ...input,
    source: input.source ?? 'catalog',
  };
}

export const GENERATED_WORKOUT_EXERCISES: Exercise[] = [
  exercise({
    id: '6fab3ac3-aa88-5970-921e-651b2ffa095a',
    slug: 'sentadilla_con_barra',
    name: 'Sentadilla con barra',
    muscle_group: 'Piernas',
    muscles_secondary: ['Glúteos', 'Core'],
    equipment: 'Barra',
    instructions: 'Baja con control, brace firme y recorrido estable.',
    movement_pattern: 'Dominante de rodilla',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Base principal para fuerza de piernas.',
  }),
  exercise({
    id: '4dbd0202-6649-54a3-95ca-d437d3b3c56a',
    slug: 'press_de_banca_con_barra',
    name: 'Press de banca con barra',
    muscle_group: 'Pecho',
    muscles_secondary: ['Tríceps', 'Hombros'],
    equipment: 'Barra',
    instructions: 'Escápulas activas, pies firmes y empuje limpio.',
    movement_pattern: 'Empuje horizontal',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Empuje principal para torso.',
  }),
  exercise({
    id: '45f587b5-9858-5513-b305-277e072b99d8',
    slug: 'remo_con_barra',
    name: 'Remo con barra',
    muscle_group: 'Espalda',
    muscles_secondary: ['Bíceps', 'Hombros'],
    equipment: 'Barra',
    instructions: 'Torso estable y tirón hacia la cintura.',
    movement_pattern: 'Tirón horizontal',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Tirón básico para espalda media.',
  }),
  exercise({
    id: 'abee45f4-b1ce-5220-bbd7-21211759d1f5',
    slug: 'plancha_frontal',
    name: 'Plancha frontal',
    muscle_group: 'Core',
    muscles_secondary: ['Hombros'],
    equipment: 'Peso corporal',
    instructions: 'Mantén pelvis neutra y respiración controlada.',
    movement_pattern: 'Estabilidad',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Base simple de control lumbopélvico.',
  }),
  exercise({
    id: 'c0af26a4-16cc-5bb3-b42f-e3c91e8324f6',
    slug: 'peso_muerto_con_barra',
    name: 'Peso muerto con barra',
    muscle_group: 'Piernas',
    muscles_secondary: ['Glúteos', 'Espalda', 'Core'],
    equipment: 'Barra',
    instructions: 'Barra cerca del cuerpo y espalda neutra.',
    movement_pattern: 'Bisagra',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Bisagra pesada de cadena posterior.',
  }),
  exercise({
    id: '2a3336e2-6165-5a88-90b9-6c1737220f9a',
    slug: 'press_militar_con_barra',
    name: 'Press militar con barra',
    muscle_group: 'Hombros',
    muscles_secondary: ['Tríceps', 'Core'],
    equipment: 'Barra',
    instructions: 'Empuja vertical con abdomen y glúteos firmes.',
    movement_pattern: 'Empuje vertical',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Empuje vertical principal.',
  }),
  exercise({
    id: 'dd99446f-63f1-54bb-aab6-15b443490678',
    slug: 'jalon_al_pecho_pronado',
    name: 'Jalón al pecho pronado',
    muscle_group: 'Espalda',
    muscles_secondary: ['Bíceps'],
    equipment: 'Máquina',
    instructions: 'Tira al pecho sin cerrar los hombros.',
    movement_pattern: 'Tirón vertical',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Alternativa guiada al patrón de dominada.',
  }),
  exercise({
    id: '1bb29304-beb8-5403-a18f-0e1727c87c49',
    slug: 'dead_bug_estandar',
    name: 'Dead bug estándar',
    muscle_group: 'Core',
    muscles_secondary: ['Cadera'],
    equipment: 'Peso corporal',
    instructions: 'Espalda baja pegada al suelo en todo momento.',
    movement_pattern: 'Estabilidad',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Control de centro y respiración.',
  }),
  exercise({
    id: 'bece1220-5689-5f42-b8b9-429e2b7b6135',
    slug: 'sentadilla_goblet',
    name: 'Sentadilla goblet',
    muscle_group: 'Piernas',
    muscles_secondary: ['Glúteos', 'Core'],
    equipment: 'Mancuernas',
    instructions: 'Pecho abierto y recorrido estable.',
    movement_pattern: 'Dominante de rodilla',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Variante simple y estable para piernas.',
  }),
  exercise({
    id: '41f00082-74b2-5b36-9533-db311c9bbf7a',
    slug: 'press_inclinado_con_mancuernas',
    name: 'Press inclinado con mancuernas',
    muscle_group: 'Pecho',
    muscles_secondary: ['Tríceps', 'Hombros'],
    equipment: 'Mancuernas',
    instructions: 'Controla la bajada y empuja sin colapsar hombros.',
    movement_pattern: 'Empuje horizontal',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Empuje inclinado para pecho alto.',
  }),
  exercise({
    id: '9d3d4920-e2df-57bf-aba0-fa1f69c6e1c7',
    slug: 'remo_sentado_en_polea_baja',
    name: 'Remo sentado en polea baja',
    muscle_group: 'Espalda',
    muscles_secondary: ['Bíceps'],
    equipment: 'Polea',
    instructions: 'No balancees el torso; cierra escápulas al final.',
    movement_pattern: 'Tirón horizontal',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Tirón guiado y estable.',
  }),
  exercise({
    id: 'fb65685e-941e-5522-be70-1df01aa19a82',
    slug: 'pallof_press_en_polea',
    name: 'Pallof press en polea',
    muscle_group: 'Core',
    muscles_secondary: ['Oblicuos'],
    equipment: 'Polea',
    instructions: 'Empuja al frente sin perder el eje.',
    movement_pattern: 'Anti-rotación',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Core anti-rotacional.',
  }),
  exercise({
    id: 'a184a9bd-812c-5559-9dcf-8fdcd8b8ec13',
    slug: 'dominada_pronada',
    name: 'Dominada pronada',
    muscle_group: 'Espalda',
    muscles_secondary: ['Bíceps', 'Core'],
    equipment: 'Peso corporal',
    instructions: 'Sube el pecho y controla la bajada.',
    movement_pattern: 'Tirón vertical',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Tirón vertical libre.',
  }),
  exercise({
    id: 'd5707805-831a-5197-b7a3-03f1e37a3f72',
    slug: 'face_pull_en_polea_alta',
    name: 'Face pull en polea alta',
    muscle_group: 'Hombros',
    muscles_secondary: ['Espalda'],
    equipment: 'Polea',
    instructions: 'Codos altos y rotación externa controlada.',
    movement_pattern: 'Tirón accesorio',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Salud de hombro y deltoide posterior.',
  }),
  exercise({
    id: '02505bff-0bbd-5e9d-9de8-951a8d5d9d93',
    slug: 'curl_de_biceps_con_barra_ez',
    name: 'Curl de bíceps con barra EZ',
    muscle_group: 'Bíceps',
    muscles_secondary: ['Antebrazos'],
    equipment: 'Barra EZ',
    instructions: 'Codos quietos y recorrido limpio.',
    movement_pattern: 'Flexión de codo',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Accesorio clásico de bíceps.',
  }),
  exercise({
    id: '5c619fef-8c4e-500d-88e0-0a9f37373b5d',
    slug: 'pushdown_de_triceps_con_cuerda',
    name: 'Pushdown de tríceps con cuerda',
    muscle_group: 'Tríceps',
    muscles_secondary: [],
    equipment: 'Polea',
    instructions: 'Codos fijos y extensión completa.',
    movement_pattern: 'Extensión de codo',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Accesorio guiado para tríceps.',
  }),
  exercise({
    id: '42a8879c-d1d2-55de-a64d-c4045e5a019a',
    slug: 'peso_muerto_rumano_con_barra',
    name: 'Peso muerto rumano con barra',
    muscle_group: 'Piernas',
    muscles_secondary: ['Glúteos', 'Espalda'],
    equipment: 'Barra',
    instructions: 'Bisagra pura, rodillas suaves y tensión posterior.',
    movement_pattern: 'Bisagra',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Cadena posterior con foco en isquios.',
  }),
  exercise({
    id: '6a3e8203-1555-5135-8da1-52fac61fcaa1',
    slug: 'prensa_de_piernas_alta',
    name: 'Prensa de piernas alta',
    muscle_group: 'Piernas',
    muscles_secondary: ['Glúteos'],
    equipment: 'Máquina',
    instructions: 'Recorrido controlado sin despegar la cadera.',
    movement_pattern: 'Dominante de rodilla',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Trabajo guiado de tren inferior.',
  }),
  exercise({
    id: '73f43eb4-6078-502b-89bc-b8ff01f95bdf',
    slug: 'curl_femoral_sentado_en_maquina',
    name: 'Curl femoral sentado en máquina',
    muscle_group: 'Piernas',
    muscles_secondary: [],
    equipment: 'Máquina',
    instructions: 'Mantén ritmo estable y aprieta al final.',
    movement_pattern: 'Flexión de rodilla',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Aislamiento de femoral.',
  }),
  exercise({
    id: '80c7b6d3-4fa5-5bf4-89a5-c7430c567825',
    slug: 'elevacion_de_pantorrillas_de_pie',
    name: 'Elevación de pantorrillas de pie',
    muscle_group: 'Pantorrillas',
    muscles_secondary: [],
    equipment: 'Máquina',
    instructions: 'Pausa arriba y estira abajo.',
    movement_pattern: 'Flexión plantar',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Trabajo de pantorrilla.',
  }),
  exercise({
    id: 'ffac29f2-7f28-52b2-88a4-351ad764f3b9',
    slug: 'hip_thrust_con_barra',
    name: 'Hip thrust con barra',
    muscle_group: 'Glúteos',
    muscles_secondary: ['Piernas', 'Core'],
    equipment: 'Barra',
    instructions: 'Bloquea arriba sin hiperextender la espalda.',
    movement_pattern: 'Extensión de cadera',
    difficulty_level: 'Intermedio',
    is_global: true,
    type: 'strength',
    description: 'Principal para glúteos.',
  }),
  exercise({
    id: '8caf2ae0-942b-5f8f-98c1-59b02644dbe3',
    slug: 'patada_de_gluteo_en_polea',
    name: 'Patada de glúteo en polea',
    muscle_group: 'Glúteos',
    muscles_secondary: [],
    equipment: 'Polea',
    instructions: 'Extiende la cadera sin girar la pelvis.',
    movement_pattern: 'Extensión de cadera',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Accesorio local de glúteos.',
  }),
  exercise({
    id: '51a14dec-aab3-5900-9185-8cc05d50027f',
    slug: 'monster_walk_con_banda',
    name: 'Monster walk con banda',
    muscle_group: 'Glúteos',
    muscles_secondary: ['Core'],
    equipment: 'Banda',
    instructions: 'Rodillas activas y pasos cortos con tensión constante.',
    movement_pattern: 'Abducción',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Activación lateral de glúteos.',
  }),
  exercise({
    id: '03438cf6-6d9c-5b10-b70d-fdc751305ce4',
    slug: 'abduccion_de_cadera_en_maquina',
    name: 'Abducción de cadera en máquina',
    muscle_group: 'Glúteos',
    muscles_secondary: [],
    equipment: 'Máquina',
    instructions: 'Abre con control sin usar impulso lumbar.',
    movement_pattern: 'Abducción',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Aislamiento lateral de cadera.',
  }),
  exercise({
    id: '14ff07f1-9620-5491-b3ed-45013f9fcffc',
    slug: 'puente_de_gluteo_unilateral',
    name: 'Puente de glúteo unilateral',
    muscle_group: 'Glúteos',
    muscles_secondary: ['Core', 'Piernas'],
    equipment: 'Peso corporal',
    instructions: 'Empuja con talón y pelvis estable.',
    movement_pattern: 'Extensión de cadera',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Trabajo unilateral de glúteos.',
  }),
  exercise({
    id: '5f29ad14-4d14-54e4-b2c4-edd8a973fcb7',
    slug: 'flexion_estandar',
    name: 'Flexión estándar',
    muscle_group: 'Pecho',
    muscles_secondary: ['Tríceps', 'Core'],
    equipment: 'Peso corporal',
    instructions: 'Cuerpo en bloque y pecho al frente.',
    movement_pattern: 'Empuje horizontal',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Empuje básico sin equipo.',
  }),
  exercise({
    id: 'b4bdbc02-cee8-5fa4-ad61-1c6e00b8a2b4',
    slug: 'sentarse_y_pararse_con_silla',
    name: 'Sentarse y pararse con silla',
    muscle_group: 'Piernas',
    muscles_secondary: ['Glúteos'],
    equipment: 'Peso corporal',
    instructions: 'Apoya todo el pie y sube controlado.',
    movement_pattern: 'Dominante de rodilla',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Base de tren inferior sin material.',
  }),
  exercise({
    id: '82048bfc-f192-5913-8e9c-48b5b2f20418',
    slug: 'mountain_climber_controlado',
    name: 'Mountain climber controlado',
    muscle_group: 'Cardio',
    muscles_secondary: ['Core', 'Hombros'],
    equipment: 'Peso corporal',
    instructions: 'Cadera estable y ritmo sostenido.',
    movement_pattern: 'Acondicionamiento',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'cardio',
    description: 'Condicionamiento simple sin equipo.',
  }),
  exercise({
    id: 'fc7344cd-fd87-5857-9150-22cd8b293347',
    slug: 'assault_bike_20_40',
    name: 'Assault bike 20/40',
    muscle_group: 'Cardio',
    muscles_secondary: ['Piernas', 'Hombros'],
    equipment: 'Máquina',
    instructions: '20 segundos fuerte, 40 suave.',
    movement_pattern: 'Acondicionamiento',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'cardio',
    description: 'Intervalo corto para subir pulsaciones.',
  }),
  exercise({
    id: '1b29c7ad-8679-5f3d-9a46-56244c9d8f7a',
    slug: 'plancha_lateral',
    name: 'Plancha lateral',
    muscle_group: 'Core',
    muscles_secondary: ['Glúteos'],
    equipment: 'Peso corporal',
    instructions: 'Línea recta desde tobillos hasta cabeza.',
    movement_pattern: 'Estabilidad',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'strength',
    description: 'Control lateral del core.',
  }),
  exercise({
    id: '5e771bdd-65dc-5d8f-abef-84fd9f62ee1b',
    slug: 'movilidad_de_cadera_en_colchoneta',
    name: 'Movilidad de cadera en colchoneta',
    muscle_group: 'Movilidad',
    muscles_secondary: ['Core'],
    equipment: 'Colchoneta',
    instructions: 'Muévete lento y respira durante el recorrido.',
    movement_pattern: 'Movilidad',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'mobility',
    description: 'Apertura básica de cadera.',
  }),
  exercise({
    id: '920914b7-8ea5-5cc7-899b-d3ee60ea0f83',
    slug: 'rotacion_toracica_en_colchoneta',
    name: 'Rotación torácica en colchoneta',
    muscle_group: 'Movilidad',
    muscles_secondary: ['Espalda'],
    equipment: 'Colchoneta',
    instructions: 'Busca rotación suave sin forzar la zona lumbar.',
    movement_pattern: 'Movilidad',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'mobility',
    description: 'Rotación de columna dorsal.',
  }),
  exercise({
    id: '0ad76599-29a6-5a83-a9af-11b989e0f86f',
    slug: 'tobillo_rodilla_a_pared_controlado',
    name: 'Tobillo rodilla a pared controlado',
    muscle_group: 'Movilidad',
    muscles_secondary: ['Piernas'],
    equipment: 'Peso corporal',
    instructions: 'Avanza la rodilla sin despegar el talón.',
    movement_pattern: 'Movilidad',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'mobility',
    description: 'Movilidad de tobillo.',
  }),
  exercise({
    id: '9a4d78ac-5ee2-56a4-8b8d-6458ffe46b41',
    slug: 'extension_toracica_en_foam_roller',
    name: 'Extensión torácica en foam roller',
    muscle_group: 'Movilidad',
    muscles_secondary: ['Espalda'],
    equipment: 'Foam roller',
    instructions: 'Abre el pecho y extiende sin perder costillas controladas.',
    movement_pattern: 'Movilidad',
    difficulty_level: 'Inicial',
    is_global: true,
    type: 'mobility',
    description: 'Extensión torácica asistida.',
  }),
];

export const GENERATED_WORKOUT_ROUTINES: Routine[] = [
  seedRoutine({
    id: 'c52ec8e6-0f0a-5baf-ad2d-705955237582',
    slug: 'foundation_full_body_a',
    name: 'Base total A',
    description: 'Full body simple para volver a entrenar con básicos estables.',
    split_tag: 'Full body',
    estimated_duration_min: 55,
    schedule_day: 'Lunes',
    goal_tag: 'Fuerza base',
    is_primary: true,
    exercises: [
      routineExercise('6fab3ac3-aa88-5970-921e-651b2ffa095a', 'Sentadilla con barra', 4, 6, 60, 0, 90),
      routineExercise('4dbd0202-6649-54a3-95ca-d437d3b3c56a', 'Press de banca con barra', 4, 6, 45, 1, 90),
      routineExercise('45f587b5-9858-5513-b305-277e072b99d8', 'Remo con barra', 3, 8, 42.5, 2, 90),
      routineExercise('abee45f4-b1ce-5220-bbd7-21211759d1f5', 'Plancha frontal', 3, 45, 0, 3, 60),
    ],
  }),
  seedRoutine({
    id: '021b2736-17de-59ee-a557-c3527ca322c6',
    slug: 'foundation_full_body_b',
    name: 'Base total B',
    description: 'Bisagra, empuje vertical y tirón controlado.',
    split_tag: 'Full body',
    estimated_duration_min: 54,
    schedule_day: 'Miércoles',
    goal_tag: 'Fuerza base',
    is_primary: false,
    exercises: [
      routineExercise('c0af26a4-16cc-5bb3-b42f-e3c91e8324f6', 'Peso muerto con barra', 4, 5, 80, 0, 150),
      routineExercise('2a3336e2-6165-5a88-90b9-6c1737220f9a', 'Press militar con barra', 4, 6, 30, 1, 90),
      routineExercise('dd99446f-63f1-54bb-aab6-15b443490678', 'Jalón al pecho pronado', 3, 10, 40, 2, 90),
      routineExercise('1bb29304-beb8-5403-a18f-0e1727c87c49', 'Dead bug estándar', 3, 10, 0, 3, 60),
    ],
  }),
  seedRoutine({
    id: '289aff2b-c8e0-5415-8ea7-34afbc672722',
    slug: 'foundation_full_body_c',
    name: 'Base total C',
    description: 'Cierre semanal con piernas unilaterales y torso estable.',
    split_tag: 'Full body',
    estimated_duration_min: 52,
    schedule_day: 'Viernes',
    goal_tag: 'Fuerza base',
    is_primary: false,
    exercises: [
      routineExercise('bece1220-5689-5f42-b8b9-429e2b7b6135', 'Sentadilla goblet', 4, 10, 24, 0, 90),
      routineExercise('41f00082-74b2-5b36-9533-db311c9bbf7a', 'Press inclinado con mancuernas', 4, 10, 18, 1, 90),
      routineExercise('9d3d4920-e2df-57bf-aba0-fa1f69c6e1c7', 'Remo sentado en polea baja', 3, 12, 40, 2, 90),
      routineExercise('fb65685e-941e-5522-be70-1df01aa19a82', 'Pallof press en polea', 3, 12, 12, 3, 60),
    ],
  }),
  seedRoutine({
    id: 'afb64124-f493-5f84-a1b0-da78661a351b',
    slug: 'upper_strength_a',
    name: 'Upper fuerza A',
    description: 'Torso fuerte con empujes y tirones pesados.',
    split_tag: 'Upper',
    estimated_duration_min: 60,
    schedule_day: 'Lunes',
    goal_tag: 'Fuerza',
    is_primary: false,
    exercises: [
      routineExercise('4dbd0202-6649-54a3-95ca-d437d3b3c56a', 'Press de banca con barra', 5, 5, 50, 0, 150),
      routineExercise('a184a9bd-812c-5559-9dcf-8fdcd8b8ec13', 'Dominada pronada', 4, 6, 0, 1, 120),
      routineExercise('2a3336e2-6165-5a88-90b9-6c1737220f9a', 'Press militar con barra', 4, 6, 32.5, 2, 90),
      routineExercise('d5707805-831a-5197-b7a3-03f1e37a3f72', 'Face pull en polea alta', 3, 15, 18, 3, 60),
      routineExercise('02505bff-0bbd-5e9d-9de8-951a8d5d9d93', 'Curl de bíceps con barra EZ', 3, 10, 20, 4, 60),
      routineExercise('5c619fef-8c4e-500d-88e0-0a9f37373b5d', 'Pushdown de tríceps con cuerda', 3, 12, 20, 5, 60),
    ],
  }),
  seedRoutine({
    id: 'd1964882-dfb0-5ae0-a251-1412568798e6',
    slug: 'lower_strength_a',
    name: 'Lower fuerza A',
    description: 'Bloque inferior con sentadilla, bisagra y soporte.',
    split_tag: 'Lower',
    estimated_duration_min: 62,
    schedule_day: 'Martes',
    goal_tag: 'Fuerza',
    is_primary: false,
    exercises: [
      routineExercise('6fab3ac3-aa88-5970-921e-651b2ffa095a', 'Sentadilla con barra', 5, 5, 70, 0, 150),
      routineExercise('42a8879c-d1d2-55de-a64d-c4045e5a019a', 'Peso muerto rumano con barra', 4, 8, 65, 1, 120),
      routineExercise('6a3e8203-1555-5135-8da1-52fac61fcaa1', 'Prensa de piernas alta', 3, 10, 120, 2, 90),
      routineExercise('73f43eb4-6078-502b-89bc-b8ff01f95bdf', 'Curl femoral sentado en máquina', 3, 12, 35, 3, 90),
      routineExercise('80c7b6d3-4fa5-5bf4-89a5-c7430c567825', 'Elevación de pantorrillas de pie', 4, 12, 30, 4, 45),
    ],
  }),
  seedRoutine({
    id: '7953f9a2-22f2-540e-85ad-8051c03212f6',
    slug: 'glutes_focus',
    name: 'Glúteos foco',
    description: 'Sesión centrada en glúteos para sumar trabajo local.',
    split_tag: 'Glúteos',
    estimated_duration_min: 50,
    schedule_day: 'Jueves',
    goal_tag: 'Hipertrofia',
    is_primary: false,
    exercises: [
      routineExercise('ffac29f2-7f28-52b2-88a4-351ad764f3b9', 'Hip thrust con barra', 4, 8, 90, 0, 90),
      routineExercise('8caf2ae0-942b-5f8f-98c1-59b02644dbe3', 'Patada de glúteo en polea', 3, 15, 10, 1, 60),
      routineExercise('51a14dec-aab3-5900-9185-8cc05d50027f', 'Monster walk con banda', 3, 20, 0, 2, 45),
      routineExercise('03438cf6-6d9c-5b10-b70d-fdc751305ce4', 'Abducción de cadera en máquina', 3, 18, 28, 3, 45),
      routineExercise('14ff07f1-9620-5491-b3ed-45013f9fcffc', 'Puente de glúteo unilateral', 3, 12, 0, 4, 45),
    ],
  }),
  seedRoutine({
    id: '76cda985-52ee-563a-8faa-60489726eef2',
    slug: 'home_bodyweight',
    name: 'Casa sin equipo',
    description: 'Entreno simple para no cortar continuidad sin gimnasio.',
    split_tag: 'Casa',
    estimated_duration_min: 32,
    schedule_day: 'Flexible',
    goal_tag: 'Continuidad',
    is_primary: false,
    exercises: [
      routineExercise('5f29ad14-4d14-54e4-b2c4-edd8a973fcb7', 'Flexión estándar', 4, 12, 0, 0, 60),
      routineExercise('b4bdbc02-cee8-5fa4-ad61-1c6e00b8a2b4', 'Sentarse y pararse con silla', 4, 12, 0, 1, 60),
      routineExercise('abee45f4-b1ce-5220-bbd7-21211759d1f5', 'Plancha frontal', 3, 40, 0, 2, 45),
      routineExercise('82048bfc-f192-5913-8e9c-48b5b2f20418', 'Mountain climber controlado', 3, 20, 0, 3, 45),
    ],
  }),
  seedRoutine({
    id: '0ae60398-45d1-57da-9ea7-cb712ac3456a',
    slug: 'express_cardio_core',
    name: 'Express cardio + core',
    description: 'Bloque corto para mover pulsaciones y salir mejor.',
    split_tag: 'Express',
    estimated_duration_min: 26,
    schedule_day: 'Sábado',
    goal_tag: 'Cardio',
    is_primary: false,
    exercises: [
      routineExercise('fc7344cd-fd87-5857-9150-22cd8b293347', 'Assault bike 20/40', 6, 1, 0, 0, 40, '20 segundos fuerte / 40 suave'),
      routineExercise('1b29c7ad-8679-5f3d-9a46-56244c9d8f7a', 'Plancha lateral', 3, 30, 0, 1, 45),
      routineExercise('1bb29304-beb8-5403-a18f-0e1727c87c49', 'Dead bug estándar', 3, 10, 0, 2, 45),
    ],
  }),
  seedRoutine({
    id: 'd5a705d8-9353-5151-9978-87af4b1d108b',
    slug: 'mobility_reset',
    name: 'Reset de movilidad',
    description: 'Sesión suave para recuperar rango y bajar rigidez.',
    split_tag: 'Movilidad',
    estimated_duration_min: 28,
    schedule_day: 'Domingo',
    goal_tag: 'Recuperación',
    is_primary: false,
    exercises: [
      routineExercise('5e771bdd-65dc-5d8f-abef-84fd9f62ee1b', 'Movilidad de cadera en colchoneta', 2, 8, 0, 0, 30),
      routineExercise('920914b7-8ea5-5cc7-899b-d3ee60ea0f83', 'Rotación torácica en colchoneta', 2, 8, 0, 1, 30),
      routineExercise('0ad76599-29a6-5a83-a9af-11b989e0f86f', 'Tobillo rodilla a pared controlado', 2, 8, 0, 2, 30),
      routineExercise('9a4d78ac-5ee2-56a4-8b8d-6458ffe46b41', 'Extensión torácica en foam roller', 2, 8, 0, 3, 30),
    ],
  }),
];

export const GENERATED_WORKOUT_TEMPLATE_ROUTINES: Routine[] = [
  seedRoutine({
    id: 'template_home_reset',
    slug: 'template_home_reset',
    name: 'Template casa reset',
    description: 'Plantilla breve para semanas con menos tiempo.',
    split_tag: 'Template',
    estimated_duration_min: 30,
    goal_tag: 'Continuidad',
    is_primary: false,
    is_template: true,
    source: 'template',
    exercises: [
      routineExercise('5f29ad14-4d14-54e4-b2c4-edd8a973fcb7', 'Flexión estándar', 3, 10, 0, 0, 60),
      routineExercise('b4bdbc02-cee8-5fa4-ad61-1c6e00b8a2b4', 'Sentarse y pararse con silla', 3, 12, 0, 1, 60),
      routineExercise('abee45f4-b1ce-5220-bbd7-21211759d1f5', 'Plancha frontal', 3, 30, 0, 2, 45),
    ],
  }),
  seedRoutine({
    id: 'template_glutes_base',
    slug: 'template_glutes_base',
    name: 'Template glúteos base',
    description: 'Plantilla corta para glúteos y posterior.',
    split_tag: 'Template',
    estimated_duration_min: 38,
    goal_tag: 'Glúteos',
    is_primary: false,
    is_template: true,
    source: 'template',
    exercises: [
      routineExercise('ffac29f2-7f28-52b2-88a4-351ad764f3b9', 'Hip thrust con barra', 4, 8, 70, 0, 90),
      routineExercise('42a8879c-d1d2-55de-a64d-c4045e5a019a', 'Peso muerto rumano con barra', 3, 8, 50, 1, 90),
      routineExercise('03438cf6-6d9c-5b10-b70d-fdc751305ce4', 'Abducción de cadera en máquina', 3, 15, 20, 2, 45),
    ],
  }),
  seedRoutine({
    id: 'template_mobility_day',
    slug: 'template_mobility_day',
    name: 'Template movilidad',
    description: 'Plantilla breve para recuperar rango útil.',
    split_tag: 'Template',
    estimated_duration_min: 22,
    goal_tag: 'Movilidad',
    is_primary: false,
    is_template: true,
    source: 'template',
    exercises: [
      routineExercise('5e771bdd-65dc-5d8f-abef-84fd9f62ee1b', 'Movilidad de cadera en colchoneta', 2, 8, 0, 0, 30),
      routineExercise('920914b7-8ea5-5cc7-899b-d3ee60ea0f83', 'Rotación torácica en colchoneta', 2, 8, 0, 1, 30),
      routineExercise('9a4d78ac-5ee2-56a4-8b8d-6458ffe46b41', 'Extensión torácica en foam roller', 2, 8, 0, 2, 30),
    ],
  }),
];

export const GENERATED_WORKOUT_PROGRAMS: WorkoutProgram[] = [
  workoutProgram({
    id: '273cad13-6b5e-57b9-92a0-71eeac540a21',
    slug: 'foundation_3d',
    name: 'Fundación 3 días',
    split_tag: 'Full body',
    difficulty_level: 'Inicial',
    days_per_week: 3,
    estimated_session_min: 55,
    duration_weeks: 6,
    routine_ids: [
      'c52ec8e6-0f0a-5baf-ad2d-705955237582',
      '021b2736-17de-59ee-a557-c3527ca322c6',
      '289aff2b-c8e0-5415-8ea7-34afbc672722',
    ],
    target_muscles: ['Piernas', 'Pecho', 'Espalda', 'Core'],
    is_premium_only: false,
    objective: 'Volver a entrenar con una base clara y progresión simple.',
    structure: 'Tres sesiones full body con foco en técnica y continuidad.',
    duration_label: '6 semanas',
    next_program_name: 'Fuerza 4 días',
    session_count: 3,
    exercise_count: 12,
  }),
  workoutProgram({
    id: '024dc030-16e3-5b7b-b39d-2cd52618c2a4',
    slug: 'strength_4d',
    name: 'Fuerza 4 días',
    split_tag: 'Upper/Lower',
    difficulty_level: 'Intermedio',
    days_per_week: 4,
    estimated_session_min: 61,
    duration_weeks: 8,
    routine_ids: [
      'afb64124-f493-5f84-a1b0-da78661a351b',
      'd1964882-dfb0-5ae0-a251-1412568798e6',
      '021b2736-17de-59ee-a557-c3527ca322c6',
      '289aff2b-c8e0-5415-8ea7-34afbc672722',
    ],
    target_muscles: ['Piernas', 'Pecho', 'Espalda', 'Hombros'],
    is_premium_only: false,
    objective: 'Subir fuerza en básicos sin perder orden semanal.',
    structure: 'Dos días pesados y dos de soporte para seguir progresando.',
    duration_label: '8 semanas',
    next_program_name: 'Glúteos 4 días',
    session_count: 4,
    exercise_count: 20,
  }),
  workoutProgram({
    id: 'cf87bd59-b9f6-5336-a10d-90bbdeec9ec8',
    slug: 'glutes_4d',
    name: 'Glúteos 4 días',
    split_tag: 'Glúteos',
    difficulty_level: 'Intermedio',
    days_per_week: 4,
    estimated_session_min: 50,
    duration_weeks: 6,
    routine_ids: [
      '7953f9a2-22f2-540e-85ad-8051c03212f6',
      'd1964882-dfb0-5ae0-a251-1412568798e6',
      'd5a705d8-9353-5151-9978-87af4b1d108b',
      '7953f9a2-22f2-540e-85ad-8051c03212f6',
    ],
    target_muscles: ['Glúteos', 'Piernas', 'Core'],
    is_premium_only: false,
    objective: 'Dar más volumen útil a glúteos sin romper la semana.',
    structure: 'Dos días principales, un soporte de fuerza y un reset.',
    duration_label: '6 semanas',
    next_program_name: 'Fuerza 4 días',
    session_count: 4,
    exercise_count: 19,
  }),
  workoutProgram({
    id: '0bfb4919-ef3c-5ec9-a6e9-1742de56a830',
    slug: 'home_bodyweight_3d',
    name: 'Casa 3 días',
    split_tag: 'Casa',
    difficulty_level: 'Inicial',
    days_per_week: 3,
    estimated_session_min: 30,
    duration_weeks: 5,
    routine_ids: [
      '76cda985-52ee-563a-8faa-60489726eef2',
      '0ae60398-45d1-57da-9ea7-cb712ac3456a',
      'd5a705d8-9353-5151-9978-87af4b1d108b',
    ],
    target_muscles: ['Core', 'Cardio', 'Pecho', 'Piernas'],
    is_premium_only: false,
    objective: 'Entrenar en casa sin perder claridad ni continuidad.',
    structure: 'Un día de fuerza simple, uno de cardio y uno de movilidad.',
    duration_label: '5 semanas',
    next_program_name: 'Fundación 3 días',
    session_count: 3,
    exercise_count: 11,
  }),
  workoutProgram({
    id: '10bafebb-f65c-5976-91bf-a9e8efb0b9a6',
    slug: 'rebuild_express',
    name: 'Rebuild express',
    split_tag: 'Express',
    difficulty_level: 'Inicial',
    days_per_week: 3,
    estimated_session_min: 29,
    duration_weeks: 4,
    routine_ids: [
      '76cda985-52ee-563a-8faa-60489726eef2',
      '0ae60398-45d1-57da-9ea7-cb712ac3456a',
      'd5a705d8-9353-5151-9978-87af4b1d108b',
    ],
    target_muscles: ['Cardio', 'Core', 'Movilidad'],
    is_premium_only: false,
    objective: 'Volver a sumar sesiones aunque la semana esté cargada.',
    structure: 'Dos días cortos y un reset para sostener el hábito.',
    duration_label: '4 semanas',
    next_program_name: 'Fundación 3 días',
    session_count: 3,
    exercise_count: 11,
  }),
];

export const GENERATED_WORKOUT_FAVORITES: string[] = [
  '6fab3ac3-aa88-5970-921e-651b2ffa095a',
  '4dbd0202-6649-54a3-95ca-d437d3b3c56a',
  '45f587b5-9858-5513-b305-277e072b99d8',
  'ffac29f2-7f28-52b2-88a4-351ad764f3b9',
  'abee45f4-b1ce-5220-bbd7-21211759d1f5',
];
